## Trial-level early stopping in Ax

This tutorial illustrates how to add a trial-level early stopping strategy to an Ax hyper-parameter optimization (HPO) loop. The goal of trial-level early stopping is to monitor the results of expensive evaluations and terminate those that are unlikely to produce promising results, freeing up resources to explore more configurations.

Most of this tutorial is adapted from the [PyTorch Ax Multiobjective NAS Tutorial](https://pytorch.org/tutorials/intermediate/ax_multiobjective_nas_tutorial.html). The training job is different from the original in that we do not optimize `batch_size` or `epochs`. This was done for illustrative purposes, as each validation curve now has the same number of points. The companion training file `mnist_train_nas.py` has also been altered to log to Tensorboard during training.

NOTE: Although the original NAS tutorial is for a multi-objective problem, this tutorial focuses on a single objective (validation accuracy) problem. Early stopping currently does not support \"true\" multi-objective stopping, although one can use [logical compositions of early stopping strategies](https://github.com/facebook/Ax/blob/main/ax/early_stopping/strategies/logical.py) to target multiple objectives separately. Early stopping for the multi-objective case is currently a work in progress.

In [1]:
import os
import tempfile

from pathlib import Path

import torchx

from ax.core import Experiment, Objective, ParameterType, RangeParameter, SearchSpace
from ax.core.optimization_config import OptimizationConfig

from ax.early_stopping.strategies import PercentileEarlyStoppingStrategy
from ax.metrics.tensorboard import TensorboardMetric

from ax.modelbridge.dispatch_utils import choose_generation_strategy

from ax.runners.torchx import TorchXRunner

from ax.service.scheduler import Scheduler, SchedulerOptions
from ax.service.utils.report_utils import exp_to_df

from tensorboard.backend.event_processing import plugin_event_multiplexer as event_multiplexer

from torchx import specs
from torchx.components import utils

from matplotlib import pyplot as plt


%matplotlib inline

In [2]:
SMOKE_TEST = os.environ.get("SMOKE_TEST")

## Defining the TorchX App

Our goal is to optimize the PyTorch Lightning training job defined in
[mnist_train_nas.py](https://github.com/pytorch/tutorials/tree/master/intermediate_source/mnist_train_nas.py)_.
To do this using TorchX, we write a helper function that takes in
the values of the architcture and hyperparameters of the training
job and creates a [TorchX AppDef](https://pytorch.org/torchx/latest/basics.html)_
with the appropriate settings.

In [3]:
if SMOKE_TEST:
    epochs = 3
else:
    epochs = 10

In [4]:
def trainer(
    log_path: str,
    hidden_size_1: int,
    hidden_size_2: int,
    learning_rate: float,
    dropout: float,
    trial_idx: int = -1,
) -> specs.AppDef:

    # define the log path so we can pass it to the TorchX AppDef
    if trial_idx >= 0:
        log_path = Path(log_path).joinpath(str(trial_idx)).absolute().as_posix()

    batch_size = 32

    return utils.python(
        # command line args to the training script
        "--log_path",
        log_path,
        "--hidden_size_1",
        str(hidden_size_1),
        "--hidden_size_2",
        str(hidden_size_2),
        "--learning_rate",
        str(learning_rate),
        "--epochs",
        str(epochs),
        "--dropout",
        str(dropout),
        "--batch_size",
        str(batch_size),
        # other config options
        name="trainer",
        script="tutorials/early_stopping/mnist_train_nas.py",
        image=torchx.version.TORCHX_IMAGE,
    )

## Setting up the Runner

Ax’s [Runner](https://ax.dev/api/core.html#ax.core.runner.Runner)
abstraction allows writing interfaces to various backends.
Ax already comes with Runner for TorchX, so we just need to
configure it. For the purpose of this tutorial, we run jobs locally
in a fully asynchronous fashion. In order to launch them on a cluster, you can instead specify a
different TorchX scheduler and adjust the configuration appropriately.
For example, if you have a Kubernetes cluster, you just need to change the
scheduler from ``local_cwd`` to ``kubernetes``.

The training job launched by this runner will log partial results to Tensorboard, which will then be monitored by the early stopping strategy. We will show how this is done using an Ax 
[TensorboardMetric](https://ax.dev/api/metrics.html#module-ax.metrics.tensorboard) below.

In [5]:
# Make a temporary dir to log our results into
log_dir = tempfile.mkdtemp()

ax_runner = TorchXRunner(
    tracker_base="/tmp/",
    component=trainer,
    # NOTE: To launch this job on a cluster instead of locally you can
    # specify a different scheduler and adjust args appropriately.
    scheduler="local_cwd",
    component_const_params={"log_path": log_dir},
    cfg={},
)

## Setting up the SearchSpace

First, we define our search space. Ax supports both range parameters
of type integer and float as well as choice parameters which can have
non-numerical types such as strings.
We will tune the hidden sizes, learning rate, and dropout parameters.

In [6]:
parameters = [
    # NOTE: In a real-world setting, hidden_size_1 and hidden_size_2
    # should probably be powers of 2, but in our simple example this
    # would mean that num_params can't take on that many values, which
    # in turn makes the Pareto frontier look pretty weird.
    RangeParameter(
        name="hidden_size_1",
        lower=16,
        upper=128,
        parameter_type=ParameterType.INT,
        log_scale=True,
    ),
    RangeParameter(
        name="hidden_size_2",
        lower=16,
        upper=128,
        parameter_type=ParameterType.INT,
        log_scale=True,
    ),
    RangeParameter(
        name="learning_rate",
        lower=1e-4,
        upper=1e-2,
        parameter_type=ParameterType.FLOAT,
        log_scale=True,
    ),
    RangeParameter(
        name="dropout",
        lower=0.0,
        upper=0.5,
        parameter_type=ParameterType.FLOAT,
    ),
]

search_space = SearchSpace(
    parameters=parameters,
    # NOTE: In practice, it may make sense to add a constraint
    # hidden_size_2 <= hidden_size_1
    parameter_constraints=[],
)

## Setting up Metrics

Ax has the concept of a Metric that defines properties of outcomes and how observations are obtained for these outcomes. This allows e.g. encodig how data is fetched from some distributed execution backend and post-processed before being passed as input to Ax.

We will optimize the validation accuracy, which is a `TensorboardMetric` that points to the logging directory assigned above. Note that we have set `is_available_while_running`, allowing for the metric to be queried as the trial progresses. This is critical for the early stopping strategy to monitor partial results.

In [7]:
class MyTensorboardMetric(TensorboardMetric):

    # NOTE: We need to tell the new Tensorboard metric how to get the id /
    # file handle for the tensorboard logs from a trial. In this case
    # our convention is to just save a separate file per trial in
    # the pre-specified log dir.
    def _get_event_multiplexer_for_trial(self, trial):
        mul = event_multiplexer.EventMultiplexer(max_reload_threads=20)
        mul.AddRunsFromDirectory(Path(log_dir).joinpath(str(trial.index)).as_posix(), None)
        mul.Reload()

        return mul

    # This indicates whether the metric is queryable while the trial is
    # still running. This is required for early stopping to monitor the
    # progress of the running trial.ArithmeticError
    @classmethod
    def is_available_while_running(cls):
        return True

In [8]:
val_acc = MyTensorboardMetric(
    name="val_acc",
    tag="val_acc",
    lower_is_better=False,
)

## Setting up the OptimizationConfig

The `OptimizationConfig` specifies the objective for Ax to optimize.

In [9]:
opt_config = OptimizationConfig(
    objective=Objective(
        metric=val_acc,
        minimize=False,
    )
)

## Defining an Early Stopping Strategy

A `PercentileEarlyStoppingStrategy` is a simple method that stops a trial if its performance falls below a certain percentile of other trials at the same step (e.g., when `percentile_threshold` is 50, at a given point in time, if a trial ranks in the bottom 50% of trials, it is stopped). 
- We make use of `normalize_progressions` which normalizes the progression column (e.g. timestamp, epochs, training data used) to be in [0, 1]. This is useful because one doesn't need to know the maximum progression values of the curve (which might be, e.g., the total number of data points in the training dataset).
- The `min_progression` parameter specifies that trials should only be considered for stopping if the latest progression value is greater than this threshold.
- The `min_curves` parameter specifies the minimum number of completed curves (i.e., fully completed training jobs) before early stopping will be considered. This should be larger than zero if `normalize_progression` is used. In general, we want a few completed curves to have a baseline for comparison.

Note that `PercentileEarlyStoppingStrategy` does not make use of learning curve modeling or prediction. More sophisticated model-based methods will be available in future versions of Ax.

In [10]:
percentile_early_stopping_strategy = PercentileEarlyStoppingStrategy(
    # stop if in bottom 70% of runs at the same progression
    percentile_threshold=70,
    # the trial must have passed `min_progression` steps before early stopping is initiated
    # note that we are using `normalize_progressions`, so this is on a scale of [0, 1]
    min_progression=0.3,
    # there must be `min_curves` completed trials and `min_curves` trials reporting data in
    # order for early stopping to be applicable
    min_curves=5,
    # specify, e.g., [0, 1] if the first two trials should never be stopped
    trial_indices_to_ignore=None,
    # check for new data every 10 seconds
    seconds_between_polls=10,
    normalize_progressions=True,
)

## Creating the Ax Experiment

In Ax, the Experiment object is the object that stores all the information about the problem setup.

In [11]:
experiment = Experiment(
    name="torchx_mnist",
    search_space=search_space,
    optimization_config=opt_config,
    runner=ax_runner,
)

## Choosing the GenerationStrategy

A [GenerationStrategy](https://ax.dev/api/modelbridge.html#ax.modelbridge.generation_strategy.GenerationStrategy)
is the abstract representation of how we would like to perform the
optimization. While this can be customized (if you’d like to do so, see
[this tutorial](https://ax.dev/tutorials/generation_strategy.html)),
in most cases Ax can automatically determine an appropriate strategy
based on the search space, optimization config, and the total number
of trials we want to run.

Typically, Ax chooses to evaluate a number of random configurations
before starting a model-based Bayesian Optimization strategy.

We remark that in Ax, generation strategies and early stopping strategies are separate, a design decision motivated by ease-of-use. However, we should acknowledge that jointly considering generation and stopping using a single strategy would likely be the "proper" formulation.

In [12]:
if SMOKE_TEST:
    total_trials = 6
else:
    total_trials = 15  # total evaluation budget

gs = choose_generation_strategy(
    search_space=experiment.search_space,
    optimization_config=experiment.optimization_config,
    num_trials=total_trials,
)

[INFO 12-19 06:45:21] ax.modelbridge.dispatch_utils: Using Models.BOTORCH_MODULAR since there is at least one ordered parameter and there are no unordered categorical parameters.

[INFO 12-19 06:45:21] ax.modelbridge.dispatch_utils: Calculating the number of remaining initialization trials based on num_initialization_trials=None max_initialization_trials=None num_tunable_parameters=4 num_trials=15 use_batch_trials=False

[INFO 12-19 06:45:21] ax.modelbridge.dispatch_utils: calculated num_initialization_trials=5

[INFO 12-19 06:45:21] ax.modelbridge.dispatch_utils: num_completed_initialization_trials=0 num_remaining_initialization_trials=5

[INFO 12-19 06:45:21] ax.modelbridge.dispatch_utils: `verbose`, `disable_progbar`, and `jit_compile` are not yet supported when using `choose_generation_strategy` with ModularBoTorchModel, dropping these arguments.

[INFO 12-19 06:45:21] ax.modelbridge.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BoTorch', steps=[Sobol for 5 trials, BoTorch for subsequent trials]). Iterations after 5 will take longer to generate due to model-fitting.

## Configuring the Scheduler

The `Scheduler` acts as the loop control for the optimization.
It communicates with the backend to launch trials, check their status, retrieve (partial) results, and importantly for this tutorial, calls the early stopping strategy. If the early stopping strategy suggests a trial to be the stopped, the `Scheduler` communicates with the backend to terminate the trial.

The ``Scheduler`` requires the ``Experiment`` and the ``GenerationStrategy``.
A set of options can be passed in via ``SchedulerOptions``. Here, we
configure the number of total evaluations as well as ``max_pending_trials``,
the maximum number of trials that should run concurrently. In our
local setting, this is the number of training jobs running as individual
processes, while in a remote execution setting, this would be the number
of machines you want to use in parallel.

In [13]:
scheduler = Scheduler(
    experiment=experiment,
    generation_strategy=gs,
    options=SchedulerOptions(
        total_trials=total_trials,
        max_pending_trials=5,
        early_stopping_strategy=percentile_early_stopping_strategy,
    ),
)

[INFO 12-19 06:45:21] Scheduler: `Scheduler` requires experiment to have immutable search space and optimization config. Setting property immutable_search_space_and_opt_config to `True` on experiment.

In [14]:
%%time
scheduler.run_all_trials()

[INFO 12-19 06:45:21] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 12-19 06:45:21] Scheduler: Running trials [0]...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 12-19 06:45:22] Scheduler: Running trials [1]...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 12-19 06:45:23] Scheduler: Running trials [2]...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 12-19 06:45:24] Scheduler: Running trials [3]...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 12-19 06:45:25] Scheduler: Running trials [4]...

[WARNING 12-19 06:45:25] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

[INFO 12-19 06:45:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e45b0>")

[INFO 12-19 06:45:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e40a0>")

[INFO 12-19 06:45:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4dc0>")

[INFO 12-19 06:45:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4e20>")

[INFO 12-19 06:45:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5630>")

[ERROR 12-19 06:45:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e45b0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e40a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4dc0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4e20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5630>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:45:25] Scheduler: Failed to fetch val_acc for trial 0, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e45b0>").

[INFO 12-19 06:45:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 0 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:25] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e40a0>").

[INFO 12-19 06:45:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:25] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4dc0>").

[INFO 12-19 06:45:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:25] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4e20>").

[INFO 12-19 06:45:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:25] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5630>").

[INFO 12-19 06:45:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:45:25] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 12-19 06:45:25] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:45:35] Scheduler: Retrieved FAILED trials: [0].

[INFO 12-19 06:45:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5360>")

[INFO 12-19 06:45:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e68c0>")

[INFO 12-19 06:45:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5420>")

[INFO 12-19 06:45:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e54b0>")

[ERROR 12-19 06:45:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5360>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e68c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5420>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e54b0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:45:35] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5360>").

[INFO 12-19 06:45:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:35] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e68c0>").

[INFO 12-19 06:45:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:35] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5420>").

[INFO 12-19 06:45:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:35] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e54b0>").

[INFO 12-19 06:45:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:45:35] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 12-19 06:45:35] Scheduler: Running trials [5]...

[WARNING 12-19 06:45:36] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

[INFO 12-19 06:45:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7610>")

[INFO 12-19 06:45:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5a20>")

[INFO 12-19 06:45:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6c50>")

[INFO 12-19 06:45:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4370>")

[INFO 12-19 06:45:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7130>")

[ERROR 12-19 06:45:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7610>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5a20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6c50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4370>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7130>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:45:36] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7610>").

[INFO 12-19 06:45:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:36] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5a20>").

[INFO 12-19 06:45:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:36] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6c50>").

[INFO 12-19 06:45:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:36] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4370>").

[INFO 12-19 06:45:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:36] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7130>").

[INFO 12-19 06:45:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:45:36] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 12-19 06:45:36] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:45:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e65f0>")

[INFO 12-19 06:45:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4250>")

[INFO 12-19 06:45:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7310>")

[INFO 12-19 06:45:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5b40>")

[INFO 12-19 06:45:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5390>")

[ERROR 12-19 06:45:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e65f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4250>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7310>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5b40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5390>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:45:46] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e65f0>").

[INFO 12-19 06:45:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:46] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4250>").

[INFO 12-19 06:45:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:46] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7310>").

[INFO 12-19 06:45:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:46] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5b40>").

[INFO 12-19 06:45:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:46] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5390>").

[INFO 12-19 06:45:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:45:46] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 12-19 06:45:46] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:45:56] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7220>")

[INFO 12-19 06:45:56] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7340>")

[INFO 12-19 06:45:56] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4370>")

[INFO 12-19 06:45:56] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6ce0>")

[INFO 12-19 06:45:56] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6bf0>")

[ERROR 12-19 06:45:56] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7220>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:56] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7340>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:56] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4370>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:56] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6ce0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:45:56] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6bf0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:45:56] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7220>").

[INFO 12-19 06:45:56] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:56] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7340>").

[INFO 12-19 06:45:56] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:56] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4370>").

[INFO 12-19 06:45:56] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:56] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6ce0>").

[INFO 12-19 06:45:56] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:45:56] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6bf0>").

[INFO 12-19 06:45:56] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:45:56] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 12-19 06:45:56] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:46:06] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e70d0>")

[INFO 12-19 06:46:06] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e65c0>")

[INFO 12-19 06:46:06] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e77c0>")

[INFO 12-19 06:46:06] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5ed0>")

[INFO 12-19 06:46:06] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e79d0>")

[ERROR 12-19 06:46:06] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e70d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:06] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e65c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:06] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e77c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:06] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5ed0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:06] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e79d0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:46:06] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e70d0>").

[INFO 12-19 06:46:06] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:06] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e65c0>").

[INFO 12-19 06:46:06] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:06] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e77c0>").

[INFO 12-19 06:46:06] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:06] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5ed0>").

[INFO 12-19 06:46:06] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:06] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e79d0>").

[INFO 12-19 06:46:06] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:46:06] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 12-19 06:46:06] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:46:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7ac0>")

[INFO 12-19 06:46:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7a00>")

[INFO 12-19 06:46:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7340>")

[INFO 12-19 06:46:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6380>")

[INFO 12-19 06:46:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7640>")

[ERROR 12-19 06:46:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7ac0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7a00>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7340>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6380>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7640>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:46:17] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7ac0>").

[INFO 12-19 06:46:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:17] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7a00>").

[INFO 12-19 06:46:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:17] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7340>").

[INFO 12-19 06:46:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:17] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6380>").

[INFO 12-19 06:46:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:17] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7640>").

[INFO 12-19 06:46:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:46:17] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 12-19 06:46:17] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:46:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7760>")

[INFO 12-19 06:46:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7460>")

[INFO 12-19 06:46:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7220>")

[INFO 12-19 06:46:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7610>")

[INFO 12-19 06:46:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7a90>")

[ERROR 12-19 06:46:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7760>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7460>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7220>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7610>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7a90>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:46:27] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7760>").

[INFO 12-19 06:46:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:27] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7460>").

[INFO 12-19 06:46:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:27] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7220>").

[INFO 12-19 06:46:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:27] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7610>").

[INFO 12-19 06:46:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:27] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7a90>").

[INFO 12-19 06:46:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:46:27] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 12-19 06:46:27] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:46:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7130>")

[INFO 12-19 06:46:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5cc0>")

[INFO 12-19 06:46:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e71f0>")

[INFO 12-19 06:46:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6d70>")

[INFO 12-19 06:46:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5750>")

[ERROR 12-19 06:46:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7130>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5cc0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e71f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6d70>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5750>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:46:37] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7130>").

[INFO 12-19 06:46:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:37] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5cc0>").

[INFO 12-19 06:46:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:37] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e71f0>").

[INFO 12-19 06:46:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:37] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6d70>").

[INFO 12-19 06:46:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:37] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5750>").

[INFO 12-19 06:46:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:46:37] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 12-19 06:46:37] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:46:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5270>")

[INFO 12-19 06:46:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4250>")

[INFO 12-19 06:46:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5d80>")

[INFO 12-19 06:46:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e62f0>")

[INFO 12-19 06:46:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5750>")

[ERROR 12-19 06:46:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5270>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4250>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5d80>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e62f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5750>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:46:47] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5270>").

[INFO 12-19 06:46:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:47] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4250>").

[INFO 12-19 06:46:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:47] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5d80>").

[INFO 12-19 06:46:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:47] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e62f0>").

[INFO 12-19 06:46:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:47] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5750>").

[INFO 12-19 06:46:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:46:47] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 12-19 06:46:47] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:46:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e65f0>")

[INFO 12-19 06:46:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6fb0>")

[INFO 12-19 06:46:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6dd0>")

[INFO 12-19 06:46:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5d80>")

[INFO 12-19 06:46:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5ed0>")

[ERROR 12-19 06:46:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e65f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6fb0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6dd0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5d80>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:46:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5ed0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:46:57] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e65f0>").

[INFO 12-19 06:46:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:57] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6fb0>").

[INFO 12-19 06:46:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:57] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6dd0>").

[INFO 12-19 06:46:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:57] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5d80>").

[INFO 12-19 06:46:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:46:57] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5ed0>").

[INFO 12-19 06:46:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:46:57] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 12-19 06:46:57] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:47:07] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7d00>")

[INFO 12-19 06:47:07] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5cc0>")

[INFO 12-19 06:47:07] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7d60>")

[INFO 12-19 06:47:07] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7e80>")

[INFO 12-19 06:47:07] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6ec0>")

[ERROR 12-19 06:47:07] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7d00>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:47:07] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5cc0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:47:07] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7d60>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:47:07] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7e80>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:47:07] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6ec0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:47:07] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7d00>").

[INFO 12-19 06:47:07] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:47:07] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5cc0>").

[INFO 12-19 06:47:07] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:47:07] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7d60>").

[INFO 12-19 06:47:07] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:47:07] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7e80>").

[INFO 12-19 06:47:07] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:47:07] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6ec0>").

[INFO 12-19 06:47:07] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:47:07] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 12-19 06:47:07] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:47:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e74c0>")

[INFO 12-19 06:47:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5cc0>")

[INFO 12-19 06:47:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5a20>")

[INFO 12-19 06:47:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5270>")

[INFO 12-19 06:47:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4fa0>")

[ERROR 12-19 06:47:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e74c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:47:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5cc0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:47:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5a20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:47:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5270>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:47:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4fa0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 06:47:17] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e74c0>").

[INFO 12-19 06:47:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:47:17] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5cc0>").

[INFO 12-19 06:47:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:47:17] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5a20>").

[INFO 12-19 06:47:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:47:17] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e5270>").

[INFO 12-19 06:47:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:47:17] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e4fa0>").

[INFO 12-19 06:47:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 12-19 06:47:17] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 12-19 06:47:17] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:47:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6b60>")

[INFO 12-19 06:47:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7e20>")

[INFO 12-19 06:47:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7fd0>")

[ERROR 12-19 06:47:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6b60>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:47:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7e20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:47:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7fd0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 06:47:28] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6b60>").

[INFO 12-19 06:47:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:47:28] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7e20>").

[INFO 12-19 06:47:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:47:28] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7fd0>").

[INFO 12-19 06:47:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:47:28] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:47:28] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:47:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7a90>")

[INFO 12-19 06:47:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7400>")

[ERROR 12-19 06:47:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7a90>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 06:47:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7400>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 06:47:38] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7a90>").

[INFO 12-19 06:47:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 06:47:38] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e7400>").

[INFO 12-19 06:47:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:47:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:47:38] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 06:47:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6ce0>")

[ERROR 12-19 06:47:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6ce0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 06:47:48] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ecc2e6ce0>").

[INFO 12-19 06:47:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:47:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:47:48] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:47:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:47:58] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:48:08] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:48:09] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:48:19] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:48:19] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:48:29] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:48:29] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:48:39] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:48:39] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:48:49] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:48:49] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:49:00] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:49:00] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:49:10] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:49:10] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:49:20] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:49:20] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:49:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:49:30] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:49:41] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:49:41] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:49:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:49:51] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:50:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:50:01] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:50:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:50:11] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:50:22] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:50:22] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:50:32] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:50:32] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:50:42] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:50:42] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:50:52] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:50:52] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:51:03] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:51:03] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:51:13] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:51:13] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:51:23] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:51:23] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:51:33] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:51:33] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:51:44] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:51:44] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:51:54] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:51:54] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:52:04] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:52:04] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:52:14] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:52:14] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:52:25] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:52:25] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:52:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:52:35] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:52:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:52:45] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:52:55] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:52:55] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:53:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:53:06] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:53:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:53:16] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:53:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:53:26] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:53:36] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:53:36] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:53:47] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:53:47] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:53:57] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:53:57] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:54:07] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:54:07] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:54:17] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:54:17] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:54:28] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:54:28] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:54:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:54:38] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:54:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:54:48] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:54:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:54:58] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:55:09] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:55:09] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:55:19] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:55:19] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:55:29] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:55:29] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:55:39] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:55:39] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:55:49] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:55:49] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:56:00] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:56:00] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:56:10] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:56:10] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:56:20] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:56:20] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:56:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:56:30] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:56:41] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:56:41] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:56:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:56:51] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:57:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:57:01] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:57:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:57:11] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:57:22] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:57:22] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:57:32] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:57:32] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:57:43] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:57:43] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:57:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:57:53] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:58:03] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:58:03] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:58:13] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:58:13] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:58:23] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:58:23] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:58:34] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:58:34] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:58:44] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:58:44] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:58:54] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:58:54] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:59:04] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:59:04] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:59:15] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:59:15] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:59:25] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:59:25] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:59:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:59:35] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:59:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:59:45] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 06:59:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 06:59:56] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:00:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:00:06] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:00:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:00:16] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:00:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:00:27] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:00:37] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:00:37] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:00:47] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:00:47] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:00:57] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:00:57] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:01:07] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[WARNING 12-19 07:01:07] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:01:08] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:01:08] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:01:18] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:01:18] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:01:28] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:01:28] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:01:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:01:38] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:01:49] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:01:49] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:01:59] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:01:59] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:02:09] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:02:09] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:02:19] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:02:19] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:02:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:02:30] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:02:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:02:40] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:02:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:02:50] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:03:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:03:01] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:03:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:03:11] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:03:21] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:03:21] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:03:31] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:03:31] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:03:42] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:03:42] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:03:52] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:03:52] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:04:02] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:04:02] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:04:12] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:04:12] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:04:23] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:04:23] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:04:33] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:04:33] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:04:43] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:04:43] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:04:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:04:53] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:05:04] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:05:04] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:05:14] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:05:14] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 5).

[INFO 12-19 07:05:24] Scheduler: Retrieved COMPLETED trials: [4].

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:05:24] ax.early_stopping.strategies.base: The number of completed trials (1) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[WARNING 12-19 07:05:24] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:05:24] ax.early_stopping.strategies.base: The number of completed trials (1) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:05:24] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 4).

[INFO 12-19 07:05:34] Scheduler: Retrieved COMPLETED trials: [3].

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:05:35] ax.early_stopping.strategies.base: The number of completed trials (2) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[WARNING 12-19 07:05:35] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:05:35] ax.early_stopping.strategies.base: The number of completed trials (2) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 12-19 07:05:35] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:05:45] Scheduler: Retrieved COMPLETED trials: [1, 2, 5].

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:05:45] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 12-19 07:05:45] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 12-19 07:05:46] Scheduler: Running trials [6]...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 12-19 07:05:49] Scheduler: Running trials [7]...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 12-19 07:05:51] Scheduler: Running trials [8]...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:05:52] Scheduler: Generated all trials that can be generated currently. Max parallelism currently reached.

[WARNING 12-19 07:05:52] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

[INFO 12-19 07:05:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16e00>")

[INFO 12-19 07:05:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f17190>")

[INFO 12-19 07:05:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16d10>")

[ERROR 12-19 07:05:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16e00>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:05:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f17190>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:05:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16d10>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 07:05:52] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16e00>").

[INFO 12-19 07:05:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:05:52] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f17190>").

[INFO 12-19 07:05:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:05:52] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16d10>").

[INFO 12-19 07:05:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:05:52] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 12-19 07:05:52] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:05:52] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:06:02] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f01db0>")

[INFO 12-19 07:06:02] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00970>")

[INFO 12-19 07:06:02] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f01300>")

[ERROR 12-19 07:06:02] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f01db0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:06:02] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00970>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:06:02] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f01300>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 07:06:02] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f01db0>").

[INFO 12-19 07:06:02] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:06:02] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00970>").

[INFO 12-19 07:06:02] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:06:02] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f01300>").

[INFO 12-19 07:06:02] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:06:02] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 12-19 07:06:02] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:06:02] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:06:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f17e50>")

[INFO 12-19 07:06:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00520>")

[INFO 12-19 07:06:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00520>")

[ERROR 12-19 07:06:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f17e50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:06:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00520>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:06:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00520>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 07:06:12] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f17e50>").

[INFO 12-19 07:06:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:06:12] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00520>").

[INFO 12-19 07:06:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:06:12] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00520>").

[INFO 12-19 07:06:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:06:12] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 12-19 07:06:12] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:06:12] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:06:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00970>")

[INFO 12-19 07:06:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00970>")

[INFO 12-19 07:06:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00970>")

[ERROR 12-19 07:06:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00970>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:06:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00970>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:06:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00970>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 07:06:22] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00970>").

[INFO 12-19 07:06:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:06:22] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00970>").

[INFO 12-19 07:06:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:06:22] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f00970>").

[INFO 12-19 07:06:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:06:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 12-19 07:06:23] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:06:23] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:06:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fa110>")

[INFO 12-19 07:06:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fb070>")

[INFO 12-19 07:06:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f95a0>")

[ERROR 12-19 07:06:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fa110>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:06:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fb070>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:06:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f95a0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 12-19 07:06:33] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fa110>").

[INFO 12-19 07:06:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:06:33] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fb070>").

[INFO 12-19 07:06:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:06:33] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f95a0>").

[INFO 12-19 07:06:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:06:33] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 12-19 07:06:33] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:06:33] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:06:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f84f0>")

[ERROR 12-19 07:06:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f84f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:06:43] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f84f0>").

[INFO 12-19 07:06:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:06:43] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 12-19 07:06:43] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:06:43] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:06:53] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 12-19 07:06:53] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:06:53] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:07:03] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 12-19 07:07:03] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:07:03] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:07:13] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 12-19 07:07:13] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:07:13] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:07:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 12-19 07:07:23] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:07:23] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:07:33] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 12-19 07:07:33] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:07:33] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:07:43] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 12-19 07:07:43] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:07:43] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:07:54] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 12-19 07:07:54] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:07:54] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:08:04] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 12-19 07:08:04] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:08:04] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:08:14] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 12-19 07:08:14] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:08:14] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:08:24] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 12-19 07:08:24] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:08:24] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:08:34] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 12-19 07:08:34] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:08:34] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:08:44] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 12-19 07:08:44] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:08:44] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:08:54] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 12-19 07:08:54] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 12-19 07:08:54] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 12-19 07:08:54] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:08:54] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 12-19 07:08:54] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 12-19 07:08:54] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.942868
2    0.938843
3    0.905534
4    0.923750
5    0.943565
6    0.926622
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:08:54] ax.early_stopping.strategies.percentile: Early stopping decision for 6: True. Reason: Trial objective value 0.9266221564391565 is worse than 70.0-th percentile (0.9408556648663111) across comparable trials.

[INFO 12-19 07:08:54] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:08:55] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.29994666666666664.

[INFO 12-19 07:08:55] ax.early_stopping.strategies.base: Trial 7's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 12-19 07:08:59] Scheduler: Running trials [9]...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:09:00] Scheduler: Generated all trials that can be generated currently. Max parallelism currently reached.

[WARNING 12-19 07:09:00] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

[INFO 12-19 07:09:00] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fa980>")

[ERROR 12-19 07:09:00] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fa980>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:09:00] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fa980>").

[INFO 12-19 07:09:00] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:09:00] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 12-19 07:09:00] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 12-19 07:09:00] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.3999466666666667.

[INFO 12-19 07:09:00] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.942868
2    0.938843
3    0.905534
4    0.923750
5    0.943565
6    0.926622
7    0.960570
8    0.927980
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:09:00] ax.early_stopping.strategies.percentile: Early stopping decision for 8: True. Reason: Trial objective value 0.9279800236518747 is worse than 70.0-th percentile (0.9424656169755118) across comparable trials.

[INFO 12-19 07:09:00] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:09:00] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:09:00] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:09:00] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 12-19 07:09:00] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.942868
2    0.938843
3    0.905534
4    0.923750
5    0.943565
6    0.926622
7    0.960570
8    0.927980
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:09:00] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9605696424474858 is better than 70.0-th percentile (0.9424656169755118) across comparable trials.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 12-19 07:09:03] Scheduler: Running trials [10]...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:09:04] Scheduler: Generated all trials that can be generated currently. Max parallelism currently reached.

[WARNING 12-19 07:09:04] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

[INFO 12-19 07:09:04] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f17d30>")

[INFO 12-19 07:09:04] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16d70>")

[ERROR 12-19 07:09:04] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f17d30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:09:04] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16d70>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:09:04] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f17d30>").

[INFO 12-19 07:09:04] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:09:04] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16d70>").

[INFO 12-19 07:09:04] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:09:04] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 12-19 07:09:04] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:09:04] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:09:04] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:09:04] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:09:04] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:09:04] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 12-19 07:09:04] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.942868
2    0.938843
3    0.905534
4    0.923750
5    0.943565
6    0.926622
7    0.960570
8    0.927980
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:09:04] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9605696424474858 is better than 70.0-th percentile (0.9424656169755118) across comparable trials.

[INFO 12-19 07:09:04] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:09:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f9ba0>")

[INFO 12-19 07:09:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f9ba0>")

[ERROR 12-19 07:09:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f9ba0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:09:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f9ba0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:09:14] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f9ba0>").

[INFO 12-19 07:09:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:09:14] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f9ba0>").

[INFO 12-19 07:09:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:09:14] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 12-19 07:09:15] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:09:15] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:09:15] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:09:15] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:09:15] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:09:15] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 12-19 07:09:15] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.942868
2    0.938843
3    0.905534
4    0.923750
5    0.943565
6    0.926622
7    0.960570
8    0.927980
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:09:15] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9605696424474858 is better than 70.0-th percentile (0.9424656169755118) across comparable trials.

[INFO 12-19 07:09:15] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:09:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecb820>")

[INFO 12-19 07:09:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecb820>")

[ERROR 12-19 07:09:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecb820>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:09:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecb820>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:09:25] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecb820>").

[INFO 12-19 07:09:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:09:25] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecb820>").

[INFO 12-19 07:09:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:09:25] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 12-19 07:09:25] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:09:25] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:09:25] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:09:25] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:09:25] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:09:25] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 12-19 07:09:25] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.942868
2    0.938843
3    0.905534
4    0.923750
5    0.943565
6    0.926622
7    0.960570
8    0.927980
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:09:25] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9605696424474858 is better than 70.0-th percentile (0.9424656169755118) across comparable trials.

[INFO 12-19 07:09:25] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:09:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ec93f0>")

[INFO 12-19 07:09:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ec93f0>")

[ERROR 12-19 07:09:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ec93f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:09:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ec93f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:09:35] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ec93f0>").

[INFO 12-19 07:09:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:09:35] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ec93f0>").

[INFO 12-19 07:09:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:09:35] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 12-19 07:09:35] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:09:35] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:09:35] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:09:35] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:09:35] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:09:35] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 12-19 07:09:35] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.942868
2    0.938843
3    0.905534
4    0.923750
5    0.943565
6    0.926622
7    0.960570
8    0.927980
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:09:35] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9605696424474858 is better than 70.0-th percentile (0.9424656169755118) across comparable trials.

[INFO 12-19 07:09:35] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:09:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9eca620>")

[INFO 12-19 07:09:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecb4f0>")

[ERROR 12-19 07:09:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9eca620>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:09:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecb4f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:09:45] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9eca620>").

[INFO 12-19 07:09:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:09:45] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecb4f0>").

[INFO 12-19 07:09:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:09:45] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 12-19 07:09:45] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:09:45] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:09:45] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:09:45] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:09:45] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:09:45] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.49994666666666665.

[INFO 12-19 07:09:45] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.946645
2    0.939574
3    0.911242
4    0.923266
5    0.946388
7    0.966444
Name: 0.49994666666666665, dtype: float64.

[INFO 12-19 07:09:45] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9664438083030783 is better than 70.0-th percentile (0.9465168402336042) across comparable trials.

[INFO 12-19 07:09:45] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:09:55] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 12-19 07:09:55] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:09:55] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:09:55] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:09:55] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 12-19 07:09:55] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:09:55] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:09:55] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 12-19 07:09:55] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:09:55] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:09:55] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.49994666666666665.

[INFO 12-19 07:09:55] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.946645
2    0.939574
3    0.911242
4    0.923266
5    0.946388
7    0.966444
Name: 0.49994666666666665, dtype: float64.

[INFO 12-19 07:09:55] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9664438083030783 is better than 70.0-th percentile (0.9465168402336042) across comparable trials.

[INFO 12-19 07:09:55] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:10:05] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 12-19 07:10:05] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:10:05] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:10:05] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:10:05] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 12-19 07:10:05] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:10:05] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:10:05] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 12-19 07:10:05] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:10:05] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:10:05] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.49994666666666665.

[INFO 12-19 07:10:05] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.946645
2    0.939574
3    0.911242
4    0.923266
5    0.946388
7    0.966444
Name: 0.49994666666666665, dtype: float64.

[INFO 12-19 07:10:05] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9664438083030783 is better than 70.0-th percentile (0.9465168402336042) across comparable trials.

[INFO 12-19 07:10:05] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:10:16] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 12-19 07:10:16] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:10:16] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:10:16] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:10:16] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 12-19 07:10:16] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:10:16] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:10:16] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 12-19 07:10:16] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:10:16] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:10:16] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.49994666666666665.

[INFO 12-19 07:10:16] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.946645
2    0.939574
3    0.911242
4    0.923266
5    0.946388
7    0.966444
Name: 0.49994666666666665, dtype: float64.

[INFO 12-19 07:10:16] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9664438083030783 is better than 70.0-th percentile (0.9465168402336042) across comparable trials.

[INFO 12-19 07:10:16] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:10:26] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 12-19 07:10:26] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:10:26] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:10:26] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:10:26] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 12-19 07:10:26] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:10:26] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:10:26] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 12-19 07:10:26] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:10:26] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:10:26] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.5999466666666666.

[INFO 12-19 07:10:26] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.948966
2    0.945210
3    0.914508
4    0.923687
5    0.950435
7    0.968633
Name: 0.5999466666666666, dtype: float64.

[INFO 12-19 07:10:26] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9686333222243974 is better than 70.0-th percentile (0.9497005386701411) across comparable trials.

[INFO 12-19 07:10:26] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:10:36] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 12-19 07:10:36] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:10:36] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:10:36] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:10:36] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 12-19 07:10:36] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:10:36] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:10:36] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 12-19 07:10:36] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:10:36] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:10:36] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.5999466666666666.

[INFO 12-19 07:10:36] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.948966
2    0.945210
3    0.914508
4    0.923687
5    0.950435
7    0.968633
Name: 0.5999466666666666, dtype: float64.

[INFO 12-19 07:10:36] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9686333222243974 is better than 70.0-th percentile (0.9497005386701411) across comparable trials.

[INFO 12-19 07:10:36] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:10:46] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 12-19 07:10:46] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:10:46] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 12-19 07:10:46] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:10:46] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:10:46] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 12-19 07:10:46] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:10:46] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:10:46] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.5999466666666666.

[INFO 12-19 07:10:46] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.948966
2    0.945210
3    0.914508
4    0.923687
5    0.950435
7    0.968633
Name: 0.5999466666666666, dtype: float64.

[INFO 12-19 07:10:46] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9686333222243974 is better than 70.0-th percentile (0.9497005386701411) across comparable trials.

[INFO 12-19 07:10:46] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:10:56] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 12-19 07:10:56] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:10:56] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 12-19 07:10:56] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:10:56] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:10:56] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 12-19 07:10:56] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:10:56] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:10:56] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.5999466666666666.

[INFO 12-19 07:10:56] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.948966
2    0.945210
3    0.914508
4    0.923687
5    0.950435
7    0.968633
Name: 0.5999466666666666, dtype: float64.

[INFO 12-19 07:10:56] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9686333222243974 is better than 70.0-th percentile (0.9497005386701411) across comparable trials.

[INFO 12-19 07:10:56] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:11:07] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 12-19 07:11:07] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:11:07] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 12-19 07:11:07] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:11:07] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:11:07] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 12-19 07:11:07] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:11:07] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:11:07] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.5999466666666666.

[INFO 12-19 07:11:07] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.948966
2    0.945210
3    0.914508
4    0.923687
5    0.950435
7    0.968633
Name: 0.5999466666666666, dtype: float64.

[INFO 12-19 07:11:07] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9686333222243974 is better than 70.0-th percentile (0.9497005386701411) across comparable trials.

[INFO 12-19 07:11:07] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:11:17] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 12-19 07:11:17] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:11:17] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 12-19 07:11:17] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:11:17] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:11:17] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 12-19 07:11:17] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:11:17] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:11:17] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.6999466666666667.

[INFO 12-19 07:11:17] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.952297
2    0.947459
3    0.917810
4    0.926432
5    0.951739
7    0.970992
Name: 0.6999466666666667, dtype: float64.

[INFO 12-19 07:11:17] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9709918629990628 is better than 70.0-th percentile (0.9520178094917208) across comparable trials.

[INFO 12-19 07:11:17] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:11:27] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 12-19 07:11:27] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:11:27] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 12-19 07:11:27] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:11:27] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:11:27] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 12-19 07:11:27] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:11:27] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:11:27] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.6999466666666667.

[INFO 12-19 07:11:27] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.952297
2    0.947459
3    0.917810
4    0.926432
5    0.951739
7    0.970992
Name: 0.6999466666666667, dtype: float64.

[INFO 12-19 07:11:27] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9709918629990628 is better than 70.0-th percentile (0.9520178094917208) across comparable trials.

[INFO 12-19 07:11:27] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:11:37] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 12-19 07:11:37] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:11:37] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 12-19 07:11:37] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:11:37] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:11:37] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 12-19 07:11:37] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:11:37] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:11:37] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.6999466666666667.

[INFO 12-19 07:11:37] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.952297
2    0.947459
3    0.917810
4    0.926432
5    0.951739
7    0.970992
Name: 0.6999466666666667, dtype: float64.

[INFO 12-19 07:11:37] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9709918629990628 is better than 70.0-th percentile (0.9520178094917208) across comparable trials.

[INFO 12-19 07:11:37] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:11:47] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 12-19 07:11:47] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:11:47] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 12-19 07:11:47] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:11:47] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:11:47] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 12-19 07:11:47] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:11:47] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:11:47] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.6999466666666667.

[INFO 12-19 07:11:47] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.952297
2    0.947459
3    0.917810
4    0.926432
5    0.951739
7    0.970992
Name: 0.6999466666666667, dtype: float64.

[INFO 12-19 07:11:47] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9709918629990628 is better than 70.0-th percentile (0.9520178094917208) across comparable trials.

[INFO 12-19 07:11:47] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:11:57] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 12-19 07:11:57] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:11:57] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 12-19 07:11:57] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:11:57] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:11:57] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 12-19 07:11:57] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:11:57] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:11:57] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.6999466666666667.

[INFO 12-19 07:11:57] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.952297
2    0.947459
3    0.917810
4    0.926432
5    0.951739
7    0.970992
Name: 0.6999466666666667, dtype: float64.

[INFO 12-19 07:11:57] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9709918629990628 is better than 70.0-th percentile (0.9520178094917208) across comparable trials.

[INFO 12-19 07:11:57] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:12:08] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 12-19 07:12:08] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:12:08] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 12-19 07:12:08] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:12:08] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:12:08] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 12-19 07:12:08] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:12:08] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:12:08] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.7999466666666667.

[INFO 12-19 07:12:08] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.954477
2    0.947598
3    0.920205
4    0.928725
5    0.953388
7    0.970996
Name: 0.7999466666666667, dtype: float64.

[INFO 12-19 07:12:08] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9709958631928962 is better than 70.0-th percentile (0.9539323401906152) across comparable trials.

[INFO 12-19 07:12:08] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:12:18] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 12-19 07:12:18] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 12-19 07:12:18] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.3999466666666667.

[INFO 12-19 07:12:18] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.942868
2     0.938843
3     0.905534
4     0.923750
5     0.943565
6     0.926622
7     0.960570
8     0.927980
9     0.926235
10    0.929029
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:12:18] ax.early_stopping.strategies.percentile: Early stopping decision for 9: True. Reason: Trial objective value 0.9262345186595258 is worse than 70.0-th percentile (0.9400506888117108) across comparable trials.

[INFO 12-19 07:12:18] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 12-19 07:12:18] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.3999466666666667.

[INFO 12-19 07:12:18] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.942868
2     0.938843
3     0.905534
4     0.923750
5     0.943565
6     0.926622
7     0.960570
8     0.927980
9     0.926235
10    0.929029
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:12:18] ax.early_stopping.strategies.percentile: Early stopping decision for 10: True. Reason: Trial objective value 0.9290288704369456 is worse than 70.0-th percentile (0.9400506888117108) across comparable trials.

[INFO 12-19 07:12:18] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:12:18] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.7999466666666667.

[INFO 12-19 07:12:18] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.954477
2    0.947598
3    0.920205
4    0.928725
5    0.953388
7    0.970996
Name: 0.7999466666666667, dtype: float64.

[INFO 12-19 07:12:18] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9709958631928962 is better than 70.0-th percentile (0.9539323401906152) across comparable trials.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 12-19 07:12:21] Scheduler: Running trials [11]...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 12-19 07:12:24] Scheduler: Running trials [12]...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:12:25] Scheduler: Generated all trials that can be generated currently. Max parallelism currently reached.

[WARNING 12-19 07:12:25] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

[INFO 12-19 07:12:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f2e290>")

[INFO 12-19 07:12:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f2f940>")

[ERROR 12-19 07:12:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f2e290>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:12:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f2f940>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:12:25] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f2e290>").

[INFO 12-19 07:12:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:12:25] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f2f940>").

[INFO 12-19 07:12:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:12:25] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 12-19 07:12:25] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 12-19 07:12:25] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:12:25] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 12-19 07:12:25] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:12:25] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:12:25] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.7999466666666667.

[INFO 12-19 07:12:25] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.954477
2    0.947598
3    0.920205
4    0.928725
5    0.953388
7    0.970996
Name: 0.7999466666666667, dtype: float64.

[INFO 12-19 07:12:25] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9709958631928962 is better than 70.0-th percentile (0.9539323401906152) across comparable trials.

[INFO 12-19 07:12:25] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:12:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16ce0>")

[INFO 12-19 07:12:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16ce0>")

[ERROR 12-19 07:12:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16ce0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:12:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16ce0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:12:35] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16ce0>").

[INFO 12-19 07:12:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:12:35] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16ce0>").

[INFO 12-19 07:12:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:12:35] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 12-19 07:12:35] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 12-19 07:12:35] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:12:35] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 12-19 07:12:35] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:12:35] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:12:35] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.7999466666666667.

[INFO 12-19 07:12:35] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.954477
2    0.947598
3    0.920205
4    0.928725
5    0.953388
7    0.970996
Name: 0.7999466666666667, dtype: float64.

[INFO 12-19 07:12:35] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9709958631928962 is better than 70.0-th percentile (0.9539323401906152) across comparable trials.

[INFO 12-19 07:12:35] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:12:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fa980>")

[INFO 12-19 07:12:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fa980>")

[ERROR 12-19 07:12:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fa980>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:12:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fa980>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:12:45] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fa980>").

[INFO 12-19 07:12:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:12:45] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80fa980>").

[INFO 12-19 07:12:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:12:45] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 12-19 07:12:45] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 12-19 07:12:45] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:12:45] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 12-19 07:12:45] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:12:45] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:12:45] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.8999466666666667.

[INFO 12-19 07:12:45] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.957104
2    0.945060
3    0.921479
4    0.929514
5    0.953418
7    0.972858
Name: 0.8999466666666667, dtype: float64.

[INFO 12-19 07:12:45] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9728584721445005 is better than 70.0-th percentile (0.9552609033219704) across comparable trials.

[INFO 12-19 07:12:45] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:12:55] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecae60>")

[INFO 12-19 07:12:55] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecae60>")

[ERROR 12-19 07:12:55] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecae60>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:12:55] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecae60>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:12:55] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecae60>").

[INFO 12-19 07:12:55] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:12:55] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecae60>").

[INFO 12-19 07:12:55] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:12:55] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 12-19 07:12:55] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 12-19 07:12:55] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:12:55] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 12-19 07:12:55] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:12:55] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:12:55] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.8999466666666667.

[INFO 12-19 07:12:55] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.957104
2    0.945060
3    0.921479
4    0.929514
5    0.953418
7    0.972858
Name: 0.8999466666666667, dtype: float64.

[INFO 12-19 07:12:55] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9728584721445005 is better than 70.0-th percentile (0.9552609033219704) across comparable trials.

[INFO 12-19 07:12:55] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:13:05] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ec9ae0>")

[INFO 12-19 07:13:05] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecb820>")

[ERROR 12-19 07:13:05] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ec9ae0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 12-19 07:13:05] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecb820>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:13:05] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ec9ae0>").

[INFO 12-19 07:13:05] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 12-19 07:13:05] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9ecb820>").

[INFO 12-19 07:13:05] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:13:05] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 12-19 07:13:05] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 12-19 07:13:05] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:13:05] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 12-19 07:13:05] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:13:05] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:13:05] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.8999466666666667.

[INFO 12-19 07:13:05] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.957104
2    0.945060
3    0.921479
4    0.929514
5    0.953418
7    0.972858
Name: 0.8999466666666667, dtype: float64.

[INFO 12-19 07:13:05] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9728584721445005 is better than 70.0-th percentile (0.9552609033219704) across comparable trials.

[INFO 12-19 07:13:05] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:13:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f9db0>")

[ERROR 12-19 07:13:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f9db0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:13:15] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f9db0>").

[INFO 12-19 07:13:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:13:15] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 12-19 07:13:15] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:13:15] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 12-19 07:13:15] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.09994666666666667.

[INFO 12-19 07:13:15] ax.early_stopping.strategies.base: Trial 11's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:13:15] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 12-19 07:13:16] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 12-19 07:13:16] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:13:16] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.8999466666666667.

[INFO 12-19 07:13:16] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.957104
2    0.945060
3    0.921479
4    0.929514
5    0.953418
7    0.972858
Name: 0.8999466666666667, dtype: float64.

[INFO 12-19 07:13:16] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9728584721445005 is better than 70.0-th percentile (0.9552609033219704) across comparable trials.

[INFO 12-19 07:13:16] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:13:26] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 12-19 07:13:26] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:13:26] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:13:26] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 12-19 07:13:26] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.09994666666666667.

[INFO 12-19 07:13:26] ax.early_stopping.strategies.base: Trial 11's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:13:26] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 12-19 07:13:26] ax.early_stopping.strategies.base: Last progression of Trial 12 is 0.09994666666666667.

[INFO 12-19 07:13:26] ax.early_stopping.strategies.base: Trial 12's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:13:26] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:13:26] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.8999466666666667.

[INFO 12-19 07:13:26] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.957104
2    0.945060
3    0.921479
4    0.929514
5    0.953418
7    0.972858
Name: 0.8999466666666667, dtype: float64.

[INFO 12-19 07:13:26] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9728584721445005 is better than 70.0-th percentile (0.9552609033219704) across comparable trials.

[INFO 12-19 07:13:26] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:13:36] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 12-19 07:13:36] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:13:36] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:13:36] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 12-19 07:13:36] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.09994666666666667.

[INFO 12-19 07:13:36] ax.early_stopping.strategies.base: Trial 11's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:13:36] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 12-19 07:13:36] ax.early_stopping.strategies.base: Last progression of Trial 12 is 0.09994666666666667.

[INFO 12-19 07:13:36] ax.early_stopping.strategies.base: Trial 12's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:13:36] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 12-19 07:13:36] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.8999466666666667.

[INFO 12-19 07:13:36] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.957104
2    0.945060
3    0.921479
4    0.929514
5    0.953418
7    0.972858
Name: 0.8999466666666667, dtype: float64.

[INFO 12-19 07:13:36] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9728584721445005 is better than 70.0-th percentile (0.9552609033219704) across comparable trials.

[INFO 12-19 07:13:36] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:13:46] Scheduler: Retrieved COMPLETED trials: [7].

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:13:46] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 12-19 07:13:46] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 12-19 07:13:52] Scheduler: Running trials [13]...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:13:53] Scheduler: Generated all trials that can be generated currently. Max parallelism currently reached.

[WARNING 12-19 07:13:53] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

[INFO 12-19 07:13:53] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f2ee90>")

[ERROR 12-19 07:13:53] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f2ee90>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:13:53] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f2ee90>").

[INFO 12-19 07:13:53] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:13:53] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 12-19 07:13:53] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:13:53] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:14:03] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f17130>")

[ERROR 12-19 07:14:03] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f17130>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:14:03] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f17130>").

[INFO 12-19 07:14:03] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:14:03] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 12-19 07:14:03] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:14:03] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:14:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f169e0>")

[ERROR 12-19 07:14:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f169e0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:14:13] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f169e0>").

[INFO 12-19 07:14:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:14:13] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 12-19 07:14:13] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:14:13] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:14:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9eca2f0>")

[ERROR 12-19 07:14:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9eca2f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:14:23] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9eca2f0>").

[INFO 12-19 07:14:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:14:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 12-19 07:14:23] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:14:23] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:14:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16bf0>")

[ERROR 12-19 07:14:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16bf0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:14:33] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f16bf0>").

[INFO 12-19 07:14:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:14:33] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 12-19 07:14:33] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:14:33] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

[INFO 12-19 07:14:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f166e0>")

[ERROR 12-19 07:14:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f166e0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:14:43] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f166e0>").

[INFO 12-19 07:14:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:14:43] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 12-19 07:14:43] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:14:43] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:14:54] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 12-19 07:14:54] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:14:54] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:15:04] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 12-19 07:15:04] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:15:04] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:15:14] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 12-19 07:15:14] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:15:14] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:15:24] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 12-19 07:15:24] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:15:24] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 3).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:15:34] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 12-19 07:15:34] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 12-19 07:15:34] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 12-19 07:15:34] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.942868
2     0.938843
3     0.905534
4     0.923750
5     0.943565
6     0.926622
7     0.960570
8     0.927980
9     0.926235
10    0.929029
11    0.921105
12    0.923529
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:15:34] ax.early_stopping.strategies.percentile: Early stopping decision for 11: True. Reason: Trial objective value 0.9211047488480365 is worse than 70.0-th percentile (0.9358989184419509) across comparable trials.

[INFO 12-19 07:15:34] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 12-19 07:15:34] ax.early_stopping.strategies.base: Last progression of Trial 12 is 0.3999466666666667.

[INFO 12-19 07:15:34] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.942868
2     0.938843
3     0.905534
4     0.923750
5     0.943565
6     0.926622
7     0.960570
8     0.927980
9     0.926235
10    0.929029
11    0.921105
12    0.923529
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:15:34] ax.early_stopping.strategies.percentile: Early stopping decision for 12: True. Reason: Trial objective value 0.9235294889933958 is worse than 70.0-th percentile (0.9358989184419509) across comparable trials.

[INFO 12-19 07:15:34] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:15:34] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.19994666666666666.

[INFO 12-19 07:15:34] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 12-19 07:15:38] Scheduler: Running trials [14]...

[WARNING 12-19 07:15:38] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

[INFO 12-19 07:15:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f9ae0>")

[ERROR 12-19 07:15:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f9ae0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:15:38] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec80f9ae0>").

[INFO 12-19 07:15:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:15:38] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 12-19 07:15:38] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:15:38] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

[INFO 12-19 07:15:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f2c340>")

[ERROR 12-19 07:15:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f2c340>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:15:48] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9f2c340>").

[INFO 12-19 07:15:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:15:48] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 12-19 07:15:48] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:15:48] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

[INFO 12-19 07:15:58] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9eca0e0>")

[ERROR 12-19 07:15:58] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9eca0e0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 12-19 07:15:58] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f4ec9eca0e0>").

[INFO 12-19 07:15:58] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:15:58] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 12-19 07:15:58] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:15:58] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:16:08] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 12-19 07:16:08] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 12-19 07:16:08] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:16:18] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 12-19 07:16:18] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 12-19 07:16:18] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:16:18] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 12-19 07:16:18] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.942868
2     0.938843
3     0.905534
4     0.923750
5     0.943565
6     0.926622
7     0.960570
8     0.927980
9     0.926235
10    0.929029
11    0.921105
12    0.923529
13    0.951056
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:16:18] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.951056406415742 is better than 70.0-th percentile (0.940453176839011) across comparable trials.

[INFO 12-19 07:16:18] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:16:18] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 12-19 07:16:18] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:16:18] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:16:29] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 12-19 07:16:29] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:16:29] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 12-19 07:16:29] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.942868
2     0.938843
3     0.905534
4     0.923750
5     0.943565
6     0.926622
7     0.960570
8     0.927980
9     0.926235
10    0.929029
11    0.921105
12    0.923529
13    0.951056
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:16:29] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.951056406415742 is better than 70.0-th percentile (0.940453176839011) across comparable trials.

[INFO 12-19 07:16:29] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:16:29] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 12-19 07:16:29] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:16:29] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:16:39] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 12-19 07:16:39] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:16:39] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 12-19 07:16:39] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.946645
2     0.939574
3     0.911242
4     0.923266
5     0.946388
7     0.966444
13    0.956863
Name: 0.49994666666666665, dtype: float64.

[INFO 12-19 07:16:39] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.956863062342432 is better than 70.0-th percentile (0.9486887843717545) across comparable trials.

[INFO 12-19 07:16:39] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:16:39] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 12-19 07:16:39] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:16:39] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:16:49] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 12-19 07:16:49] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:16:49] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 12-19 07:16:49] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.946645
2     0.939574
3     0.911242
4     0.923266
5     0.946388
7     0.966444
13    0.956863
Name: 0.49994666666666665, dtype: float64.

[INFO 12-19 07:16:49] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.956863062342432 is better than 70.0-th percentile (0.9486887843717545) across comparable trials.

[INFO 12-19 07:16:49] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:16:49] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.29994666666666664.

[INFO 12-19 07:16:49] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:16:49] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:16:59] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 12-19 07:16:59] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:16:59] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 12-19 07:16:59] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.946645
2     0.939574
3     0.911242
4     0.923266
5     0.946388
7     0.966444
13    0.956863
Name: 0.49994666666666665, dtype: float64.

[INFO 12-19 07:16:59] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.956863062342432 is better than 70.0-th percentile (0.9486887843717545) across comparable trials.

[INFO 12-19 07:16:59] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:16:59] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.29994666666666664.

[INFO 12-19 07:16:59] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 12-19 07:16:59] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:17:09] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 12-19 07:17:09] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:17:09] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.5999466666666666.

[INFO 12-19 07:17:09] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.948966
2     0.945210
3     0.914508
4     0.923687
5     0.950435
7     0.968633
13    0.960746
Name: 0.5999466666666666, dtype: float64.

[INFO 12-19 07:17:09] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9607460946850128 is better than 70.0-th percentile (0.95249737548488) across comparable trials.

[INFO 12-19 07:17:09] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:17:09] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.3999466666666667.

[INFO 12-19 07:17:09] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.942868
2     0.938843
3     0.905534
4     0.923750
5     0.943565
6     0.926622
7     0.960570
8     0.927980
9     0.926235
10    0.929029
11    0.921105
12    0.923529
13    0.951056
14    0.958636
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:17:09] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.9586357204197662 is better than 70.0-th percentile (0.9429377870606671) across comparable trials.

[INFO 12-19 07:17:09] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:17:19] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 12-19 07:17:19] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:17:19] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.5999466666666666.

[INFO 12-19 07:17:19] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.948966
2     0.945210
3     0.914508
4     0.923687
5     0.950435
7     0.968633
13    0.960746
Name: 0.5999466666666666, dtype: float64.

[INFO 12-19 07:17:19] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9607460946850128 is better than 70.0-th percentile (0.95249737548488) across comparable trials.

[INFO 12-19 07:17:19] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:17:19] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.3999466666666667.

[INFO 12-19 07:17:19] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.942868
2     0.938843
3     0.905534
4     0.923750
5     0.943565
6     0.926622
7     0.960570
8     0.927980
9     0.926235
10    0.929029
11    0.921105
12    0.923529
13    0.951056
14    0.958636
Name: 0.3999466666666667, dtype: float64.

[INFO 12-19 07:17:19] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.9586357204197662 is better than 70.0-th percentile (0.9429377870606671) across comparable trials.

[INFO 12-19 07:17:19] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:17:29] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 12-19 07:17:29] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:17:29] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.6999466666666667.

[INFO 12-19 07:17:29] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.952297
2     0.947459
3     0.917810
4     0.926432
5     0.951739
7     0.970992
13    0.963178
Name: 0.6999466666666667, dtype: float64.

[INFO 12-19 07:17:29] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9631780952810118 is better than 70.0-th percentile (0.9544728526835615) across comparable trials.

[INFO 12-19 07:17:29] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:17:29] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.49994666666666665.

[INFO 12-19 07:17:29] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.946645
2     0.939574
3     0.911242
4     0.923266
5     0.946388
7     0.966444
13    0.956863
14    0.955558
Name: 0.49994666666666665, dtype: float64.

[INFO 12-19 07:17:29] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.9555576208375474 is better than 70.0-th percentile (0.9546663802417011) across comparable trials.

[INFO 12-19 07:17:29] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:17:40] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 12-19 07:17:40] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:17:40] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.6999466666666667.

[INFO 12-19 07:17:40] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.952297
2     0.947459
3     0.917810
4     0.926432
5     0.951739
7     0.970992
13    0.963178
Name: 0.6999466666666667, dtype: float64.

[INFO 12-19 07:17:40] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9631780952810118 is better than 70.0-th percentile (0.9544728526835615) across comparable trials.

[INFO 12-19 07:17:40] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:17:40] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.49994666666666665.

[INFO 12-19 07:17:40] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.946645
2     0.939574
3     0.911242
4     0.923266
5     0.946388
7     0.966444
13    0.956863
14    0.955558
Name: 0.49994666666666665, dtype: float64.

[INFO 12-19 07:17:40] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.9555576208375474 is better than 70.0-th percentile (0.9546663802417011) across comparable trials.

[INFO 12-19 07:17:40] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:17:50] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 12-19 07:17:50] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:17:50] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.7999466666666667.

[INFO 12-19 07:17:50] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.954477
2     0.947598
3     0.920205
4     0.928725
5     0.953388
7     0.970996
13    0.964596
Name: 0.7999466666666667, dtype: float64.

[INFO 12-19 07:17:50] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9645955542042808 is better than 70.0-th percentile (0.9565006006698733) across comparable trials.

[INFO 12-19 07:17:50] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:17:50] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.5999466666666666.

[INFO 12-19 07:17:50] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.948966
2     0.945210
3     0.914508
4     0.923687
5     0.950435
7     0.968633
13    0.960746
14    0.964993
Name: 0.5999466666666666, dtype: float64.

[INFO 12-19 07:17:50] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.9649932416091656 is better than 70.0-th percentile (0.9597150047849962) across comparable trials.

[INFO 12-19 07:17:50] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:18:00] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 12-19 07:18:00] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:18:00] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.7999466666666667.

[INFO 12-19 07:18:00] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.954477
2     0.947598
3     0.920205
4     0.928725
5     0.953388
7     0.970996
13    0.964596
Name: 0.7999466666666667, dtype: float64.

[INFO 12-19 07:18:00] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9645955542042808 is better than 70.0-th percentile (0.9565006006698733) across comparable trials.

[INFO 12-19 07:18:00] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:18:00] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.5999466666666666.

[INFO 12-19 07:18:00] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.948966
2     0.945210
3     0.914508
4     0.923687
5     0.950435
7     0.968633
13    0.960746
14    0.964993
Name: 0.5999466666666666, dtype: float64.

[INFO 12-19 07:18:00] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.9649932416091656 is better than 70.0-th percentile (0.9597150047849962) across comparable trials.

[INFO 12-19 07:18:00] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:18:10] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 12-19 07:18:10] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:18:10] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.8999466666666667.

[INFO 12-19 07:18:10] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.957104
2     0.945060
3     0.921479
4     0.929514
5     0.953418
7     0.972858
13    0.966768
Name: 0.8999466666666667, dtype: float64.

[INFO 12-19 07:18:10] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9667681062933865 is better than 70.0-th percentile (0.9590366403011998) across comparable trials.

[INFO 12-19 07:18:10] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:18:10] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.6999466666666667.

[INFO 12-19 07:18:10] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.952297
2     0.947459
3     0.917810
4     0.926432
5     0.951739
7     0.970992
13    0.963178
14    0.961004
Name: 0.6999466666666667, dtype: float64.

[INFO 12-19 07:18:10] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.9610035152700142 is better than 70.0-th percentile (0.9601328179464327) across comparable trials.

[INFO 12-19 07:18:10] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:18:20] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 12-19 07:18:20] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 12-19 07:18:20] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.8999466666666667.

[INFO 12-19 07:18:20] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.957104
2     0.945060
3     0.921479
4     0.929514
5     0.953418
7     0.972858
13    0.966768
Name: 0.8999466666666667, dtype: float64.

[INFO 12-19 07:18:20] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9667681062933865 is better than 70.0-th percentile (0.9590366403011998) across comparable trials.

[INFO 12-19 07:18:20] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:18:20] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.6999466666666667.

[INFO 12-19 07:18:20] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.952297
2     0.947459
3     0.917810
4     0.926432
5     0.951739
7     0.970992
13    0.963178
14    0.961004
Name: 0.6999466666666667, dtype: float64.

[INFO 12-19 07:18:20] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.9610035152700142 is better than 70.0-th percentile (0.9601328179464327) across comparable trials.

[INFO 12-19 07:18:20] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 2).

[INFO 12-19 07:18:30] Scheduler: Retrieved COMPLETED trials: [13].

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:18:30] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 12-19 07:18:30] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:18:30] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.7999466666666667.

[INFO 12-19 07:18:30] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.954477
2     0.947598
3     0.920205
4     0.928725
5     0.953388
7     0.970996
13    0.964596
14    0.963560
Name: 0.7999466666666667, dtype: float64.

[INFO 12-19 07:18:30] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.9635604223291967 is better than 70.0-th percentile (0.9626520663249042) across comparable trials.

[INFO 12-19 07:18:30] Scheduler: Done submitting trials, waiting for remaining 1 running trials...

[WARNING 12-19 07:18:30] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:18:30] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 12-19 07:18:30] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:18:30] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.7999466666666667.

[INFO 12-19 07:18:30] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.954477
2     0.947598
3     0.920205
4     0.928725
5     0.953388
7     0.970996
13    0.964596
14    0.963560
Name: 0.7999466666666667, dtype: float64.

[INFO 12-19 07:18:30] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.9635604223291967 is better than 70.0-th percentile (0.9626520663249042) across comparable trials.

[INFO 12-19 07:18:30] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 1).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:18:40] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 12-19 07:18:40] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:18:40] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.7999466666666667.

[INFO 12-19 07:18:40] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.954477
2     0.947598
3     0.920205
4     0.928725
5     0.953388
7     0.970996
13    0.964596
14    0.963560
Name: 0.7999466666666667, dtype: float64.

[INFO 12-19 07:18:40] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.9635604223291967 is better than 70.0-th percentile (0.9626520663249042) across comparable trials.

[INFO 12-19 07:18:40] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 1).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:18:50] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 12-19 07:18:50] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:18:51] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.8999466666666667.

[INFO 12-19 07:18:51] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.957104
2     0.945060
3     0.921479
4     0.929514
5     0.953418
7     0.972858
13    0.966768
14    0.965691
Name: 0.8999466666666667, dtype: float64.

[INFO 12-19 07:18:51] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.9656911793324748 is better than 70.0-th percentile (0.9648324387795426) across comparable trials.

[INFO 12-19 07:18:51] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 1).

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:19:01] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.9999466666666667.

[INFO 12-19 07:19:01] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 12-19 07:19:01] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.9999466666666667.

[INFO 12-19 07:19:01] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.958695
2     0.947034
3     0.922104
4     0.930697
5     0.951763
7     0.972947
13    0.967696
14    0.967346
Name: 0.9999466666666667, dtype: float64.

[INFO 12-19 07:19:01] ax.early_stopping.strategies.percentile: Early stopping decision for 14: False. Reason: Trial objective value 0.967345578219388 is better than 70.0-th percentile (0.9664805561949781) across comparable trials.

[INFO 12-19 07:19:01] Scheduler: Waiting for completed trials (for 10 sec, currently running trials: 1).

[INFO 12-19 07:19:11] Scheduler: Retrieved COMPLETED trials: [14].

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 12-19 07:19:11] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 12-19 07:19:11] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[WARNING 12-19 07:19:11] Scheduler: Both `init_seconds_between_polls` and `early_stopping_strategy supplied. `init_seconds_between_polls=1` will be overrridden by `early_stopping_strategy.seconds_between_polls=10` and polling will take place at a constant rate.

CPU times: user 49.9 s, sys: 1.4 s, total: 51.3 s
Wall time: 33min 50s

OptimizationResult()

## Results

First, we examine the data stored on the experiment. This shows that each trial is associated with an entire learning curve, represented by the column "steps".

In [15]:
experiment.lookup_data().map_df.head(n=10)

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

  arm_name metric_name      mean  sem  trial_index     step
0      1_0     val_acc  0.911154  NaN            1   1874.0
1      1_0     val_acc  0.924925  NaN            1   3749.0
2      1_0     val_acc  0.935295  NaN            1   5624.0
3      1_0     val_acc  0.942868  NaN            1   7499.0
4      1_0     val_acc  0.946645  NaN            1   9374.0
5      1_0     val_acc  0.948966  NaN            1  11249.0
6      1_0     val_acc  0.952297  NaN            1  13124.0
7      1_0     val_acc  0.954477  NaN            1  14999.0
8      1_0     val_acc  0.957104  NaN            1  16874.0
9      1_0     val_acc  0.958695  NaN            1  18749.0

Below is a summary of the experiment, showing that a portion of trials have been early stopped.

In [16]:
exp_to_df(experiment)

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

,trial_index,arm_name,trial_status,generation_method,val_acc,hidden_size_1,hidden_size_2,learning_rate,dropout
0,0,0_0,FAILED,Sobol,NaN,28,19,0.001110,0.025715
1,1,1_0,COMPLETED,Sobol,0.959332,81,74,0.000493,0.487135
2,2,2_0,COMPLETED,Sobol,0.947823,62,27,0.005452,0.136206
3,3,3_0,COMPLETED,Sobol,0.922353,22,105,0.000106,0.347653
4,4,4_0,COMPLETED,Sobol,0.931170,16,39,0.000811,0.252094
5,5,5_0,COMPLETED,Sobol,0.951101,45,83,0.002092,0.229135
6,6,6_0,EARLY_STOPPED,BoTorch,0.926622,82,128,0.002664,0.500000
7,7,7_0,COMPLETED,BoTorch,0.972982,95,122,0.000285,0.213368
8,8,8_0,EARLY_STOPPED,BoTorch,0.927980,80,16,0.000321,0.500000
9,9,9_0,EARLY_STOPPED,BoTorch,0.926235,79,128,0.002810,0.500000
10,10,10_0,EARLY_STOPPED,BoTorch,0.929029,77,16,0.000385,0.500000
11,11,11_0,EARLY_STOPPED,BoTorch,0.921105,77,128,0.002943,0.500000
12,12,12_0,EARLY_STOPPED,BoTorch,0.923529,80,16,0.000328,0.500000
13,13,13_0,COMPLETED,BoTorch,0.968067,128,128,0.000117,0.019377
14,14,14_0,COMPLETED,BoTorch,0.968007,121,128,0.001843,0.153448

We can give a very rough estimate of the amount of computational savings due to early stopping, by looking at the total number of steps used when early stopping is used versus the number of steps used if we ran all trials to completion. Note to do a true comparison, one should run full HPO loops with and without early stopping (as early stopping will influence the model and future points selected by the generation strategy).

In [17]:
map_df = experiment.lookup_data().map_df
trial_to_max_steps = map_df.groupby("trial_index")["step"].max()
completed_trial_steps = trial_to_max_steps.iloc[0]
savings = 1.0 - trial_to_max_steps.sum() / (
    completed_trial_steps * len(trial_to_max_steps)
)
# TODO format nicer
print(f"A rough estimate of the computational savings is {100 * savings}%.")

A rough estimate of the computational savings is 25.716571428571434%.

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

## Visualizations

Finally, we show a visualization of learning curves versus actual elapsed wall time. This helps to illustrate that stopped trials make room for additional trials to be run.

In [18]:
# helper function for getting trial start times
def time_started(row):
    trial_index = row["trial_index"]
    return experiment.trials[trial_index].time_run_started


# helper function for getting trial completion times
def time_completed(row):
    trial_index = row["trial_index"]
    return experiment.trials[trial_index].time_completed


# helper function for getting relevant data from experiment
# with early stopping into useful dfs
def early_stopping_exp_to_df(experiment):
    trials_df = exp_to_df(experiment)
    curve_df = experiment.lookup_data().map_df
    training_row_df = (
        curve_df.groupby("trial_index").max().reset_index()[["trial_index", "steps"]]
    )
    trials_df = trials_df.merge(training_row_df, on="trial_index")
    trials_df["time_started"] = trials_df.apply(func=time_started, axis=1)
    trials_df["time_completed"] = trials_df.apply(func=time_completed, axis=1)
    start_time = trials_df["time_started"].min()
    trials_df["time_started_rel"] = (
        trials_df["time_started"] - start_time
    ).dt.total_seconds()
    trials_df["time_completed_rel"] = (
        trials_df["time_completed"] - start_time
    ).dt.total_seconds()
    return trials_df, curve_df


def plot_curves_by_wall_time(trials_df, curve_df):
    trials = set(curve_df["trial_index"])
    fig, ax = plt.subplots(1, 1, figsize=(10, 6))
    ax.set(xlabel="seconds since start", ylabel="validation accuracy")
    for trial_index in trials:
        this_trial_df = curve_df[curve_df["trial_index"] == trial_index]
        start_time_rel = trials_df["time_started_rel"].iloc[trial_index]
        completed_time_rel = trials_df["time_completed_rel"].iloc[trial_index]
        total_steps = trials_df.loc[trial_index, "steps"]
        smoothed_curve = this_trial_df["mean"].rolling(window=3).mean()
        x = (
            start_time_rel
            + (completed_time_rel - start_time_rel)
            / total_steps
            * this_trial_df["steps"]
        )
        ax.plot(
            x,
            smoothed_curve,
            label=f"trial #{trial_index}" if trial_index % 2 == 1 else None,
        )
    ax.legend()

In [19]:
# wrap in try/except in case of flaky I/O issues
try:
    trials_df, curve_df = early_stopping_exp_to_df(experiment)
    plot_curves_by_wall_time(trials_df, curve_df)
except Exception as e:
    print(f"Encountered exception while plotting results: {e}")

Encountered exception while plotting results: "['steps'] not in index"

/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.RMcZqKq0CU/Ax-main/ax/core/map_data.py:197: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(