## Trial-level early stopping in Ax

This tutorial illustrates how to add a trial-level early stopping strategy to an Ax hyper-parameter optimization (HPO) loop. The goal of trial-level early stopping is to monitor the results of expensive evaluations and terminate those that are unlikely to produce promising results, freeing up resources to explore more configurations.

Most of this tutorial is adapted from the [PyTorch Ax Multiobjective NAS Tutorial](https://pytorch.org/tutorials/intermediate/ax_multiobjective_nas_tutorial.html). The training job is different from the original in that we do not optimize `batch_size` or `epochs`. This was done for illustrative purposes, as each validation curve now has the same number of points. The companion training file `mnist_train_nas.py` has also been altered to log to Tensorboard during training.

NOTE: Although the original NAS tutorial is for a multi-objective problem, this tutorial focuses on a single objective (validation accuracy) problem. Early stopping currently does not support \"true\" multi-objective stopping, although one can use [logical compositions of early stopping strategies](https://github.com/facebook/Ax/blob/main/ax/early_stopping/strategies/logical.py) to target multiple objectives separately. Early stopping for the multi-objective case is currently a work in progress.

In [1]:
import os
import tempfile

from pathlib import Path

import torchx

from ax.core import Experiment, Objective, ParameterType, RangeParameter, SearchSpace
from ax.core.optimization_config import OptimizationConfig

from ax.early_stopping.strategies import PercentileEarlyStoppingStrategy
from ax.metrics.tensorboard import TensorboardMetric

from ax.modelbridge.dispatch_utils import choose_generation_strategy

from ax.runners.torchx import TorchXRunner

from ax.service.scheduler import Scheduler, SchedulerOptions
from ax.service.utils.report_utils import exp_to_df

from tensorboard.backend.event_processing import plugin_event_multiplexer as event_multiplexer

from torchx import specs
from torchx.components import utils

from matplotlib import pyplot as plt


%matplotlib inline

In [2]:
SMOKE_TEST = os.environ.get("SMOKE_TEST")

## Defining the TorchX App

Our goal is to optimize the PyTorch Lightning training job defined in
[mnist_train_nas.py](https://github.com/pytorch/tutorials/tree/master/intermediate_source/mnist_train_nas.py)_.
To do this using TorchX, we write a helper function that takes in
the values of the architcture and hyperparameters of the training
job and creates a [TorchX AppDef](https://pytorch.org/torchx/latest/basics.html)_
with the appropriate settings.

In [3]:
if SMOKE_TEST:
    epochs = 3
else:
    epochs = 10

In [4]:
def trainer(
    log_path: str,
    hidden_size_1: int,
    hidden_size_2: int,
    learning_rate: float,
    dropout: float,
    trial_idx: int = -1,
) -> specs.AppDef:

    # define the log path so we can pass it to the TorchX AppDef
    if trial_idx >= 0:
        log_path = Path(log_path).joinpath(str(trial_idx)).absolute().as_posix()

    batch_size = 32

    return utils.python(
        # command line args to the training script
        "--log_path",
        log_path,
        "--hidden_size_1",
        str(hidden_size_1),
        "--hidden_size_2",
        str(hidden_size_2),
        "--learning_rate",
        str(learning_rate),
        "--epochs",
        str(epochs),
        "--dropout",
        str(dropout),
        "--batch_size",
        str(batch_size),
        # other config options
        name="trainer",
        script="tutorials/early_stopping/mnist_train_nas.py",
        image=torchx.version.TORCHX_IMAGE,
    )

## Setting up the Runner

Ax’s [Runner](https://ax.dev/api/core.html#ax.core.runner.Runner)
abstraction allows writing interfaces to various backends.
Ax already comes with Runner for TorchX, so we just need to
configure it. For the purpose of this tutorial, we run jobs locally
in a fully asynchronous fashion. In order to launch them on a cluster, you can instead specify a
different TorchX scheduler and adjust the configuration appropriately.
For example, if you have a Kubernetes cluster, you just need to change the
scheduler from ``local_cwd`` to ``kubernetes``.

The training job launched by this runner will log partial results to Tensorboard, which will then be monitored by the early stopping strategy. We will show how this is done using an Ax 
[TensorboardMetric](https://ax.dev/api/metrics.html#module-ax.metrics.tensorboard) below.

In [5]:
# Make a temporary dir to log our results into
log_dir = tempfile.mkdtemp()

ax_runner = TorchXRunner(
    tracker_base="/tmp/",
    component=trainer,
    # NOTE: To launch this job on a cluster instead of locally you can
    # specify a different scheduler and adjust args appropriately.
    scheduler="local_cwd",
    component_const_params={"log_path": log_dir},
    cfg={},
)

## Setting up the SearchSpace

First, we define our search space. Ax supports both range parameters
of type integer and float as well as choice parameters which can have
non-numerical types such as strings.
We will tune the hidden sizes, learning rate, and dropout parameters.

In [6]:
parameters = [
    # NOTE: In a real-world setting, hidden_size_1 and hidden_size_2
    # should probably be powers of 2, but in our simple example this
    # would mean that num_params can't take on that many values, which
    # in turn makes the Pareto frontier look pretty weird.
    RangeParameter(
        name="hidden_size_1",
        lower=16,
        upper=128,
        parameter_type=ParameterType.INT,
        log_scale=True,
    ),
    RangeParameter(
        name="hidden_size_2",
        lower=16,
        upper=128,
        parameter_type=ParameterType.INT,
        log_scale=True,
    ),
    RangeParameter(
        name="learning_rate",
        lower=1e-4,
        upper=1e-2,
        parameter_type=ParameterType.FLOAT,
        log_scale=True,
    ),
    RangeParameter(
        name="dropout",
        lower=0.0,
        upper=0.5,
        parameter_type=ParameterType.FLOAT,
    ),
]

search_space = SearchSpace(
    parameters=parameters,
    # NOTE: In practice, it may make sense to add a constraint
    # hidden_size_2 <= hidden_size_1
    parameter_constraints=[],
)

## Setting up Metrics

Ax has the concept of a Metric that defines properties of outcomes and how observations are obtained for these outcomes. This allows e.g. encodig how data is fetched from some distributed execution backend and post-processed before being passed as input to Ax.

We will optimize the validation accuracy, which is a `TensorboardMetric` that points to the logging directory assigned above. Note that we have set `is_available_while_running`, allowing for the metric to be queried as the trial progresses. This is critical for the early stopping strategy to monitor partial results.

In [7]:
class MyTensorboardMetric(TensorboardMetric):

    # NOTE: We need to tell the new Tensorboard metric how to get the id /
    # file handle for the tensorboard logs from a trial. In this case
    # our convention is to just save a separate file per trial in
    # the pre-specified log dir.
    def _get_event_multiplexer_for_trial(self, trial):
        mul = event_multiplexer.EventMultiplexer(max_reload_threads=20)
        mul.AddRunsFromDirectory(Path(log_dir).joinpath(str(trial.index)).as_posix(), None)
        mul.Reload()

        return mul

    # This indicates whether the metric is queryable while the trial is
    # still running. This is required for early stopping to monitor the
    # progress of the running trial.ArithmeticError
    @classmethod
    def is_available_while_running(cls):
        return True

In [8]:
val_acc = MyTensorboardMetric(
    name="val_acc",
    tag="val_acc",
    lower_is_better=False,
)

## Setting up the OptimizationConfig

The `OptimizationConfig` specifies the objective for Ax to optimize.

In [9]:
opt_config = OptimizationConfig(
    objective=Objective(
        metric=val_acc,
        minimize=False,
    )
)

## Defining an Early Stopping Strategy

A `PercentileEarlyStoppingStrategy` is a simple method that stops a trial if its performance falls below a certain percentile of other trials at the same step (e.g., when `percentile_threshold` is 50, at a given point in time, if a trial ranks in the bottom 50% of trials, it is stopped). 
- We make use of `normalize_progressions` which normalizes the progression column (e.g. timestamp, epochs, training data used) to be in [0, 1]. This is useful because one doesn't need to know the maximum progression values of the curve (which might be, e.g., the total number of data points in the training dataset).
- The `min_progression` parameter specifies that trials should only be considered for stopping if the latest progression value is greater than this threshold.
- The `min_curves` parameter specifies the minimum number of completed curves (i.e., fully completed training jobs) before early stopping will be considered. This should be larger than zero if `normalize_progression` is used. In general, we want a few completed curves to have a baseline for comparison.

Note that `PercentileEarlyStoppingStrategy` does not make use of learning curve modeling or prediction. More sophisticated model-based methods will be available in future versions of Ax.

In [10]:
percentile_early_stopping_strategy = PercentileEarlyStoppingStrategy(
    # stop if in bottom 70% of runs at the same progression
    percentile_threshold=70,
    # the trial must have passed `min_progression` steps before early stopping is initiated
    # note that we are using `normalize_progressions`, so this is on a scale of [0, 1]
    min_progression=0.3,
    # there must be `min_curves` completed trials and `min_curves` trials reporting data in
    # order for early stopping to be applicable
    min_curves=5,
    # specify, e.g., [0, 1] if the first two trials should never be stopped
    trial_indices_to_ignore=None,
    normalize_progressions=True,
)

## Creating the Ax Experiment

In Ax, the Experiment object is the object that stores all the information about the problem setup.

In [11]:
experiment = Experiment(
    name="torchx_mnist",
    search_space=search_space,
    optimization_config=opt_config,
    runner=ax_runner,
)

## Choosing the GenerationStrategy

A [GenerationStrategy](https://ax.dev/api/modelbridge.html#ax.modelbridge.generation_strategy.GenerationStrategy)
is the abstract representation of how we would like to perform the
optimization. While this can be customized (if you’d like to do so, see
[this tutorial](https://ax.dev/tutorials/generation_strategy.html)),
in most cases Ax can automatically determine an appropriate strategy
based on the search space, optimization config, and the total number
of trials we want to run.

Typically, Ax chooses to evaluate a number of random configurations
before starting a model-based Bayesian Optimization strategy.

We remark that in Ax, generation strategies and early stopping strategies are separate, a design decision motivated by ease-of-use. However, we should acknowledge that jointly considering generation and stopping using a single strategy would likely be the "proper" formulation.

In [12]:
if SMOKE_TEST:
    total_trials = 6
else:
    total_trials = 15  # total evaluation budget

gs = choose_generation_strategy(
    search_space=experiment.search_space,
    optimization_config=experiment.optimization_config,
    num_trials=total_trials,
)

[INFO 01-21 06:45:06] ax.modelbridge.dispatch_utils: Using Models.BOTORCH_MODULAR since there is at least one ordered parameter and there are no unordered categorical parameters.

[INFO 01-21 06:45:06] ax.modelbridge.dispatch_utils: Calculating the number of remaining initialization trials based on num_initialization_trials=None max_initialization_trials=None num_tunable_parameters=4 num_trials=15 use_batch_trials=False

[INFO 01-21 06:45:06] ax.modelbridge.dispatch_utils: calculated num_initialization_trials=5

[INFO 01-21 06:45:06] ax.modelbridge.dispatch_utils: num_completed_initialization_trials=0 num_remaining_initialization_trials=5

[INFO 01-21 06:45:06] ax.modelbridge.dispatch_utils: `verbose`, `disable_progbar`, and `jit_compile` are not yet supported when using `choose_generation_strategy` with ModularBoTorchModel, dropping these arguments.

[INFO 01-21 06:45:06] ax.modelbridge.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BoTorch', steps=[Sobol for 5 trials, BoTorch for subsequent trials]). Iterations after 5 will take longer to generate due to model-fitting.

## Configuring the Scheduler

The `Scheduler` acts as the loop control for the optimization.
It communicates with the backend to launch trials, check their status, retrieve (partial) results, and importantly for this tutorial, calls the early stopping strategy. If the early stopping strategy suggests a trial to be the stopped, the `Scheduler` communicates with the backend to terminate the trial.

The ``Scheduler`` requires the ``Experiment`` and the ``GenerationStrategy``.
A set of options can be passed in via ``SchedulerOptions``. Here, we
configure the number of total evaluations as well as ``max_pending_trials``,
the maximum number of trials that should run concurrently. In our
local setting, this is the number of training jobs running as individual
processes, while in a remote execution setting, this would be the number
of machines you want to use in parallel.

In [13]:
scheduler = Scheduler(
    experiment=experiment,
    generation_strategy=gs,
    options=SchedulerOptions(
        total_trials=total_trials,
        max_pending_trials=5,
        early_stopping_strategy=percentile_early_stopping_strategy,
    ),
)

[INFO 01-21 06:45:06] Scheduler: `Scheduler` requires experiment to have immutable search space and optimization config. Setting property immutable_search_space_and_opt_config to `True` on experiment.

In [14]:
%%time
scheduler.run_all_trials()

[INFO 01-21 06:45:06] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 01-21 06:45:06] Scheduler: Running trials [0]...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 01-21 06:45:07] Scheduler: Running trials [1]...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 01-21 06:45:09] Scheduler: Running trials [2]...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 01-21 06:45:10] Scheduler: Running trials [3]...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 01-21 06:45:11] Scheduler: Running trials [4]...

[INFO 01-21 06:45:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>")

[INFO 01-21 06:45:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>")

[INFO 01-21 06:45:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>")

[INFO 01-21 06:45:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>")

[INFO 01-21 06:45:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>")

[ERROR 01-21 06:45:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:12] Scheduler: Failed to fetch val_acc for trial 0, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>").

[INFO 01-21 06:45:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 0 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:12] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>").

[INFO 01-21 06:45:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:12] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>").

[INFO 01-21 06:45:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:12] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>").

[INFO 01-21 06:45:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:12] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9300>").

[INFO 01-21 06:45:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:12] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>")

[INFO 01-21 06:45:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>")

[INFO 01-21 06:45:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>")

[INFO 01-21 06:45:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>")

[INFO 01-21 06:45:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>")

[ERROR 01-21 06:45:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:13] Scheduler: Failed to fetch val_acc for trial 0, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>").

[INFO 01-21 06:45:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 0 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:13] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>").

[INFO 01-21 06:45:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:13] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>").

[INFO 01-21 06:45:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:13] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>").

[INFO 01-21 06:45:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:13] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea92d0>").

[INFO 01-21 06:45:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:13] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>")

[INFO 01-21 06:45:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>")

[INFO 01-21 06:45:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>")

[INFO 01-21 06:45:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>")

[INFO 01-21 06:45:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>")

[ERROR 01-21 06:45:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:14] Scheduler: Failed to fetch val_acc for trial 0, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>").

[INFO 01-21 06:45:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 0 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:14] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>").

[INFO 01-21 06:45:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:14] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>").

[INFO 01-21 06:45:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:14] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>").

[INFO 01-21 06:45:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:14] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ea0>").

[INFO 01-21 06:45:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:14] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:15] Scheduler: Retrieved FAILED trials: [0].

[INFO 01-21 06:45:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa200>")

[INFO 01-21 06:45:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8df0>")

[INFO 01-21 06:45:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8bb0>")

[INFO 01-21 06:45:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea87c0>")

[ERROR 01-21 06:45:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa200>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8df0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8bb0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea87c0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:15] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa200>").

[INFO 01-21 06:45:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:15] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8df0>").

[INFO 01-21 06:45:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:15] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8bb0>").

[INFO 01-21 06:45:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:15] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea87c0>").

[INFO 01-21 06:45:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:15] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/modelbridge/cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 01-21 06:45:15] Scheduler: Running trials [5]...

[INFO 01-21 06:45:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9780>")

[INFO 01-21 06:45:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>")

[INFO 01-21 06:45:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9000>")

[INFO 01-21 06:45:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9450>")

[INFO 01-21 06:45:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98a0>")

[ERROR 01-21 06:45:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9780>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9000>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9450>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98a0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:16] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9780>").

[INFO 01-21 06:45:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:16] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>").

[INFO 01-21 06:45:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:16] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9000>").

[INFO 01-21 06:45:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:16] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9450>").

[INFO 01-21 06:45:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:16] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98a0>").

[INFO 01-21 06:45:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:16] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd08a170>")

[INFO 01-21 06:45:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd088f40>")

[INFO 01-21 06:45:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd08be20>")

[INFO 01-21 06:45:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd08aa70>")

[INFO 01-21 06:45:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd08abc0>")

[ERROR 01-21 06:45:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd08a170>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd088f40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd08be20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd08aa70>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd08abc0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:17] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd08a170>").

[INFO 01-21 06:45:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:17] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd088f40>").

[INFO 01-21 06:45:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:17] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd08be20>").

[INFO 01-21 06:45:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:17] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd08aa70>").

[INFO 01-21 06:45:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:17] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddd08abc0>").

[INFO 01-21 06:45:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:17] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:18] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>")

[INFO 01-21 06:45:18] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>")

[INFO 01-21 06:45:18] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>")

[INFO 01-21 06:45:18] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>")

[INFO 01-21 06:45:18] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>")

[ERROR 01-21 06:45:18] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:18] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:18] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:18] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:18] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:18] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>").

[INFO 01-21 06:45:18] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:18] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>").

[INFO 01-21 06:45:18] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:18] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>").

[INFO 01-21 06:45:18] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:18] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>").

[INFO 01-21 06:45:18] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:18] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>").

[INFO 01-21 06:45:18] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:18] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:19] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>")

[INFO 01-21 06:45:19] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>")

[INFO 01-21 06:45:19] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>")

[INFO 01-21 06:45:19] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>")

[INFO 01-21 06:45:19] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>")

[ERROR 01-21 06:45:19] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:19] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:19] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:19] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:19] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:19] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>").

[INFO 01-21 06:45:19] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:19] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>").

[INFO 01-21 06:45:19] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:19] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>").

[INFO 01-21 06:45:19] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:19] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>").

[INFO 01-21 06:45:19] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:19] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>").

[INFO 01-21 06:45:19] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:19] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>")

[INFO 01-21 06:45:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>")

[INFO 01-21 06:45:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>")

[INFO 01-21 06:45:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>")

[INFO 01-21 06:45:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>")

[ERROR 01-21 06:45:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:20] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>").

[INFO 01-21 06:45:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:20] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>").

[INFO 01-21 06:45:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:20] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>").

[INFO 01-21 06:45:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:20] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>").

[INFO 01-21 06:45:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:20] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa950>").

[INFO 01-21 06:45:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:20] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>")

[INFO 01-21 06:45:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>")

[INFO 01-21 06:45:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>")

[INFO 01-21 06:45:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>")

[INFO 01-21 06:45:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>")

[ERROR 01-21 06:45:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:21] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>").

[INFO 01-21 06:45:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:21] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>").

[INFO 01-21 06:45:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:21] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>").

[INFO 01-21 06:45:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:21] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>").

[INFO 01-21 06:45:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:21] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>").

[INFO 01-21 06:45:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:21] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>")

[INFO 01-21 06:45:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>")

[INFO 01-21 06:45:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>")

[INFO 01-21 06:45:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>")

[INFO 01-21 06:45:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>")

[ERROR 01-21 06:45:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:22] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>").

[INFO 01-21 06:45:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:22] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>").

[INFO 01-21 06:45:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:22] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>").

[INFO 01-21 06:45:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:22] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>").

[INFO 01-21 06:45:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:22] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa080>").

[INFO 01-21 06:45:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:22] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab520>")

[INFO 01-21 06:45:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>")

[INFO 01-21 06:45:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>")

[INFO 01-21 06:45:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaaa0>")

[INFO 01-21 06:45:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab90>")

[ERROR 01-21 06:45:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab520>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaaa0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab90>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:23] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab520>").

[INFO 01-21 06:45:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:23] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab010>").

[INFO 01-21 06:45:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:23] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea93f0>").

[INFO 01-21 06:45:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:23] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaaa0>").

[INFO 01-21 06:45:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:23] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab90>").

[INFO 01-21 06:45:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:23] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaada0>")

[INFO 01-21 06:45:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8d00>")

[INFO 01-21 06:45:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe80>")

[INFO 01-21 06:45:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabaf0>")

[INFO 01-21 06:45:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8e20>")

[ERROR 01-21 06:45:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaada0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8d00>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe80>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabaf0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8e20>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:25] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaada0>").

[INFO 01-21 06:45:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:25] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8d00>").

[INFO 01-21 06:45:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:25] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe80>").

[INFO 01-21 06:45:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:25] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabaf0>").

[INFO 01-21 06:45:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:25] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8e20>").

[INFO 01-21 06:45:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:25] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8940>")

[INFO 01-21 06:45:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ff0>")

[INFO 01-21 06:45:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa0e0>")

[INFO 01-21 06:45:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab460>")

[INFO 01-21 06:45:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab8b0>")

[ERROR 01-21 06:45:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8940>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ff0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa0e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab460>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab8b0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:26] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8940>").

[INFO 01-21 06:45:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:26] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9ff0>").

[INFO 01-21 06:45:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:26] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa0e0>").

[INFO 01-21 06:45:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:26] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab460>").

[INFO 01-21 06:45:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:26] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab8b0>").

[INFO 01-21 06:45:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:26] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99c0>")

[INFO 01-21 06:45:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaa40>")

[INFO 01-21 06:45:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabaf0>")

[INFO 01-21 06:45:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8e50>")

[INFO 01-21 06:45:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab8e0>")

[ERROR 01-21 06:45:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaa40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabaf0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8e50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab8e0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:27] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99c0>").

[INFO 01-21 06:45:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:27] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaa40>").

[INFO 01-21 06:45:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:27] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabaf0>").

[INFO 01-21 06:45:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:27] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8e50>").

[INFO 01-21 06:45:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:27] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab8e0>").

[INFO 01-21 06:45:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:27] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab9d0>")

[INFO 01-21 06:45:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8070>")

[INFO 01-21 06:45:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab9a0>")

[INFO 01-21 06:45:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabb50>")

[INFO 01-21 06:45:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab550>")

[ERROR 01-21 06:45:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab9d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8070>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab9a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabb50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab550>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:28] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab9d0>").

[INFO 01-21 06:45:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:28] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8070>").

[INFO 01-21 06:45:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:28] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab9a0>").

[INFO 01-21 06:45:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:28] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabb50>").

[INFO 01-21 06:45:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:28] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab550>").

[INFO 01-21 06:45:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:28] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:29] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea96c0>")

[INFO 01-21 06:45:29] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>")

[INFO 01-21 06:45:29] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea97e0>")

[INFO 01-21 06:45:29] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae30>")

[INFO 01-21 06:45:29] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe80>")

[ERROR 01-21 06:45:29] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea96c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:29] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:29] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea97e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:29] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:29] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe80>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:29] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea96c0>").

[INFO 01-21 06:45:29] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:29] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>").

[INFO 01-21 06:45:29] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:29] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea97e0>").

[INFO 01-21 06:45:29] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:29] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae30>").

[INFO 01-21 06:45:29] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:29] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe80>").

[INFO 01-21 06:45:29] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:29] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaabf0>")

[INFO 01-21 06:45:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabbb0>")

[INFO 01-21 06:45:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab90>")

[INFO 01-21 06:45:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae90>")

[INFO 01-21 06:45:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9e70>")

[ERROR 01-21 06:45:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaabf0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabbb0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab90>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae90>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9e70>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:30] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaabf0>").

[INFO 01-21 06:45:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:30] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabbb0>").

[INFO 01-21 06:45:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:30] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab90>").

[INFO 01-21 06:45:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:30] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae90>").

[INFO 01-21 06:45:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:30] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9e70>").

[INFO 01-21 06:45:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:30] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9990>")

[INFO 01-21 06:45:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab7f0>")

[INFO 01-21 06:45:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa5f0>")

[INFO 01-21 06:45:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9f00>")

[INFO 01-21 06:45:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>")

[ERROR 01-21 06:45:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9990>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab7f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa5f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9f00>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:31] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9990>").

[INFO 01-21 06:45:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:31] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab7f0>").

[INFO 01-21 06:45:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:31] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa5f0>").

[INFO 01-21 06:45:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:31] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9f00>").

[INFO 01-21 06:45:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:31] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>").

[INFO 01-21 06:45:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:31] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaa40>")

[INFO 01-21 06:45:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabd30>")

[INFO 01-21 06:45:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab880>")

[INFO 01-21 06:45:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9c30>")

[INFO 01-21 06:45:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaa40>")

[ERROR 01-21 06:45:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaa40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabd30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab880>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9c30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaa40>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:32] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaa40>").

[INFO 01-21 06:45:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:32] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabd30>").

[INFO 01-21 06:45:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:32] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab880>").

[INFO 01-21 06:45:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:32] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9c30>").

[INFO 01-21 06:45:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:32] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaa40>").

[INFO 01-21 06:45:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:32] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab550>")

[INFO 01-21 06:45:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe20>")

[INFO 01-21 06:45:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8940>")

[INFO 01-21 06:45:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa350>")

[INFO 01-21 06:45:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabeb0>")

[ERROR 01-21 06:45:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab550>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8940>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa350>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabeb0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:33] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab550>").

[INFO 01-21 06:45:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:33] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe20>").

[INFO 01-21 06:45:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:33] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8940>").

[INFO 01-21 06:45:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:33] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa350>").

[INFO 01-21 06:45:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:33] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabeb0>").

[INFO 01-21 06:45:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:33] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8280>")

[INFO 01-21 06:45:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab610>")

[INFO 01-21 06:45:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa0e0>")

[INFO 01-21 06:45:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8430>")

[INFO 01-21 06:45:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8280>")

[ERROR 01-21 06:45:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8280>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab610>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa0e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8430>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8280>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:34] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8280>").

[INFO 01-21 06:45:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:34] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab610>").

[INFO 01-21 06:45:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:34] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa0e0>").

[INFO 01-21 06:45:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:34] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8430>").

[INFO 01-21 06:45:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:34] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8280>").

[INFO 01-21 06:45:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:35] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe80>")

[INFO 01-21 06:45:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab90>")

[INFO 01-21 06:45:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab7f0>")

[INFO 01-21 06:45:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa980>")

[INFO 01-21 06:45:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe80>")

[ERROR 01-21 06:45:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe80>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab90>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab7f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa980>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe80>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:36] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe80>").

[INFO 01-21 06:45:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:36] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab90>").

[INFO 01-21 06:45:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:36] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab7f0>").

[INFO 01-21 06:45:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:36] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa980>").

[INFO 01-21 06:45:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:36] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe80>").

[INFO 01-21 06:45:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:36] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>")

[INFO 01-21 06:45:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa8c0>")

[INFO 01-21 06:45:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaabf0>")

[INFO 01-21 06:45:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa3e0>")

[INFO 01-21 06:45:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>")

[ERROR 01-21 06:45:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa8c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaabf0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa3e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:37] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>").

[INFO 01-21 06:45:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:37] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa8c0>").

[INFO 01-21 06:45:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:37] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaabf0>").

[INFO 01-21 06:45:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:37] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa3e0>").

[INFO 01-21 06:45:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:37] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>").

[INFO 01-21 06:45:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:37] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>")

[INFO 01-21 06:45:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8280>")

[INFO 01-21 06:45:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabc10>")

[INFO 01-21 06:45:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab7f0>")

[INFO 01-21 06:45:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98d0>")

[ERROR 01-21 06:45:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8280>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabc10>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab7f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98d0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:38] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>").

[INFO 01-21 06:45:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:38] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8280>").

[INFO 01-21 06:45:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:38] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabc10>").

[INFO 01-21 06:45:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:38] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab7f0>").

[INFO 01-21 06:45:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:38] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98d0>").

[INFO 01-21 06:45:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:38] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8430>")

[INFO 01-21 06:45:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8940>")

[INFO 01-21 06:45:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9c30>")

[INFO 01-21 06:45:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa5f0>")

[INFO 01-21 06:45:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8430>")

[ERROR 01-21 06:45:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8430>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8940>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9c30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa5f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8430>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:39] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8430>").

[INFO 01-21 06:45:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:39] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8940>").

[INFO 01-21 06:45:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:39] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9c30>").

[INFO 01-21 06:45:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:39] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa5f0>").

[INFO 01-21 06:45:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:39] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8430>").

[INFO 01-21 06:45:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:39] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9f00>")

[INFO 01-21 06:45:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8bb0>")

[INFO 01-21 06:45:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab670>")

[INFO 01-21 06:45:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>")

[INFO 01-21 06:45:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9f00>")

[ERROR 01-21 06:45:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9f00>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8bb0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab670>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9f00>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:40] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9f00>").

[INFO 01-21 06:45:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:40] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8bb0>").

[INFO 01-21 06:45:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:40] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab670>").

[INFO 01-21 06:45:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:40] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab430>").

[INFO 01-21 06:45:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:40] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9f00>").

[INFO 01-21 06:45:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:40] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab60>")

[INFO 01-21 06:45:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa530>")

[INFO 01-21 06:45:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98d0>")

[INFO 01-21 06:45:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaf80>")

[INFO 01-21 06:45:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab60>")

[ERROR 01-21 06:45:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab60>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa530>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaf80>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab60>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:41] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab60>").

[INFO 01-21 06:45:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:41] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa530>").

[INFO 01-21 06:45:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:41] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98d0>").

[INFO 01-21 06:45:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:41] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaf80>").

[INFO 01-21 06:45:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:41] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab60>").

[INFO 01-21 06:45:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:41] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:42] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa1a0>")

[INFO 01-21 06:45:42] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabdc0>")

[INFO 01-21 06:45:42] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabaf0>")

[INFO 01-21 06:45:42] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa0e0>")

[INFO 01-21 06:45:42] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa1a0>")

[ERROR 01-21 06:45:42] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa1a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:42] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabdc0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:42] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabaf0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:42] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa0e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:42] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa1a0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:42] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa1a0>").

[INFO 01-21 06:45:42] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:42] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabdc0>").

[INFO 01-21 06:45:42] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:42] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabaf0>").

[INFO 01-21 06:45:42] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:42] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa0e0>").

[INFO 01-21 06:45:42] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:42] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa1a0>").

[INFO 01-21 06:45:42] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:42] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaad40>")

[INFO 01-21 06:45:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab60>")

[INFO 01-21 06:45:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaf80>")

[INFO 01-21 06:45:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab640>")

[INFO 01-21 06:45:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaad40>")

[ERROR 01-21 06:45:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaad40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab60>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaf80>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab640>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaad40>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:43] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaad40>").

[INFO 01-21 06:45:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:43] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab60>").

[INFO 01-21 06:45:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:43] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaf80>").

[INFO 01-21 06:45:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:43] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab640>").

[INFO 01-21 06:45:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:43] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaad40>").

[INFO 01-21 06:45:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:43] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:44] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>")

[INFO 01-21 06:45:44] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa0e0>")

[INFO 01-21 06:45:44] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa860>")

[INFO 01-21 06:45:44] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9c30>")

[INFO 01-21 06:45:44] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>")

[ERROR 01-21 06:45:44] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:44] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa0e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:44] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa860>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:44] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9c30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:44] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:44] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>").

[INFO 01-21 06:45:44] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:44] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa0e0>").

[INFO 01-21 06:45:44] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:44] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa860>").

[INFO 01-21 06:45:44] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:44] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9c30>").

[INFO 01-21 06:45:44] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:44] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea99f0>").

[INFO 01-21 06:45:44] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:45] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaa40>")

[INFO 01-21 06:45:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab9a0>")

[INFO 01-21 06:45:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab370>")

[INFO 01-21 06:45:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab7f0>")

[INFO 01-21 06:45:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab970>")

[ERROR 01-21 06:45:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaa40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab9a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab370>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab7f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab970>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:46] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaaa40>").

[INFO 01-21 06:45:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:46] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab9a0>").

[INFO 01-21 06:45:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:46] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab370>").

[INFO 01-21 06:45:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:46] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab7f0>").

[INFO 01-21 06:45:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:46] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab970>").

[INFO 01-21 06:45:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:46] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabaf0>")

[INFO 01-21 06:45:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98d0>")

[INFO 01-21 06:45:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9d50>")

[INFO 01-21 06:45:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab90>")

[INFO 01-21 06:45:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea91e0>")

[ERROR 01-21 06:45:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabaf0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9d50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab90>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea91e0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:47] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabaf0>").

[INFO 01-21 06:45:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:47] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98d0>").

[INFO 01-21 06:45:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:47] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea9d50>").

[INFO 01-21 06:45:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:47] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaab90>").

[INFO 01-21 06:45:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:47] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea91e0>").

[INFO 01-21 06:45:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:47] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8490>")

[INFO 01-21 06:45:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabf10>")

[INFO 01-21 06:45:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa2f0>")

[INFO 01-21 06:45:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8af0>")

[INFO 01-21 06:45:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8490>")

[ERROR 01-21 06:45:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8490>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabf10>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa2f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8af0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8490>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:48] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8490>").

[INFO 01-21 06:45:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:48] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabf10>").

[INFO 01-21 06:45:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:48] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa2f0>").

[INFO 01-21 06:45:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:48] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8af0>").

[INFO 01-21 06:45:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:48] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8490>").

[INFO 01-21 06:45:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:48] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:49] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>")

[INFO 01-21 06:45:49] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea91e0>")

[INFO 01-21 06:45:49] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab1f0>")

[INFO 01-21 06:45:49] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8bb0>")

[INFO 01-21 06:45:49] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabdc0>")

[ERROR 01-21 06:45:49] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:49] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea91e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:49] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab1f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:49] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8bb0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:49] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabdc0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:49] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>").

[INFO 01-21 06:45:49] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:49] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea91e0>").

[INFO 01-21 06:45:49] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:49] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab1f0>").

[INFO 01-21 06:45:49] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:49] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8bb0>").

[INFO 01-21 06:45:49] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:49] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabdc0>").

[INFO 01-21 06:45:49] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:49] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:50] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98a0>")

[INFO 01-21 06:45:50] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>")

[INFO 01-21 06:45:50] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>")

[INFO 01-21 06:45:50] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae30>")

[INFO 01-21 06:45:50] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>")

[ERROR 01-21 06:45:50] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:50] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:50] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:50] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:50] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:50] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98a0>").

[INFO 01-21 06:45:50] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:50] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>").

[INFO 01-21 06:45:50] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:50] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>").

[INFO 01-21 06:45:50] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:50] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae30>").

[INFO 01-21 06:45:50] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:50] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>").

[INFO 01-21 06:45:50] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:50] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:51] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>")

[INFO 01-21 06:45:51] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>")

[INFO 01-21 06:45:51] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>")

[INFO 01-21 06:45:51] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>")

[INFO 01-21 06:45:51] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>")

[ERROR 01-21 06:45:51] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:51] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:51] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:51] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:51] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:51] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>").

[INFO 01-21 06:45:51] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:51] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>").

[INFO 01-21 06:45:51] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:51] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>").

[INFO 01-21 06:45:51] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:51] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>").

[INFO 01-21 06:45:51] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:51] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>").

[INFO 01-21 06:45:51] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:51] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea91e0>")

[INFO 01-21 06:45:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8340>")

[INFO 01-21 06:45:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>")

[INFO 01-21 06:45:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae00>")

[INFO 01-21 06:45:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>")

[ERROR 01-21 06:45:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea91e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8340>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae00>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:52] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea91e0>").

[INFO 01-21 06:45:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:52] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8340>").

[INFO 01-21 06:45:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:52] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>").

[INFO 01-21 06:45:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:52] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae00>").

[INFO 01-21 06:45:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:52] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>").

[INFO 01-21 06:45:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:52] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:53] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa860>")

[INFO 01-21 06:45:53] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>")

[INFO 01-21 06:45:53] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>")

[INFO 01-21 06:45:53] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab550>")

[INFO 01-21 06:45:53] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabf40>")

[ERROR 01-21 06:45:53] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa860>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:53] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:53] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:53] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab550>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:53] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabf40>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:53] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa860>").

[INFO 01-21 06:45:53] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:53] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea8700>").

[INFO 01-21 06:45:53] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:53] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>").

[INFO 01-21 06:45:53] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:53] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceab550>").

[INFO 01-21 06:45:53] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:53] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabf40>").

[INFO 01-21 06:45:53] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:53] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:54] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>")

[INFO 01-21 06:45:54] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae30>")

[INFO 01-21 06:45:54] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98a0>")

[INFO 01-21 06:45:54] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa980>")

[INFO 01-21 06:45:54] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabf10>")

[ERROR 01-21 06:45:54] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:54] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:54] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:54] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa980>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:54] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabf10>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:54] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa590>").

[INFO 01-21 06:45:54] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:54] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaae30>").

[INFO 01-21 06:45:54] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:54] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcea98a0>").

[INFO 01-21 06:45:54] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:54] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceaa980>").

[INFO 01-21 06:45:54] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:54] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabf10>").

[INFO 01-21 06:45:54] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:54] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:55] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>")

[INFO 01-21 06:45:55] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>")

[INFO 01-21 06:45:55] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>")

[INFO 01-21 06:45:55] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>")

[INFO 01-21 06:45:55] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>")

[ERROR 01-21 06:45:55] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:55] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:55] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:55] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:55] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:55] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>").

[INFO 01-21 06:45:55] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:55] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>").

[INFO 01-21 06:45:55] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:55] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>").

[INFO 01-21 06:45:55] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:55] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>").

[INFO 01-21 06:45:55] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:55] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2080>").

[INFO 01-21 06:45:55] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:55] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>")

[INFO 01-21 06:45:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>")

[INFO 01-21 06:45:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>")

[INFO 01-21 06:45:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>")

[INFO 01-21 06:45:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>")

[ERROR 01-21 06:45:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:57] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>").

[INFO 01-21 06:45:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:57] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>").

[INFO 01-21 06:45:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:57] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>").

[INFO 01-21 06:45:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:57] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>").

[INFO 01-21 06:45:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:57] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1e10>").

[INFO 01-21 06:45:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:57] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:58] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>")

[INFO 01-21 06:45:58] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>")

[INFO 01-21 06:45:58] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>")

[INFO 01-21 06:45:58] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>")

[INFO 01-21 06:45:58] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>")

[ERROR 01-21 06:45:58] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:58] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:58] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:58] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:58] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:58] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>").

[INFO 01-21 06:45:58] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:58] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>").

[INFO 01-21 06:45:58] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:58] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>").

[INFO 01-21 06:45:58] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:58] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>").

[INFO 01-21 06:45:58] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:58] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0c40>").

[INFO 01-21 06:45:58] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:58] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:45:59] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>")

[INFO 01-21 06:45:59] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>")

[INFO 01-21 06:45:59] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>")

[INFO 01-21 06:45:59] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>")

[INFO 01-21 06:45:59] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>")

[ERROR 01-21 06:45:59] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:59] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:59] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:59] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:45:59] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:45:59] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>").

[INFO 01-21 06:45:59] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:59] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>").

[INFO 01-21 06:45:59] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:59] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>").

[INFO 01-21 06:45:59] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:59] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>").

[INFO 01-21 06:45:59] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:45:59] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced23e0>").

[INFO 01-21 06:45:59] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:45:59] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:45:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:00] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>")

[INFO 01-21 06:46:00] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>")

[INFO 01-21 06:46:00] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>")

[INFO 01-21 06:46:00] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>")

[INFO 01-21 06:46:00] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>")

[ERROR 01-21 06:46:00] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:00] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:00] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:00] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:00] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:00] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>").

[INFO 01-21 06:46:00] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:00] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>").

[INFO 01-21 06:46:00] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:00] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>").

[INFO 01-21 06:46:00] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:00] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>").

[INFO 01-21 06:46:00] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:00] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>").

[INFO 01-21 06:46:00] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:00] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:01] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>")

[INFO 01-21 06:46:01] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>")

[INFO 01-21 06:46:01] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>")

[INFO 01-21 06:46:01] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>")

[INFO 01-21 06:46:01] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>")

[ERROR 01-21 06:46:01] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:01] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:01] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:01] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:01] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:01] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>").

[INFO 01-21 06:46:01] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:01] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>").

[INFO 01-21 06:46:01] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:01] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>").

[INFO 01-21 06:46:01] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:01] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>").

[INFO 01-21 06:46:01] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:01] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>").

[INFO 01-21 06:46:01] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:01] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:02] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>")

[INFO 01-21 06:46:02] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>")

[INFO 01-21 06:46:02] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>")

[INFO 01-21 06:46:02] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>")

[INFO 01-21 06:46:02] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>")

[ERROR 01-21 06:46:02] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:02] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:02] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:02] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:02] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:02] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>").

[INFO 01-21 06:46:02] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:02] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>").

[INFO 01-21 06:46:02] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:02] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>").

[INFO 01-21 06:46:02] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:02] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>").

[INFO 01-21 06:46:02] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:02] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1d20>").

[INFO 01-21 06:46:02] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:02] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:03] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>")

[INFO 01-21 06:46:03] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>")

[INFO 01-21 06:46:03] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>")

[INFO 01-21 06:46:03] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>")

[INFO 01-21 06:46:03] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>")

[ERROR 01-21 06:46:03] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:03] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:03] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:03] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:03] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:03] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>").

[INFO 01-21 06:46:03] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:03] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>").

[INFO 01-21 06:46:03] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:03] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>").

[INFO 01-21 06:46:03] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:03] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>").

[INFO 01-21 06:46:03] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:03] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>").

[INFO 01-21 06:46:03] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:03] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:04] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>")

[INFO 01-21 06:46:04] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>")

[INFO 01-21 06:46:04] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>")

[INFO 01-21 06:46:04] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>")

[INFO 01-21 06:46:04] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>")

[ERROR 01-21 06:46:04] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:04] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:04] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:04] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:04] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:04] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>").

[INFO 01-21 06:46:04] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:04] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>").

[INFO 01-21 06:46:04] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:04] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>").

[INFO 01-21 06:46:04] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:04] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>").

[INFO 01-21 06:46:04] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:04] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2680>").

[INFO 01-21 06:46:04] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:04] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:05] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>")

[INFO 01-21 06:46:05] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>")

[INFO 01-21 06:46:05] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>")

[INFO 01-21 06:46:05] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>")

[INFO 01-21 06:46:05] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>")

[ERROR 01-21 06:46:05] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:05] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:05] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:05] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:05] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:05] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>").

[INFO 01-21 06:46:05] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:05] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>").

[INFO 01-21 06:46:05] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:05] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>").

[INFO 01-21 06:46:05] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:05] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>").

[INFO 01-21 06:46:05] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:05] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32b0>").

[INFO 01-21 06:46:05] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:05] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:06] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>")

[INFO 01-21 06:46:06] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>")

[INFO 01-21 06:46:06] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>")

[INFO 01-21 06:46:06] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>")

[INFO 01-21 06:46:06] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>")

[ERROR 01-21 06:46:06] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:06] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:06] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:06] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:06] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:06] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>").

[INFO 01-21 06:46:06] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:06] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>").

[INFO 01-21 06:46:06] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:06] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>").

[INFO 01-21 06:46:06] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:06] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>").

[INFO 01-21 06:46:06] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:06] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1c30>").

[INFO 01-21 06:46:06] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:07] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:08] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>")

[INFO 01-21 06:46:08] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>")

[INFO 01-21 06:46:08] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>")

[INFO 01-21 06:46:08] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>")

[INFO 01-21 06:46:08] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>")

[ERROR 01-21 06:46:08] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:08] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:08] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:08] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:08] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:08] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>").

[INFO 01-21 06:46:08] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:08] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>").

[INFO 01-21 06:46:08] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:08] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>").

[INFO 01-21 06:46:08] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:08] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>").

[INFO 01-21 06:46:08] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:08] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1480>").

[INFO 01-21 06:46:08] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:08] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:09] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>")

[INFO 01-21 06:46:09] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>")

[INFO 01-21 06:46:09] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>")

[INFO 01-21 06:46:09] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>")

[INFO 01-21 06:46:09] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>")

[ERROR 01-21 06:46:09] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:09] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:09] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:09] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:09] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:09] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>").

[INFO 01-21 06:46:09] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:09] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>").

[INFO 01-21 06:46:09] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:09] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>").

[INFO 01-21 06:46:09] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:09] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>").

[INFO 01-21 06:46:09] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:09] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2fb0>").

[INFO 01-21 06:46:09] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:09] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:10] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>")

[INFO 01-21 06:46:10] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>")

[INFO 01-21 06:46:10] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>")

[INFO 01-21 06:46:10] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>")

[INFO 01-21 06:46:10] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>")

[ERROR 01-21 06:46:10] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:10] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:10] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:10] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:10] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:10] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>").

[INFO 01-21 06:46:10] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:10] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>").

[INFO 01-21 06:46:10] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:10] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>").

[INFO 01-21 06:46:10] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:10] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>").

[INFO 01-21 06:46:10] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:10] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced19c0>").

[INFO 01-21 06:46:10] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:10] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:11] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>")

[INFO 01-21 06:46:11] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>")

[INFO 01-21 06:46:11] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>")

[INFO 01-21 06:46:11] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>")

[INFO 01-21 06:46:11] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>")

[ERROR 01-21 06:46:11] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:11] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:11] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:11] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:11] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:11] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>").

[INFO 01-21 06:46:11] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:11] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>").

[INFO 01-21 06:46:11] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:11] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>").

[INFO 01-21 06:46:11] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:11] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>").

[INFO 01-21 06:46:11] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:11] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced12a0>").

[INFO 01-21 06:46:11] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:11] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>")

[INFO 01-21 06:46:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>")

[INFO 01-21 06:46:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>")

[INFO 01-21 06:46:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>")

[INFO 01-21 06:46:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>")

[ERROR 01-21 06:46:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:12] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>").

[INFO 01-21 06:46:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:12] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>").

[INFO 01-21 06:46:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:12] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>").

[INFO 01-21 06:46:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:12] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>").

[INFO 01-21 06:46:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:12] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3490>").

[INFO 01-21 06:46:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:12] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>")

[INFO 01-21 06:46:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>")

[INFO 01-21 06:46:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>")

[INFO 01-21 06:46:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>")

[INFO 01-21 06:46:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>")

[ERROR 01-21 06:46:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:13] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>").

[INFO 01-21 06:46:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:13] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>").

[INFO 01-21 06:46:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:13] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>").

[INFO 01-21 06:46:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:13] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>").

[INFO 01-21 06:46:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:13] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1720>").

[INFO 01-21 06:46:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:13] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>")

[INFO 01-21 06:46:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>")

[INFO 01-21 06:46:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>")

[INFO 01-21 06:46:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>")

[INFO 01-21 06:46:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>")

[ERROR 01-21 06:46:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:14] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>").

[INFO 01-21 06:46:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:14] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>").

[INFO 01-21 06:46:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:14] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>").

[INFO 01-21 06:46:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:14] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>").

[INFO 01-21 06:46:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:14] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0640>").

[INFO 01-21 06:46:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:14] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>")

[INFO 01-21 06:46:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>")

[INFO 01-21 06:46:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>")

[INFO 01-21 06:46:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>")

[INFO 01-21 06:46:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>")

[ERROR 01-21 06:46:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:15] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>").

[INFO 01-21 06:46:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:15] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>").

[INFO 01-21 06:46:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:15] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>").

[INFO 01-21 06:46:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:15] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>").

[INFO 01-21 06:46:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:15] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3190>").

[INFO 01-21 06:46:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:15] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>")

[INFO 01-21 06:46:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>")

[INFO 01-21 06:46:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>")

[INFO 01-21 06:46:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>")

[INFO 01-21 06:46:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>")

[ERROR 01-21 06:46:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:16] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>").

[INFO 01-21 06:46:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:16] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>").

[INFO 01-21 06:46:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:16] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>").

[INFO 01-21 06:46:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:16] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>").

[INFO 01-21 06:46:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:16] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced32e0>").

[INFO 01-21 06:46:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:16] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>")

[INFO 01-21 06:46:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>")

[INFO 01-21 06:46:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>")

[INFO 01-21 06:46:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>")

[INFO 01-21 06:46:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>")

[ERROR 01-21 06:46:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:17] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>").

[INFO 01-21 06:46:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:17] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>").

[INFO 01-21 06:46:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:17] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>").

[INFO 01-21 06:46:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:17] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>").

[INFO 01-21 06:46:18] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:18] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1ea0>").

[INFO 01-21 06:46:18] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:18] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:19] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>")

[INFO 01-21 06:46:19] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>")

[INFO 01-21 06:46:19] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>")

[INFO 01-21 06:46:19] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>")

[INFO 01-21 06:46:19] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>")

[ERROR 01-21 06:46:19] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:19] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:19] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:19] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:19] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:19] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>").

[INFO 01-21 06:46:19] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:19] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>").

[INFO 01-21 06:46:19] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:19] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>").

[INFO 01-21 06:46:19] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:19] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>").

[INFO 01-21 06:46:19] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:19] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>").

[INFO 01-21 06:46:19] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:19] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>")

[INFO 01-21 06:46:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>")

[INFO 01-21 06:46:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>")

[INFO 01-21 06:46:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>")

[INFO 01-21 06:46:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>")

[ERROR 01-21 06:46:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:20] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>").

[INFO 01-21 06:46:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:20] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>").

[INFO 01-21 06:46:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:20] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>").

[INFO 01-21 06:46:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:20] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>").

[INFO 01-21 06:46:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:20] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced24d0>").

[INFO 01-21 06:46:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:20] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>")

[INFO 01-21 06:46:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>")

[INFO 01-21 06:46:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>")

[INFO 01-21 06:46:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>")

[INFO 01-21 06:46:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>")

[ERROR 01-21 06:46:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:21] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>").

[INFO 01-21 06:46:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:21] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>").

[INFO 01-21 06:46:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:21] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>").

[INFO 01-21 06:46:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:21] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>").

[INFO 01-21 06:46:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:21] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0940>").

[INFO 01-21 06:46:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:21] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>")

[INFO 01-21 06:46:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>")

[INFO 01-21 06:46:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>")

[INFO 01-21 06:46:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>")

[INFO 01-21 06:46:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>")

[ERROR 01-21 06:46:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:22] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>").

[INFO 01-21 06:46:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:22] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>").

[INFO 01-21 06:46:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:22] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>").

[INFO 01-21 06:46:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:22] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>").

[INFO 01-21 06:46:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:22] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>").

[INFO 01-21 06:46:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:22] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>")

[INFO 01-21 06:46:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>")

[INFO 01-21 06:46:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>")

[INFO 01-21 06:46:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>")

[INFO 01-21 06:46:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>")

[ERROR 01-21 06:46:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:23] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>").

[INFO 01-21 06:46:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:23] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>").

[INFO 01-21 06:46:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:23] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>").

[INFO 01-21 06:46:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:23] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>").

[INFO 01-21 06:46:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:23] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0ca0>").

[INFO 01-21 06:46:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:23] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>")

[INFO 01-21 06:46:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>")

[INFO 01-21 06:46:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>")

[INFO 01-21 06:46:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>")

[INFO 01-21 06:46:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>")

[ERROR 01-21 06:46:24] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:24] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:24] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:24] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:24] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:24] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>").

[INFO 01-21 06:46:24] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:24] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>").

[INFO 01-21 06:46:24] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:24] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>").

[INFO 01-21 06:46:24] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:24] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>").

[INFO 01-21 06:46:24] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:24] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced39d0>").

[INFO 01-21 06:46:24] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:24] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1a50>")

[INFO 01-21 06:46:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0b20>")

[INFO 01-21 06:46:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3f10>")

[INFO 01-21 06:46:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3f40>")

[INFO 01-21 06:46:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3520>")

[ERROR 01-21 06:46:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1a50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0b20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3f10>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3f40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3520>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:25] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1a50>").

[INFO 01-21 06:46:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:25] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0b20>").

[INFO 01-21 06:46:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:25] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3f10>").

[INFO 01-21 06:46:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:25] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3f40>").

[INFO 01-21 06:46:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:25] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3520>").

[INFO 01-21 06:46:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:25] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1780>")

[INFO 01-21 06:46:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2830>")

[INFO 01-21 06:46:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1f30>")

[INFO 01-21 06:46:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>")

[INFO 01-21 06:46:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3310>")

[ERROR 01-21 06:46:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1780>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2830>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1f30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3310>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:26] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1780>").

[INFO 01-21 06:46:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:26] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2830>").

[INFO 01-21 06:46:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:26] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1f30>").

[INFO 01-21 06:46:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:26] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>").

[INFO 01-21 06:46:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:26] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3310>").

[INFO 01-21 06:46:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:26] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3e50>")

[INFO 01-21 06:46:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3400>")

[INFO 01-21 06:46:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>")

[INFO 01-21 06:46:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3f40>")

[INFO 01-21 06:46:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2a10>")

[ERROR 01-21 06:46:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3e50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3400>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3f40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2a10>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:27] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3e50>").

[INFO 01-21 06:46:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:27] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3400>").

[INFO 01-21 06:46:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:27] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>").

[INFO 01-21 06:46:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:27] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3f40>").

[INFO 01-21 06:46:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:27] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2a10>").

[INFO 01-21 06:46:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:27] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>")

[INFO 01-21 06:46:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>")

[INFO 01-21 06:46:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>")

[INFO 01-21 06:46:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>")

[INFO 01-21 06:46:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>")

[ERROR 01-21 06:46:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:28] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>").

[INFO 01-21 06:46:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:28] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>").

[INFO 01-21 06:46:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:28] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>").

[INFO 01-21 06:46:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:28] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>").

[INFO 01-21 06:46:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:28] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1540>").

[INFO 01-21 06:46:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:29] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>")

[INFO 01-21 06:46:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>")

[INFO 01-21 06:46:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>")

[INFO 01-21 06:46:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>")

[INFO 01-21 06:46:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>")

[ERROR 01-21 06:46:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:30] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>").

[INFO 01-21 06:46:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:30] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>").

[INFO 01-21 06:46:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:30] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>").

[INFO 01-21 06:46:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:30] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>").

[INFO 01-21 06:46:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:30] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0a60>").

[INFO 01-21 06:46:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:30] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>")

[INFO 01-21 06:46:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>")

[INFO 01-21 06:46:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>")

[INFO 01-21 06:46:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>")

[INFO 01-21 06:46:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>")

[ERROR 01-21 06:46:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:31] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>").

[INFO 01-21 06:46:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:31] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>").

[INFO 01-21 06:46:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:31] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>").

[INFO 01-21 06:46:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:31] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>").

[INFO 01-21 06:46:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:31] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>").

[INFO 01-21 06:46:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:31] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>")

[INFO 01-21 06:46:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>")

[INFO 01-21 06:46:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>")

[INFO 01-21 06:46:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>")

[INFO 01-21 06:46:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>")

[ERROR 01-21 06:46:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:32] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>").

[INFO 01-21 06:46:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:32] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>").

[INFO 01-21 06:46:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:32] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>").

[INFO 01-21 06:46:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:32] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>").

[INFO 01-21 06:46:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:32] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1b70>").

[INFO 01-21 06:46:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:32] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>")

[INFO 01-21 06:46:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>")

[INFO 01-21 06:46:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>")

[INFO 01-21 06:46:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>")

[INFO 01-21 06:46:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>")

[ERROR 01-21 06:46:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:46:33] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>").

[INFO 01-21 06:46:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:33] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>").

[INFO 01-21 06:46:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:33] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>").

[INFO 01-21 06:46:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:33] Scheduler: Failed to fetch val_acc for trial 4, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>").

[INFO 01-21 06:46:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 4 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:33] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>").

[INFO 01-21 06:46:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

[INFO 01-21 06:46:33] ax.early_stopping.strategies.base: PercentileEarlyStoppingStrategy received empty data. Not stopping any trials.

[INFO 01-21 06:46:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced14b0>")

[INFO 01-21 06:46:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced14b0>")

[INFO 01-21 06:46:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced14b0>")

[INFO 01-21 06:46:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced14b0>")

[ERROR 01-21 06:46:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced14b0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced14b0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced14b0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced14b0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:46:34] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced14b0>").

[INFO 01-21 06:46:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:34] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced14b0>").

[INFO 01-21 06:46:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:34] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced14b0>").

[INFO 01-21 06:46:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:34] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced14b0>").

[INFO 01-21 06:46:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:34] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3e50>")

[INFO 01-21 06:46:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>")

[INFO 01-21 06:46:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1f90>")

[INFO 01-21 06:46:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1f30>")

[ERROR 01-21 06:46:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3e50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1f90>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1f30>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:46:35] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3e50>").

[INFO 01-21 06:46:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:35] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced04c0>").

[INFO 01-21 06:46:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:35] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1f90>").

[INFO 01-21 06:46:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:35] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced1f30>").

[INFO 01-21 06:46:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>")

[INFO 01-21 06:46:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>")

[INFO 01-21 06:46:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>")

[INFO 01-21 06:46:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced38b0>")

[ERROR 01-21 06:46:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced38b0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:46:36] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3040>").

[INFO 01-21 06:46:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:36] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>").

[INFO 01-21 06:46:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:36] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>").

[INFO 01-21 06:46:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:36] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced38b0>").

[INFO 01-21 06:46:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:36] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b50>")

[INFO 01-21 06:46:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3fd0>")

[INFO 01-21 06:46:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3e50>")

[INFO 01-21 06:46:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2d10>")

[ERROR 01-21 06:46:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3fd0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3e50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2d10>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:46:38] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b50>").

[INFO 01-21 06:46:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:38] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3fd0>").

[INFO 01-21 06:46:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:38] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3e50>").

[INFO 01-21 06:46:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:38] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2d10>").

[INFO 01-21 06:46:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b50>")

[INFO 01-21 06:46:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>")

[INFO 01-21 06:46:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0d30>")

[INFO 01-21 06:46:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>")

[ERROR 01-21 06:46:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0d30>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:46:39] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b50>").

[INFO 01-21 06:46:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:39] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3220>").

[INFO 01-21 06:46:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:39] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced0d30>").

[INFO 01-21 06:46:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:39] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2650>").

[INFO 01-21 06:46:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:39] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3100>")

[INFO 01-21 06:46:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>")

[INFO 01-21 06:46:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>")

[INFO 01-21 06:46:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2b00>")

[ERROR 01-21 06:46:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3100>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2b00>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:46:40] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3100>").

[INFO 01-21 06:46:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:40] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>").

[INFO 01-21 06:46:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:40] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3790>").

[INFO 01-21 06:46:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:40] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2b00>").

[INFO 01-21 06:46:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>")

[INFO 01-21 06:46:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>")

[INFO 01-21 06:46:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>")

[INFO 01-21 06:46:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>")

[ERROR 01-21 06:46:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:46:41] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>").

[INFO 01-21 06:46:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:41] Scheduler: Failed to fetch val_acc for trial 2, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>").

[INFO 01-21 06:46:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 2 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:41] Scheduler: Failed to fetch val_acc for trial 3, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>").

[INFO 01-21 06:46:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 3 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:41] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced2230>").

[INFO 01-21 06:46:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:41] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:42] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>")

[INFO 01-21 06:46:42] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced27a0>")

[ERROR 01-21 06:46:42] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:42] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced27a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:46:42] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>").

[INFO 01-21 06:46:42] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:42] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced27a0>").

[INFO 01-21 06:46:42] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:42] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>")

[INFO 01-21 06:46:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced27a0>")

[ERROR 01-21 06:46:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced27a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:46:43] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced3b20>").

[INFO 01-21 06:46:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:43] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddced27a0>").

[INFO 01-21 06:46:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 01-21 06:46:44] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>")

[INFO 01-21 06:46:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabf40>")

[ERROR 01-21 06:46:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:46:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabf40>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:46:45] Scheduler: Failed to fetch val_acc for trial 1, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabe50>").

[INFO 01-21 06:46:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 1 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:46:45] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddceabf40>").

[INFO 01-21 06:46:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcef78e0>")

[ERROR 01-21 06:46:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcef78e0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:46:46] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcef78e0>").

[INFO 01-21 06:46:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:46] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:46:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcef6b00>")

[ERROR 01-21 06:46:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcef6b00>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:46:47] Scheduler: Failed to fetch val_acc for trial 5, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcef6b00>").

[INFO 01-21 06:46:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 5 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:47] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:52] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:55] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:57] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:46:59] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:46:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:02] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:03] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:04] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:07] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:08] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:09] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:12] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:13] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:14] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:17] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:18] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:19] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:21] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:22] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:23] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:24] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:27] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:28] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:29] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:32] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:33] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:34] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:37] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:39] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:42] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:43] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:44] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:47] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:49] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:52] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:55] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:57] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:47:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:47:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:00] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:02] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:03] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:04] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:07] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:08] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:09] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:12] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:13] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:14] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:17] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:18] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:19] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:20] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:22] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:23] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:24] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:25] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:27] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:28] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:29] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:32] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:33] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:34] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:37] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:39] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:42] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:43] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:44] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:47] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:49] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:54] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:55] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:48:59] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:48:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:00] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:03] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:04] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:05] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:08] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:09] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:10] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:12] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:14] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:15] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:17] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:19] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:20] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:21] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:22] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:24] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:25] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:27] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:29] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:31] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:32] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:33] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:36] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:37] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:41] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:42] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:43] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:46] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:47] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:52] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:54] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:57] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:49:59] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:49:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:02] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:03] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:04] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:07] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:08] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:09] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:12] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:13] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:14] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:17] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:18] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:19] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:21] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:22] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:23] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:24] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:27] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:28] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:29] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:31] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:32] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:33] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:34] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:37] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:39] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:42] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:43] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:44] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:47] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:49] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:52] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:54] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:55] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:57] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:50:59] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:50:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:00] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:03] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:04] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:05] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:08] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:09] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:10] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:13] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:14] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:15] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:18] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:19] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:20] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:21] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:23] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:24] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:25] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:28] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:29] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:31] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:33] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:34] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:36] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:39] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:41] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:43] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:44] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:46] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:49] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:54] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:55] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:51:59] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:51:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:00] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:03] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:04] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:05] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:08] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:09] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:10] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:13] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:14] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:15] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:18] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:19] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:20] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:21] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:23] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:24] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:25] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:28] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:29] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:31] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:33] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:34] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:36] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:39] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:41] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:43] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:44] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:46] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:49] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:54] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:55] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:52:59] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:52:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:00] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:02] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:04] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:05] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:07] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:09] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:10] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:12] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:14] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:15] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:17] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:19] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:20] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:21] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:22] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:24] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:25] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:27] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:29] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:31] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:32] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:34] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:36] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:37] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:39] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:41] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:42] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:44] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:46] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:47] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:52] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:55] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:57] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:53:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:53:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:00] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:02] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:03] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:05] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:07] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:08] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:10] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:12] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:13] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:15] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:17] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:18] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:20] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:21] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:22] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:23] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:25] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:27] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:28] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:31] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:32] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:33] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:36] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:37] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:41] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:42] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:43] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:46] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:47] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:52] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:55] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:57] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:54:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:54:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:00] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:02] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:03] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:05] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:07] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:08] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:10] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:12] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:13] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:15] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:17] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:18] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:20] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:21] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:22] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:23] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:25] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:27] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:28] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:31] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:32] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:33] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:36] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:37] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:39] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:41] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:42] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:43] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:46] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:47] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:49] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:52] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:54] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:57] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:55:59] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:55:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:02] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:03] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:04] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:07] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:08] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:09] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:12] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:13] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:14] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:17] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:18] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:20] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:21] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:22] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:23] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:24] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:27] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:28] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:29] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:31] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:32] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:33] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:36] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:37] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:41] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:42] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:43] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:46] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:47] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:52] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:55] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:57] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:56:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:56:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:00] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:02] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:03] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:05] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:07] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:08] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:10] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:12] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:14] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:15] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:17] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:19] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:20] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:21] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:22] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:24] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:25] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:27] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:29] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:31] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:32] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:34] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:36] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:37] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:39] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:41] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:42] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:44] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:46] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:47] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:49] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:52] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:54] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:55] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:57] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:57:59] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:57:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:00] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:01] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:02] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:04] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:05] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:06] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:07] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:09] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:10] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:11] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:12] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:14] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:15] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:16] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:17] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:19] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:20] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:21] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:22] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:24] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:25] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:26] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:27] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:29] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:30] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:31] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:33] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:34] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:35] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:36] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:38] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:39] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:40] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:41] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:43] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:44] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:45] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:46] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:48] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:49] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:50] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:51] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:53] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:54] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:55] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:56] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:58] ax.early_stopping.strategies.base: The number of completed trials (0) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 5).

[INFO 01-21 06:58:59] Scheduler: Retrieved COMPLETED trials: [3].

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:59] ax.early_stopping.strategies.base: The number of completed trials (1) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:58:59] ax.early_stopping.strategies.base: The number of completed trials (1) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:58:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 4).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:00] ax.early_stopping.strategies.base: The number of completed trials (1) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:59:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 4).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:02] ax.early_stopping.strategies.base: The number of completed trials (1) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:59:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 4).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:03] ax.early_stopping.strategies.base: The number of completed trials (1) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:59:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 4).

[INFO 01-21 06:59:04] Scheduler: Retrieved COMPLETED trials: [4].

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:04] ax.early_stopping.strategies.base: The number of completed trials (2) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:04] ax.early_stopping.strategies.base: The number of completed trials (2) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:59:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:05] ax.early_stopping.strategies.base: The number of completed trials (2) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

[INFO 01-21 06:59:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:06] Scheduler: Retrieved COMPLETED trials: [2].

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:06] ax.early_stopping.strategies.base: The number of completed trials (3) is less than the minimum number of curves needed for early stopping (5). Not early stopping.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 01-21 06:59:11] Scheduler: Running trials [6]...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 01-21 06:59:14] Scheduler: Running trials [7]...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 01-21 06:59:18] Scheduler: Running trials [8]...

[INFO 01-21 06:59:20] Scheduler: Retrieved COMPLETED trials: [1, 5].

[INFO 01-21 06:59:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fa5c0>")

[INFO 01-21 06:59:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fa5c0>")

[INFO 01-21 06:59:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fa5c0>")

[ERROR 01-21 06:59:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fa5c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fa5c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fa5c0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:59:20] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fa5c0>").

[INFO 01-21 06:59:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:20] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fa5c0>").

[INFO 01-21 06:59:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:20] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fa5c0>").

[INFO 01-21 06:59:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:20] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:20] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 01-21 06:59:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>")

[INFO 01-21 06:59:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04c70>")

[INFO 01-21 06:59:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04520>")

[ERROR 01-21 06:59:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04c70>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04520>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:20] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>").

[INFO 01-21 06:59:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:20] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04c70>").

[INFO 01-21 06:59:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:20] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04520>").

[INFO 01-21 06:59:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:20] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:20] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64940>")

[INFO 01-21 06:59:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf67dc0>")

[INFO 01-21 06:59:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64e20>")

[ERROR 01-21 06:59:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64940>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf67dc0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64e20>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:21] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64940>").

[INFO 01-21 06:59:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:21] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf67dc0>").

[INFO 01-21 06:59:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:21] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64e20>").

[INFO 01-21 06:59:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:21] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:21] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04220>")

[INFO 01-21 06:59:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>")

[INFO 01-21 06:59:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>")

[ERROR 01-21 06:59:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04220>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:22] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04220>").

[INFO 01-21 06:59:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:22] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>").

[INFO 01-21 06:59:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:22] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>").

[INFO 01-21 06:59:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:22] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:22] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf66470>")

[INFO 01-21 06:59:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64820>")

[INFO 01-21 06:59:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf65690>")

[ERROR 01-21 06:59:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf66470>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64820>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf65690>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:23] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf66470>").

[INFO 01-21 06:59:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:23] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64820>").

[INFO 01-21 06:59:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:23] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf65690>").

[INFO 01-21 06:59:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:23] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64d00>")

[INFO 01-21 06:59:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf66470>")

[INFO 01-21 06:59:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64820>")

[ERROR 01-21 06:59:24] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64d00>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:24] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf66470>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:24] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64820>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:24] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64d00>").

[INFO 01-21 06:59:24] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:24] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf66470>").

[INFO 01-21 06:59:24] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:24] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64820>").

[INFO 01-21 06:59:24] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:24] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:24] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db8e0>")

[INFO 01-21 06:59:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db8e0>")

[INFO 01-21 06:59:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db8e0>")

[ERROR 01-21 06:59:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db8e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db8e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db8e0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:25] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db8e0>").

[INFO 01-21 06:59:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:25] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db8e0>").

[INFO 01-21 06:59:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:25] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db8e0>").

[INFO 01-21 06:59:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:25] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:25] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04550>")

[INFO 01-21 06:59:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07b20>")

[INFO 01-21 06:59:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd06e60>")

[ERROR 01-21 06:59:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04550>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07b20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd06e60>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:26] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04550>").

[INFO 01-21 06:59:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:26] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07b20>").

[INFO 01-21 06:59:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:26] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd06e60>").

[INFO 01-21 06:59:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:26] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:26] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05240>")

[INFO 01-21 06:59:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05ed0>")

[INFO 01-21 06:59:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04220>")

[ERROR 01-21 06:59:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05240>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05ed0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04220>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:28] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05240>").

[INFO 01-21 06:59:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:28] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05ed0>").

[INFO 01-21 06:59:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:28] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04220>").

[INFO 01-21 06:59:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:28] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:28] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:29] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05b40>")

[INFO 01-21 06:59:29] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd068f0>")

[INFO 01-21 06:59:29] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>")

[ERROR 01-21 06:59:29] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05b40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:29] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd068f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:29] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:29] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05b40>").

[INFO 01-21 06:59:29] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:29] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd068f0>").

[INFO 01-21 06:59:29] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:29] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>").

[INFO 01-21 06:59:29] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:29] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:29] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd041f0>")

[INFO 01-21 06:59:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04ac0>")

[INFO 01-21 06:59:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04130>")

[ERROR 01-21 06:59:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd041f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04ac0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04130>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:30] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd041f0>").

[INFO 01-21 06:59:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:30] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04ac0>").

[INFO 01-21 06:59:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:30] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04130>").

[INFO 01-21 06:59:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:30] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:30] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dace0>")

[INFO 01-21 06:59:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da710>")

[INFO 01-21 06:59:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d92d0>")

[ERROR 01-21 06:59:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dace0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da710>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d92d0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:31] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dace0>").

[INFO 01-21 06:59:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:31] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da710>").

[INFO 01-21 06:59:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:31] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d92d0>").

[INFO 01-21 06:59:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:31] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:31] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da8c0>")

[INFO 01-21 06:59:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8220>")

[INFO 01-21 06:59:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da680>")

[ERROR 01-21 06:59:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da8c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8220>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da680>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:32] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da8c0>").

[INFO 01-21 06:59:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:32] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8220>").

[INFO 01-21 06:59:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:32] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da680>").

[INFO 01-21 06:59:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:32] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:32] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8910>")

[INFO 01-21 06:59:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dac20>")

[INFO 01-21 06:59:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9720>")

[ERROR 01-21 06:59:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8910>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dac20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9720>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:33] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8910>").

[INFO 01-21 06:59:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:33] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dac20>").

[INFO 01-21 06:59:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:33] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9720>").

[INFO 01-21 06:59:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:33] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:33] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05ed0>")

[INFO 01-21 06:59:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd042b0>")

[INFO 01-21 06:59:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64e20>")

[ERROR 01-21 06:59:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05ed0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd042b0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64e20>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:34] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05ed0>").

[INFO 01-21 06:59:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:34] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd042b0>").

[INFO 01-21 06:59:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:34] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64e20>").

[INFO 01-21 06:59:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:34] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:34] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd047f0>")

[INFO 01-21 06:59:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd070a0>")

[INFO 01-21 06:59:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04550>")

[ERROR 01-21 06:59:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd047f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd070a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04550>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:35] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd047f0>").

[INFO 01-21 06:59:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:35] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd070a0>").

[INFO 01-21 06:59:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:35] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04550>").

[INFO 01-21 06:59:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:35] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:35] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05ed0>")

[INFO 01-21 06:59:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05930>")

[INFO 01-21 06:59:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd042b0>")

[ERROR 01-21 06:59:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05ed0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05930>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd042b0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:36] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05ed0>").

[INFO 01-21 06:59:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:36] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05930>").

[INFO 01-21 06:59:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:36] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd042b0>").

[INFO 01-21 06:59:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:36] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:36] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>")

[INFO 01-21 06:59:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>")

[INFO 01-21 06:59:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd06cb0>")

[ERROR 01-21 06:59:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd06cb0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:37] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>").

[INFO 01-21 06:59:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:37] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>").

[INFO 01-21 06:59:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:37] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd06cb0>").

[INFO 01-21 06:59:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:37] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:37] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04400>")

[INFO 01-21 06:59:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>")

[INFO 01-21 06:59:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07c40>")

[ERROR 01-21 06:59:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04400>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07c40>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:38] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04400>").

[INFO 01-21 06:59:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:38] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>").

[INFO 01-21 06:59:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:38] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07c40>").

[INFO 01-21 06:59:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:38] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:38] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dace0>")

[INFO 01-21 06:59:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da2c0>")

[INFO 01-21 06:59:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d98a0>")

[ERROR 01-21 06:59:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dace0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da2c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d98a0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:39] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dace0>").

[INFO 01-21 06:59:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:39] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da2c0>").

[INFO 01-21 06:59:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:39] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d98a0>").

[INFO 01-21 06:59:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:39] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:39] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07c70>")

[INFO 01-21 06:59:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07880>")

[INFO 01-21 06:59:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>")

[ERROR 01-21 06:59:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07c70>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07880>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:40] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07c70>").

[INFO 01-21 06:59:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:40] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07880>").

[INFO 01-21 06:59:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:40] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>").

[INFO 01-21 06:59:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:40] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:40] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf659c0>")

[INFO 01-21 06:59:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64e20>")

[INFO 01-21 06:59:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf679a0>")

[ERROR 01-21 06:59:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf659c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64e20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf679a0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:41] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf659c0>").

[INFO 01-21 06:59:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:41] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64e20>").

[INFO 01-21 06:59:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:41] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf679a0>").

[INFO 01-21 06:59:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:41] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:42] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf679a0>")

[INFO 01-21 06:59:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64d00>")

[INFO 01-21 06:59:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf647f0>")

[ERROR 01-21 06:59:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf679a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64d00>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf647f0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:43] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf679a0>").

[INFO 01-21 06:59:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:43] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64d00>").

[INFO 01-21 06:59:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:43] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf647f0>").

[INFO 01-21 06:59:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:43] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:43] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:44] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9c00>")

[INFO 01-21 06:59:44] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daa70>")

[INFO 01-21 06:59:44] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da8c0>")

[ERROR 01-21 06:59:44] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9c00>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:44] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daa70>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:44] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da8c0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:44] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9c00>").

[INFO 01-21 06:59:44] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:44] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daa70>").

[INFO 01-21 06:59:44] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:44] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da8c0>").

[INFO 01-21 06:59:44] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:44] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:44] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>")

[INFO 01-21 06:59:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>")

[INFO 01-21 06:59:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>")

[ERROR 01-21 06:59:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:45] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>").

[INFO 01-21 06:59:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:45] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>").

[INFO 01-21 06:59:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:45] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>").

[INFO 01-21 06:59:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:45] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:45] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05240>")

[INFO 01-21 06:59:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd048b0>")

[INFO 01-21 06:59:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>")

[ERROR 01-21 06:59:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05240>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd048b0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:46] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05240>").

[INFO 01-21 06:59:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:46] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd048b0>").

[INFO 01-21 06:59:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:46] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd056c0>").

[INFO 01-21 06:59:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:46] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:46] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9450>")

[INFO 01-21 06:59:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dab00>")

[INFO 01-21 06:59:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da590>")

[ERROR 01-21 06:59:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9450>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dab00>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da590>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:47] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9450>").

[INFO 01-21 06:59:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:47] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dab00>").

[INFO 01-21 06:59:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:47] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da590>").

[INFO 01-21 06:59:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:47] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:47] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daf20>")

[INFO 01-21 06:59:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daef0>")

[INFO 01-21 06:59:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8220>")

[ERROR 01-21 06:59:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daf20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daef0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8220>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:48] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daf20>").

[INFO 01-21 06:59:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:48] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daef0>").

[INFO 01-21 06:59:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:48] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8220>").

[INFO 01-21 06:59:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:48] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:48] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:49] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf651e0>")

[INFO 01-21 06:59:49] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf66cb0>")

[INFO 01-21 06:59:49] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf679a0>")

[ERROR 01-21 06:59:49] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf651e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:49] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf66cb0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:49] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf679a0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 06:59:49] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf651e0>").

[INFO 01-21 06:59:49] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:49] Scheduler: Failed to fetch val_acc for trial 6, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf66cb0>").

[INFO 01-21 06:59:49] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 6 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:49] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf679a0>").

[INFO 01-21 06:59:49] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:49] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 06:59:49] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:50] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04550>")

[INFO 01-21 06:59:50] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf65870>")

[ERROR 01-21 06:59:50] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04550>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:50] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf65870>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:59:50] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04550>").

[INFO 01-21 06:59:50] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:50] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf65870>").

[INFO 01-21 06:59:50] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:50] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 06:59:50] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:51] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daf20>")

[INFO 01-21 06:59:51] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>")

[ERROR 01-21 06:59:51] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daf20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:51] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:59:51] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daf20>").

[INFO 01-21 06:59:51] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:51] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>").

[INFO 01-21 06:59:51] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:51] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 06:59:51] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04ac0>")

[INFO 01-21 06:59:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf659c0>")

[ERROR 01-21 06:59:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04ac0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf659c0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:59:52] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04ac0>").

[INFO 01-21 06:59:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:52] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf659c0>").

[INFO 01-21 06:59:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:52] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 06:59:52] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:53] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f9390>")

[INFO 01-21 06:59:53] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f87f0>")

[ERROR 01-21 06:59:53] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f9390>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 06:59:53] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f87f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:59:53] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f9390>").

[INFO 01-21 06:59:53] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 06:59:53] Scheduler: Failed to fetch val_acc for trial 7, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f87f0>").

[INFO 01-21 06:59:53] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 7 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:53] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 06:59:53] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:54] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db550>")

[ERROR 01-21 06:59:54] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db550>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:59:54] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db550>").

[INFO 01-21 06:59:54] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:54] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 06:59:54] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:55] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da710>")

[ERROR 01-21 06:59:56] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da710>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:59:56] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da710>").

[INFO 01-21 06:59:56] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:56] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 06:59:56] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf66cb0>")

[ERROR 01-21 06:59:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf66cb0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:59:57] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf66cb0>").

[INFO 01-21 06:59:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:57] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 06:59:57] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:58] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf651e0>")

[ERROR 01-21 06:59:58] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf651e0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:59:58] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf651e0>").

[INFO 01-21 06:59:58] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:58] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 06:59:58] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 06:59:59] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05b40>")

[ERROR 01-21 06:59:59] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05b40>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 06:59:59] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05b40>").

[INFO 01-21 06:59:59] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 06:59:59] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 06:59:59] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 06:59:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:00:00] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>")

[ERROR 01-21 07:00:00] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:00:00] Scheduler: Failed to fetch val_acc for trial 8, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07ee0>").

[INFO 01-21 07:00:00] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 8 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:00] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:00] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:01] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:01] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:02] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:02] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:03] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:03] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:04] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:04] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:06] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:06] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:07] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:07] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:08] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:08] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:09] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:09] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:10] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:10] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:11] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:11] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:12] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:12] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:13] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:13] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:14] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:15] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:16] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:16] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:17] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:17] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:18] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:18] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:19] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:19] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:20] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:20] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:21] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:21] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:22] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:22] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:23] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:25] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:25] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:26] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:00:26] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:27] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:27] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:28] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:28] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:29] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:29] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:30] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:30] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:31] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:31] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:32] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:32] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:33] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:33] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:35] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:35] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:36] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:36] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:37] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:37] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:38] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:38] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:39] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:39] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:40] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:40] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:41] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:41] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:42] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:42] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:44] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:44] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 01-21 07:00:45] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:45] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:46] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:46] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:47] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:47] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:48] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:48] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:49] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:49] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:51] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:51] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:52] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:52] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:53] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:53] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:54] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:54] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:55] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:55] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:56] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:56] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:57] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:57] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:58] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:00:58] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:00:59] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:00:59] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:00:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:00] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:00] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:02] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:02] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:03] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:03] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:04] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:04] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:05] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:05] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:06] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:06] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:07] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:07] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:08] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:08] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:09] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:09] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:11] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:11] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:12] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:12] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:13] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:13] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:14] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:14] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:15] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:15] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:16] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:16] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:17] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:17] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:18] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:18] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:19] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:19] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:21] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:21] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:22] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:22] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:23] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:24] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:24] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:25] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:25] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:26] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:26] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:27] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:27] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:28] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:28] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:29] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:29] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:31] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:31] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:32] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:32] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:33] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:01:33] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:01:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:34] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:34] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:34] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:34] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:34] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:34] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:34] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:34] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9512746334075928) across comparable trials.

[INFO 01-21 07:01:34] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:34] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.29994666666666664.

[INFO 01-21 07:01:34] ax.early_stopping.strategies.base: Trial 7's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:35] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:35] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:35] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:35] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:35] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:35] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:35] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:35] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9512746334075928) across comparable trials.

[INFO 01-21 07:01:35] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:35] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.29994666666666664.

[INFO 01-21 07:01:35] ax.early_stopping.strategies.base: Trial 7's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:36] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:36] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:36] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:36] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:36] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:36] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:36] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:36] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9512746334075928) across comparable trials.

[INFO 01-21 07:01:36] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:36] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.29994666666666664.

[INFO 01-21 07:01:36] ax.early_stopping.strategies.base: Trial 7's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:37] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:38] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:38] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:38] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:38] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:38] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:38] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:38] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:38] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:38] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:38] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:38] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:39] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:39] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:39] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:39] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:39] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:39] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:39] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:39] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:39] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:39] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:39] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:39] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:40] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:40] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:40] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:40] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:40] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:40] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:40] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:40] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:40] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:40] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:40] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:40] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:41] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:41] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:41] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:41] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:41] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:41] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:41] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:41] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:41] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:41] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:41] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:41] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:42] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:42] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:42] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:42] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:42] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:42] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:42] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:42] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:42] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:42] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:42] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:42] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:43] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:43] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:43] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:43] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:43] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:43] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:43] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:43] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:43] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:43] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:43] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:43] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:45] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:45] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:45] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:45] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:45] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:45] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:45] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:45] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:45] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:45] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:45] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:45] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:46] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:46] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:46] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:46] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:46] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:46] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:46] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:46] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:46] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:46] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:46] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:46] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:47] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:47] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:47] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:47] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:47] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:47] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:47] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:47] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:47] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:47] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:47] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:47] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:48] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:48] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:48] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.29994666666666664.

[INFO 01-21 07:01:48] ax.early_stopping.strategies.base: Trial 8's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:01:48] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:48] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:48] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:48] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:48] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:48] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:48] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:48] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.959629762172699) across comparable trials.

[INFO 01-21 07:01:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:49] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:49] ax.early_stopping.strategies.percentile: Considering trial 8 for early stopping.

[INFO 01-21 07:01:49] ax.early_stopping.strategies.base: Last progression of Trial 8 is 0.3999466666666667.

[INFO 01-21 07:01:49] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:49] ax.early_stopping.strategies.percentile: Early stopping decision for 8: True. Reason: Trial objective value 0.9328844547271729 is worse than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:01:49] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:49] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:49] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:49] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:01:49] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:49] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:49] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:49] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 01-21 07:01:53] Scheduler: Running trials [9]...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:54] Scheduler: Generated all trials that can be generated currently. Max parallelism currently reached.

[INFO 01-21 07:01:54] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3840250>")

[ERROR 01-21 07:01:54] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3840250>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:01:54] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3840250>").

[INFO 01-21 07:01:54] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:54] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:54] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:01:54] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:01:54] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:54] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:54] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:54] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:01:54] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:54] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:54] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:54] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:01:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:01:55] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da290>")

[ERROR 01-21 07:01:55] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da290>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:01:55] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38da290>").

[INFO 01-21 07:01:55] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:55] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:55] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:01:55] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:01:55] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:55] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:55] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:55] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:01:55] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:55] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:55] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:55] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:01:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:01:56] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf5f610>")

[ERROR 01-21 07:01:56] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf5f610>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:01:56] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf5f610>").

[INFO 01-21 07:01:56] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:56] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:56] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:01:56] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:01:56] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:56] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:56] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:56] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:01:56] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:56] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:56] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:56] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:01:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:01:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3841090>")

[ERROR 01-21 07:01:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3841090>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:01:57] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3841090>").

[INFO 01-21 07:01:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:57] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:57] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:01:57] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:01:57] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:57] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:57] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:57] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:01:57] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:57] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:57] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:57] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:01:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:01:58] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daa10>")

[ERROR 01-21 07:01:58] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daa10>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:01:58] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daa10>").

[INFO 01-21 07:01:58] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:58] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:01:58] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:01:58] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:01:58] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:01:58] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:01:58] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:58] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:01:58] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:01:58] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:01:58] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:01:58] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:01:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:01:59] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388ce50>")

[ERROR 01-21 07:01:59] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388ce50>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:01:59] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388ce50>").

[INFO 01-21 07:01:59] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:01:59] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:02:00] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:00] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:00] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:00] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:02:00] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:00] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:00] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:00] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:00] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:00] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:01] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388fe50>")

[ERROR 01-21 07:02:01] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388fe50>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:01] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388fe50>").

[INFO 01-21 07:02:01] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:01] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:02:01] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:01] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:01] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:01] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:02:01] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:01] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:01] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:01] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:01] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:01] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:02] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf5ee30>")

[ERROR 01-21 07:02:02] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf5ee30>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:02] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf5ee30>").

[INFO 01-21 07:02:02] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:02] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:02:02] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:02] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:02] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:02] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:02:02] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:02] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:02] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:02] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:02] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:02] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:03] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3842470>")

[ERROR 01-21 07:02:03] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3842470>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:03] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3842470>").

[INFO 01-21 07:02:03] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:03] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:02:03] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:03] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:03] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:03] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:02:03] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:03] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:03] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:03] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:03] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:03] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:04] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3841840>")

[ERROR 01-21 07:02:04] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3841840>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:04] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3841840>").

[INFO 01-21 07:02:04] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:04] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:02:04] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:04] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:04] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:04] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:02:04] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:04] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:04] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:04] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:04] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:04] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:05] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388ff40>")

[ERROR 01-21 07:02:05] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388ff40>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:05] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388ff40>").

[INFO 01-21 07:02:05] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:05] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:02:05] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:05] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:05] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:05] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.3999466666666667.

[INFO 01-21 07:02:05] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:05] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9643920660018921 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:05] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:05] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:05] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:05] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:06] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3840c70>")

[ERROR 01-21 07:02:07] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3840c70>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:07] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3840c70>").

[INFO 01-21 07:02:07] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:07] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:07] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:07] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:07] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:07] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:07] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:07] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9553400576114655) across comparable trials.

[INFO 01-21 07:02:07] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:07] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:07] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:07] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:08] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07070>")

[ERROR 01-21 07:02:08] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07070>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:08] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07070>").

[INFO 01-21 07:02:08] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:08] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:08] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:08] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:08] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:08] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:08] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:08] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9553400576114655) across comparable trials.

[INFO 01-21 07:02:08] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:08] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:08] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:08] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:09] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db010>")

[ERROR 01-21 07:02:09] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db010>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:09] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db010>").

[INFO 01-21 07:02:09] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:09] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:09] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:09] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:09] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:09] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:09] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:09] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9553400576114655) across comparable trials.

[INFO 01-21 07:02:09] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:09] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:09] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:09] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:10] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>")

[ERROR 01-21 07:02:10] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:10] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>").

[INFO 01-21 07:02:10] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:10] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:10] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:10] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:10] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:10] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:10] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:10] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9553400576114655) across comparable trials.

[INFO 01-21 07:02:10] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:10] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:10] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:10] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:11] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d95a0>")

[ERROR 01-21 07:02:11] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d95a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:11] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d95a0>").

[INFO 01-21 07:02:11] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:11] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:11] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:11] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:11] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:11] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:11] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:11] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9553400576114655) across comparable trials.

[INFO 01-21 07:02:11] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:11] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:11] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:11] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9180>")

[ERROR 01-21 07:02:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9180>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:12] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9180>").

[INFO 01-21 07:02:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:12] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:13] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:13] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:13] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:13] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:13] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:13] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9553400576114655) across comparable trials.

[INFO 01-21 07:02:13] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:13] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:13] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:13] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c05b0>")

[ERROR 01-21 07:02:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c05b0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:14] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c05b0>").

[INFO 01-21 07:02:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:14] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:14] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:14] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:14] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:14] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:14] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:14] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9553400576114655) across comparable trials.

[INFO 01-21 07:02:14] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:14] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.3999466666666667.

[INFO 01-21 07:02:14] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:02:14] ax.early_stopping.strategies.percentile: Early stopping decision for 7: False. Reason: Trial objective value 0.9609209895133972 is better than 70.0-th percentile (0.9577004909515381) across comparable trials.

[INFO 01-21 07:02:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf67e80>")

[ERROR 01-21 07:02:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf67e80>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:15] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf67e80>").

[INFO 01-21 07:02:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:15] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:15] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:15] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:15] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:15] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:15] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:15] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:15] ax.early_stopping.strategies.percentile: Considering trial 7 for early stopping.

[INFO 01-21 07:02:15] ax.early_stopping.strategies.base: Last progression of Trial 7 is 0.49994666666666665.

[INFO 01-21 07:02:15] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:15] ax.early_stopping.strategies.percentile: Early stopping decision for 7: True. Reason: Trial objective value 0.9590466022491455 is worse than 70.0-th percentile (0.9593579888343811) across comparable trials.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 01-21 07:02:19] Scheduler: Running trials [10]...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:20] Scheduler: Generated all trials that can be generated currently. Max parallelism currently reached.

[INFO 01-21 07:02:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04fa0>")

[INFO 01-21 07:02:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fb130>")

[ERROR 01-21 07:02:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04fa0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:02:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fb130>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:20] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04fa0>").

[INFO 01-21 07:02:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:02:20] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fb130>").

[INFO 01-21 07:02:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:21] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:21] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:21] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:21] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:21] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:21] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:21] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:21] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:21] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>")

[INFO 01-21 07:02:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>")

[ERROR 01-21 07:02:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:02:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:22] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>").

[INFO 01-21 07:02:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:02:22] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>").

[INFO 01-21 07:02:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:22] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:22] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:22] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:22] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:22] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:22] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:22] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:22] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:22] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3d00>")

[INFO 01-21 07:02:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3d00>")

[ERROR 01-21 07:02:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3d00>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:02:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3d00>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:23] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3d00>").

[INFO 01-21 07:02:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:02:23] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3d00>").

[INFO 01-21 07:02:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:23] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:23] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:23] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:23] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:23] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:23] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:23] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:23] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db340>")

[INFO 01-21 07:02:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db340>")

[ERROR 01-21 07:02:24] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db340>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:02:24] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db340>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:24] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db340>").

[INFO 01-21 07:02:24] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:02:24] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db340>").

[INFO 01-21 07:02:24] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:24] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:24] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:24] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:24] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:24] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:24] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:24] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:24] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:24] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>")

[INFO 01-21 07:02:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>")

[ERROR 01-21 07:02:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:02:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:25] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>").

[INFO 01-21 07:02:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:02:25] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>").

[INFO 01-21 07:02:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:25] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:25] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:25] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:25] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:25] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:25] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:25] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:25] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:25] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2e90>")

[INFO 01-21 07:02:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0be0>")

[ERROR 01-21 07:02:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2e90>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:02:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0be0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:26] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2e90>").

[INFO 01-21 07:02:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:02:26] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0be0>").

[INFO 01-21 07:02:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:26] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:26] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:26] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:26] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:26] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:26] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:26] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:26] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:26] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1cc0>")

[INFO 01-21 07:02:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2350>")

[ERROR 01-21 07:02:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1cc0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:02:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2350>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:27] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1cc0>").

[INFO 01-21 07:02:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:02:27] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2350>").

[INFO 01-21 07:02:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:27] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:27] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:27] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:27] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:27] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:27] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:27] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:27] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:27] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0700>")

[INFO 01-21 07:02:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9510>")

[ERROR 01-21 07:02:29] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0700>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:02:29] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9510>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:29] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0700>").

[INFO 01-21 07:02:29] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:02:29] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9510>").

[INFO 01-21 07:02:29] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:29] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:29] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:29] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:29] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:29] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:29] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:29] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:29] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:29] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9300>")

[INFO 01-21 07:02:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9300>")

[ERROR 01-21 07:02:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9300>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:02:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9300>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:30] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9300>").

[INFO 01-21 07:02:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:02:30] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9300>").

[INFO 01-21 07:02:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:30] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:30] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:30] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:30] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:30] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:30] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:30] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:30] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:30] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38406a0>")

[INFO 01-21 07:02:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3843520>")

[ERROR 01-21 07:02:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38406a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:02:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3843520>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:31] Scheduler: Failed to fetch val_acc for trial 9, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38406a0>").

[INFO 01-21 07:02:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 9 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:02:31] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3843520>").

[INFO 01-21 07:02:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:31] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:31] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:31] ax.early_stopping.strategies.base: There is not yet any data associated with trial 9 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:31] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:31] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:31] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:31] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:31] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:31] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2530>")

[ERROR 01-21 07:02:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2530>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:32] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2530>").

[INFO 01-21 07:02:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:32] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:32] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:32] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:32] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:32] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:32] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:32] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:32] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:32] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:32] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:32] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daa10>")

[ERROR 01-21 07:02:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daa10>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:33] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38daa10>").

[INFO 01-21 07:02:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:33] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:33] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:33] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:33] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:33] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:33] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:33] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:33] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:33] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:33] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:33] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8d30>")

[ERROR 01-21 07:02:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8d30>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:34] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8d30>").

[INFO 01-21 07:02:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:34] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:34] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:34] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:34] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:34] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:34] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:34] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:34] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:34] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:34] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:34] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dbca0>")

[ERROR 01-21 07:02:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dbca0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:36] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38dbca0>").

[INFO 01-21 07:02:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:36] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:36] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:36] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:36] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:36] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:36] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:36] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:36] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:36] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:36] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:36] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>")

[ERROR 01-21 07:02:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:37] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>").

[INFO 01-21 07:02:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:37] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:37] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:37] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:37] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:37] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:37] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:37] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:37] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:37] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:37] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:37] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3550>")

[ERROR 01-21 07:02:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3550>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:38] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3550>").

[INFO 01-21 07:02:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:38] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:38] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:38] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:38] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:38] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:38] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:38] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:38] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:38] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:38] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:38] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8790>")

[ERROR 01-21 07:02:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8790>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:39] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8790>").

[INFO 01-21 07:02:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:39] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:02:39] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:39] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:39] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:39] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:39] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:39] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:39] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:39] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.49994666666666665.

[INFO 01-21 07:02:39] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.950077
2    0.960604
3    0.939967
4    0.904845
5    0.934662
6    0.967661
7    0.959047
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:02:39] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9676614999771118 is better than 70.0-th percentile (0.9593579888343811) across comparable trials.

[INFO 01-21 07:02:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>")

[ERROR 01-21 07:02:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:40] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>").

[INFO 01-21 07:02:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:40] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:40] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:40] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:40] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:40] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:40] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:40] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:40] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:40] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:40] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:40] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9540>")

[ERROR 01-21 07:02:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9540>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:41] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9540>").

[INFO 01-21 07:02:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:41] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:41] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:41] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:41] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:41] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:41] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:41] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:41] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:41] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:41] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:41] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:42] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d95a0>")

[ERROR 01-21 07:02:42] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d95a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:42] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d95a0>").

[INFO 01-21 07:02:42] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:42] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:43] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:43] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:43] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:43] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:43] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:43] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:43] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:43] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:43] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:43] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:44] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3850>")

[ERROR 01-21 07:02:44] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3850>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:44] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3850>").

[INFO 01-21 07:02:44] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:44] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:44] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:44] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:44] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:44] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:44] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:44] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:44] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:44] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:44] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:44] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1e10>")

[ERROR 01-21 07:02:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1e10>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:45] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1e10>").

[INFO 01-21 07:02:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:45] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:45] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:45] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:45] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:45] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:45] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:45] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:45] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:45] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:45] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:45] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>")

[ERROR 01-21 07:02:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:46] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>").

[INFO 01-21 07:02:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:46] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:46] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:46] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:46] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:46] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:46] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:46] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:46] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:46] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:46] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:46] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:47] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38406a0>")

[ERROR 01-21 07:02:47] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38406a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:47] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38406a0>").

[INFO 01-21 07:02:47] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:47] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:47] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:47] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:47] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:47] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:47] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:47] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:47] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:47] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:47] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:47] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db1f0>")

[ERROR 01-21 07:02:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db1f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:48] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38db1f0>").

[INFO 01-21 07:02:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:48] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:48] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:48] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:48] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:48] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:48] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:48] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:48] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:48] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:48] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:48] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:49] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64190>")

[ERROR 01-21 07:02:49] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64190>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:49] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64190>").

[INFO 01-21 07:02:49] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:49] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:50] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:50] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:50] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:50] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:50] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:50] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:50] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:50] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:50] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:50] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:51] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c19c0>")

[ERROR 01-21 07:02:51] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c19c0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:51] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c19c0>").

[INFO 01-21 07:02:51] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:51] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:51] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:51] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:51] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:51] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:51] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:51] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:51] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:51] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:51] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:51] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2b90>")

[ERROR 01-21 07:02:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2b90>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:52] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2b90>").

[INFO 01-21 07:02:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:52] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:52] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:52] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:52] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:52] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:52] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:52] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:52] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:52] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:52] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:52] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:53] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9300>")

[ERROR 01-21 07:02:53] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9300>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:53] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9300>").

[INFO 01-21 07:02:53] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:53] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:53] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:53] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:53] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:53] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:53] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:53] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:53] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:53] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:53] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:53] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:54] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>")

[ERROR 01-21 07:02:54] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:54] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>").

[INFO 01-21 07:02:54] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:54] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:54] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:54] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:54] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:54] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:54] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:54] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:54] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:54] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:54] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:54] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:55] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fada0>")

[ERROR 01-21 07:02:55] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fada0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:55] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fada0>").

[INFO 01-21 07:02:55] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:55] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:55] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:55] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:55] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:55] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:55] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:55] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:55] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:55] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:55] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:55] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:02:56] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8d30>")

[ERROR 01-21 07:02:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8d30>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:02:57] Scheduler: Failed to fetch val_acc for trial 10, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d8d30>").

[INFO 01-21 07:02:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 10 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:57] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:57] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:57] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:57] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:57] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:57] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:57] ax.early_stopping.strategies.base: There is not yet any data associated with trial 10 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:02:57] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:57] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:57] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:57] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:58] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:58] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:58] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:58] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:58] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:58] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:58] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:58] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:02:58] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:58] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:58] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:58] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:58] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:02:59] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:02:59] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:59] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:02:59] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:02:59] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:02:59] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:59] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:02:59] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:02:59] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:02:59] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:02:59] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:02:59] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:02:59] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:02:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:00] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:00] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:00] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:00] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:00] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:03:00] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:00] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:00] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:00] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:00] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:00] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:00] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:00] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:01] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:01] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:01] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:01] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:01] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:03:01] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:01] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:01] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:01] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:01] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:01] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:01] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:01] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:02] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:02] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:02] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:03] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:03] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:03:03] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:03] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:03] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:03] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:03] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:03] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:03] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:03] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:04] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:04] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:04] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:04] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:04] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:03:04] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:04] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:04] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:04] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:04] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:04] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:04] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:04] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:05] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:05] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:05] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:05] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:05] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:03:05] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:05] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:05] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:05] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:05] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:05] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:05] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:05] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:06] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:06] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:06] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:06] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:06] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:03:06] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:06] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:06] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:06] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:06] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:06] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:06] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:06] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:07] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:07] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:07] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:07] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:07] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:03:07] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:07] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:07] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:07] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:07] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:07] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:07] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:07] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:08] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:08] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:08] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:08] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:08] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:03:08] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:08] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:08] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:08] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:08] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:08] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:08] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:08] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:10] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:10] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:10] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:10] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:10] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.09994666666666667.

[INFO 01-21 07:03:10] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:10] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:10] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:10] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:10] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:10] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:10] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:10] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:11] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:11] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:11] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:11] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:11] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:11] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:11] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:11] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:11] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:11] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:11] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:11] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:12] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:12] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:12] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:12] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:12] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:12] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:12] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:12] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:12] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:12] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:12] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:12] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:13] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:13] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:13] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:13] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:13] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:13] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:13] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:13] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:13] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:13] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:13] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:13] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:14] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:14] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:14] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:14] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:14] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:14] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:14] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:14] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:14] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:14] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:14] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:14] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:15] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:03:15] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:15] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:15] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:15] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:15] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:15] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:15] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:15] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:15] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.5999466666666666.

[INFO 01-21 07:03:15] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.953664
2    0.962683
3    0.941989
4    0.905204
5    0.941007
6    0.966297
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:03:15] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9662968516349792 is better than 70.0-th percentile (0.9581735730171204) across comparable trials.

[INFO 01-21 07:03:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:17] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:17] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:17] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:17] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:17] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:17] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:17] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:17] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:17] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:17] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:17] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:17] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:18] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:18] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:18] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:18] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:18] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:18] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:18] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:18] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:18] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:18] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:18] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:18] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:19] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:19] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:19] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:19] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:19] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:19] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:19] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:19] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:19] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:19] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:19] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:19] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:20] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:20] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:20] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:20] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:20] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:20] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:20] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:20] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:20] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:20] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:20] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:20] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:21] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:21] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:21] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:21] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:21] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:21] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:21] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:21] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:21] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:21] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:21] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:21] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:23] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:23] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:23] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:23] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:23] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:23] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:23] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:23] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:23] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:23] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:23] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:24] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:24] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:24] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:24] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:24] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:24] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:24] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:24] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:24] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:24] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:24] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:24] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:25] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:25] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:25] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:25] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:25] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:25] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:25] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:25] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:25] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:25] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:25] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:25] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:26] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:26] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:26] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:26] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:26] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:26] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:26] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:26] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:26] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:26] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:26] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:26] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:27] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:27] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:27] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:27] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:27] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:27] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:27] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:27] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:27] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:27] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:27] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:27] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:29] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:29] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:29] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:29] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:29] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:29] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:29] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:29] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:29] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:29] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:29] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:29] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:30] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:30] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:03:30] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:30] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:30] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:30] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:30] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.09994666666666667.

[INFO 01-21 07:03:30] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:30] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:30] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:30] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:30] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:31] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:31] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:31] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:31] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:31] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:31] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:31] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:31] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:31] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:31] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:31] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:32] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:32] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:32] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:32] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:32] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:32] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:32] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:32] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:32] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:32] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:32] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:33] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:33] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:33] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:33] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:33] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:33] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:33] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:33] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:33] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:33] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:33] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:35] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:35] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:35] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:35] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:35] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:35] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:35] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:35] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:35] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:35] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:35] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:36] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:36] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:36] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:36] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:36] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:36] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:36] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:36] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:36] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:36] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:36] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:37] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:37] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:37] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:37] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:37] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:37] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:37] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:37] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:37] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:37] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:37] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:38] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:38] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:38] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:38] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:38] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:38] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:38] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:38] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:38] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:38] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:38] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:39] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:39] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:39] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:39] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:39] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:39] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:39] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:39] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:39] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:39] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:39] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:40] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:41] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:41] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:41] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:41] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:41] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:41] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:41] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:41] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:41] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:41] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:42] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:42] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:42] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:42] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:42] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:42] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:42] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:42] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:42] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:42] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:42] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:43] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:43] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:43] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:43] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:43] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:43] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:43] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:43] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:43] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:43] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:43] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:44] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:44] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:44] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:44] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:44] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:44] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:44] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:44] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:44] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:44] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:44] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:45] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:45] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:45] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:45] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:45] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:45] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:45] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:45] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:45] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:45] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:45] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:46] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:46] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:47] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:47] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:47] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:47] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:47] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:47] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:47] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:47] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:47] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:48] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:48] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:48] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.19994666666666666.

[INFO 01-21 07:03:48] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:48] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:48] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:48] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:48] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:48] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:48] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:48] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:49] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:49] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:49] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:03:49] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:49] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:49] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:49] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:49] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:49] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:49] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:49] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:50] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.6999466666666667.

[INFO 01-21 07:03:50] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:50] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:03:50] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:50] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:50] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:50] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:50] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:50] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.6999466666666667.

[INFO 01-21 07:03:50] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.956219
2    0.962165
3    0.944895
4    0.908192
5    0.936562
6    0.963728
Name: 0.6999466666666667, dtype: float64.

[INFO 01-21 07:03:50] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9637275338172913 is better than 70.0-th percentile (0.9591919481754303) across comparable trials.

[INFO 01-21 07:03:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:51] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:03:51] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:51] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:03:51] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:51] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:51] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:51] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:51] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:51] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:03:51] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:03:51] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:03:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:52] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:03:52] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:52] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:03:52] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:52] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:52] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:52] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:52] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:52] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:03:52] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:03:52] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:03:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:54] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:03:54] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:54] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:03:54] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:54] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:54] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:54] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:54] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:54] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:03:54] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:03:54] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:03:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:55] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:03:55] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:55] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:03:55] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:55] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:55] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:55] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:55] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:55] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:03:55] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:03:55] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:03:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:56] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:03:56] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:56] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:03:56] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:56] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:56] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:56] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:56] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:56] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:03:56] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:03:56] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:03:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:57] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:03:57] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:57] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:03:57] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:57] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:57] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:57] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:57] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:57] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:03:57] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:03:57] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:03:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:03:58] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:03:58] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:03:58] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:03:58] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:58] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:03:58] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:03:58] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:03:58] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:03:58] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:03:58] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:03:58] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:03:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:00] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:00] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:00] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:00] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:00] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:00] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:04:00] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:00] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:00] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:00] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:00] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:01] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:01] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:01] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:01] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:01] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:01] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:04:01] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:01] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:01] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:01] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:01] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:02] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:02] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:02] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:02] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:02] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:02] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.19994666666666666.

[INFO 01-21 07:04:02] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:02] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:02] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:02] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:02] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:03] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:03] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:03] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:03] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:03] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:03] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:03] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:03] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:03] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:03] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:03] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:04] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:04] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:04] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:04] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:04] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:04] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:04] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:04] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:04] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:04] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:04] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:06] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:06] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:06] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:06] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:06] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:06] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:06] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:06] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:06] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:06] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:06] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:07] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:07] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:07] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:07] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:07] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:07] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:07] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:07] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:07] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:07] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:07] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:08] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:08] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:08] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:08] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:08] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:08] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:08] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:08] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:08] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:08] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:08] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:09] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:09] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:09] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:09] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:09] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:09] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:09] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:09] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:09] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:09] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:09] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:10] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:10] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:10] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:10] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:10] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:10] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:10] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:10] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:10] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:10] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:10] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:11] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:12] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:12] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:12] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:12] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:12] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:12] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:12] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:12] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:12] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:12] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:13] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:13] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:13] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:13] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:13] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:13] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:13] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:13] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:13] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:13] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:13] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:14] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:14] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:14] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:14] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:14] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:14] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:14] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:14] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:14] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:14] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:14] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:15] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:15] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:15] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:15] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:15] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:15] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:15] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:15] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:15] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:15] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:15] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:16] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:16] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:16] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:16] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:16] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:16] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:16] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:16] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:16] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:16] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:16] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:17] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:18] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:18] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:18] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:18] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:18] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:18] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:18] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:18] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:18] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:18] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:19] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:19] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:19] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:19] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:19] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:19] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:19] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:19] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:19] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:19] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:19] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:20] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:20] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:20] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:20] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:20] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:20] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:20] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:20] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:20] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:20] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:20] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:21] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:21] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:21] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:21] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:21] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:21] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:21] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:21] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:21] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:21] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:21] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:22] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:22] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:22] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:22] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:22] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:22] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:22] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:22] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:22] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:22] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:22] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:23] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:23] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:23] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:23] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:23] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:23] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:23] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:23] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:23] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:23] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:25] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.7999466666666667.

[INFO 01-21 07:04:25] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:25] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:25] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:25] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:25] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:25] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:25] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:25] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.7999466666666667.

[INFO 01-21 07:04:25] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.955744
2    0.962075
3    0.946112
4    0.909253
5    0.939264
6    0.967800
Name: 0.7999466666666667, dtype: float64.

[INFO 01-21 07:04:25] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9678003191947937 is better than 70.0-th percentile (0.9589094817638397) across comparable trials.

[INFO 01-21 07:04:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:26] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:26] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:26] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.29994666666666664.

[INFO 01-21 07:04:26] ax.early_stopping.strategies.base: Trial 9's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:26] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:26] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:26] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:26] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:26] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:26] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:26] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:27] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:27] ax.early_stopping.strategies.percentile: Considering trial 9 for early stopping.

[INFO 01-21 07:04:27] ax.early_stopping.strategies.base: Last progression of Trial 9 is 0.3999466666666667.

[INFO 01-21 07:04:27] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.943242
2    0.959307
3    0.935194
4    0.898628
5    0.932184
6    0.964392
7    0.960921
8    0.932884
9    0.953034
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:04:27] ax.early_stopping.strategies.percentile: Early stopping decision for 9: True. Reason: Trial objective value 0.9530338048934937 is worse than 70.0-th percentile (0.9567976951599121) across comparable trials.

[INFO 01-21 07:04:27] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:27] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:27] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:27] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:27] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:27] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:27] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 01-21 07:04:30] Scheduler: Running trials [11]...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:31] Scheduler: Generated all trials that can be generated currently. Max parallelism currently reached.

[INFO 01-21 07:04:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04e50>")

[ERROR 01-21 07:04:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04e50>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:31] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04e50>").

[INFO 01-21 07:04:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:31] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:31] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:31] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:31] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:31] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:31] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:31] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:31] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:31] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:31] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0670>")

[ERROR 01-21 07:04:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0670>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:32] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0670>").

[INFO 01-21 07:04:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:32] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:32] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:32] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:32] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:32] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:32] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:32] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:32] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:32] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:32] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fa0e0>")

[ERROR 01-21 07:04:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fa0e0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:33] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fa0e0>").

[INFO 01-21 07:04:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:34] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:34] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:34] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:34] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:34] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:34] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:34] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:34] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:34] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:34] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9540>")

[ERROR 01-21 07:04:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9540>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:35] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d9540>").

[INFO 01-21 07:04:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:35] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:35] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:35] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.29994666666666664.

[INFO 01-21 07:04:35] ax.early_stopping.strategies.base: Trial 10's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:04:35] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:35] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:35] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:35] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:35] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:35] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64580>")

[ERROR 01-21 07:04:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64580>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:36] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddcf64580>").

[INFO 01-21 07:04:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:36] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:36] ax.early_stopping.strategies.percentile: Considering trial 10 for early stopping.

[INFO 01-21 07:04:36] ax.early_stopping.strategies.base: Last progression of Trial 10 is 0.3999466666666667.

[INFO 01-21 07:04:36] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:04:36] ax.early_stopping.strategies.percentile: Early stopping decision for 10: True. Reason: Trial objective value 0.9524292945861816 is worse than 70.0-th percentile (0.9549157500267029) across comparable trials.

[INFO 01-21 07:04:36] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:36] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:36] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:36] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:36] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:36] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 01-21 07:04:40] Scheduler: Running trials [12]...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:41] Scheduler: Generated all trials that can be generated currently. Max parallelism currently reached.

[INFO 01-21 07:04:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3840400>")

[INFO 01-21 07:04:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>")

[ERROR 01-21 07:04:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3840400>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:41] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3840400>").

[INFO 01-21 07:04:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:41] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>").

[INFO 01-21 07:04:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:41] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:41] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:41] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:41] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:41] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:41] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:41] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:41] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:41] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:42] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3840400>")

[INFO 01-21 07:04:42] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8fd0>")

[ERROR 01-21 07:04:42] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3840400>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:42] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8fd0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:42] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3840400>").

[INFO 01-21 07:04:42] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:42] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8fd0>").

[INFO 01-21 07:04:42] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:42] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:42] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:42] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:42] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:42] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:42] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:42] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:42] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:42] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05090>")

[INFO 01-21 07:04:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd068c0>")

[ERROR 01-21 07:04:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05090>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd068c0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:43] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05090>").

[INFO 01-21 07:04:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:43] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd068c0>").

[INFO 01-21 07:04:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:43] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:43] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:43] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:43] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:43] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:43] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:43] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:43] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:43] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:44] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f84c0>")

[INFO 01-21 07:04:44] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8610>")

[ERROR 01-21 07:04:44] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f84c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:44] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8610>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:44] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f84c0>").

[INFO 01-21 07:04:44] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:44] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8610>").

[INFO 01-21 07:04:44] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:44] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:44] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:44] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:44] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:44] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:44] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:44] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:44] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:44] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fb130>")

[INFO 01-21 07:04:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fb130>")

[ERROR 01-21 07:04:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fb130>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fb130>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:45] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fb130>").

[INFO 01-21 07:04:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:45] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fb130>").

[INFO 01-21 07:04:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:45] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:45] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:45] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:45] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:45] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:45] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:45] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:45] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:45] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>")

[INFO 01-21 07:04:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>")

[ERROR 01-21 07:04:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:46] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>").

[INFO 01-21 07:04:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:46] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>").

[INFO 01-21 07:04:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:47] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:47] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:47] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:47] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:47] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:47] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:47] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:47] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:47] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8fd0>")

[INFO 01-21 07:04:48] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>")

[ERROR 01-21 07:04:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8fd0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:48] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:48] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8fd0>").

[INFO 01-21 07:04:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:48] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>").

[INFO 01-21 07:04:48] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:48] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:48] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:48] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:48] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:48] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:48] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:48] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:48] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:48] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:49] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8610>")

[INFO 01-21 07:04:49] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8610>")

[ERROR 01-21 07:04:49] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8610>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:49] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8610>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:49] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8610>").

[INFO 01-21 07:04:49] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:49] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8610>").

[INFO 01-21 07:04:49] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:49] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:49] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:49] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:49] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:49] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:49] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:49] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:49] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:49] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:50] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>")

[INFO 01-21 07:04:50] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd048b0>")

[ERROR 01-21 07:04:50] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:50] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd048b0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:50] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>").

[INFO 01-21 07:04:50] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:50] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd048b0>").

[INFO 01-21 07:04:50] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:50] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:50] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:50] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:50] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:50] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:50] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:50] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:50] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:50] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:51] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388c7f0>")

[INFO 01-21 07:04:51] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388c7f0>")

[ERROR 01-21 07:04:51] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388c7f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:51] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388c7f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:51] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388c7f0>").

[INFO 01-21 07:04:51] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:51] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388c7f0>").

[INFO 01-21 07:04:51] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:51] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:51] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:51] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:51] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:51] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:51] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:51] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:51] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:51] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd37954e0>")

[INFO 01-21 07:04:52] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd37954e0>")

[ERROR 01-21 07:04:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd37954e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:52] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd37954e0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:52] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd37954e0>").

[INFO 01-21 07:04:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:52] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd37954e0>").

[INFO 01-21 07:04:52] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:52] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:52] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:52] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:52] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:52] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:52] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:52] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:52] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:52] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:53] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>")

[INFO 01-21 07:04:53] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>")

[ERROR 01-21 07:04:53] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:53] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:53] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>").

[INFO 01-21 07:04:53] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:53] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>").

[INFO 01-21 07:04:53] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:54] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:54] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:54] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:54] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:54] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:54] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:54] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:54] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:54] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:55] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8c10>")

[INFO 01-21 07:04:55] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8c10>")

[ERROR 01-21 07:04:55] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8c10>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:55] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8c10>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:55] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8c10>").

[INFO 01-21 07:04:55] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:55] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8c10>").

[INFO 01-21 07:04:55] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:55] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:55] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:55] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:55] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:55] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:55] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:55] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:55] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:55] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:56] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388ff40>")

[INFO 01-21 07:04:56] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8c10>")

[ERROR 01-21 07:04:56] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388ff40>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:56] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8c10>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:56] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388ff40>").

[INFO 01-21 07:04:56] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:56] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8c10>").

[INFO 01-21 07:04:56] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:56] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:56] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:56] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:56] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:56] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:56] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:56] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:56] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:56] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>")

[INFO 01-21 07:04:57] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>")

[ERROR 01-21 07:04:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:57] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:57] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>").

[INFO 01-21 07:04:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:57] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38d87c0>").

[INFO 01-21 07:04:57] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:57] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.8999466666666667.

[INFO 01-21 07:04:57] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:57] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:57] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:57] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:57] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:57] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.8999466666666667.

[INFO 01-21 07:04:57] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.960212
2    0.959158
3    0.949249
4    0.907861
5    0.941487
6    0.964573
Name: 0.8999466666666667, dtype: float64.

[INFO 01-21 07:04:57] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9645726680755615 is better than 70.0-th percentile (0.9596847295761108) across comparable trials.

[INFO 01-21 07:04:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:58] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f84f0>")

[INFO 01-21 07:04:58] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f84f0>")

[ERROR 01-21 07:04:58] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f84f0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:58] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f84f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:58] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f84f0>").

[INFO 01-21 07:04:58] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:58] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f84f0>").

[INFO 01-21 07:04:58] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:58] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.9999466666666667.

[INFO 01-21 07:04:58] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:58] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:58] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:58] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:58] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:58] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.9999466666666667.

[INFO 01-21 07:04:58] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.959721
2    0.962203
3    0.948714
4    0.911162
5    0.927991
6    0.966897
Name: 0.9999466666666667, dtype: float64.

[INFO 01-21 07:04:58] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9668969511985779 is better than 70.0-th percentile (0.9609618782997131) across comparable trials.

[INFO 01-21 07:04:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:04:59] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38406a0>")

[INFO 01-21 07:04:59] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38406a0>")

[ERROR 01-21 07:04:59] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38406a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:04:59] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38406a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:04:59] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38406a0>").

[INFO 01-21 07:04:59] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:04:59] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38406a0>").

[INFO 01-21 07:04:59] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:04:59] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.9999466666666667.

[INFO 01-21 07:04:59] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:04:59] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:59] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:04:59] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:04:59] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:04:59] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.9999466666666667.

[INFO 01-21 07:04:59] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.959721
2    0.962203
3    0.948714
4    0.911162
5    0.927991
6    0.966897
Name: 0.9999466666666667, dtype: float64.

[INFO 01-21 07:04:59] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9668969511985779 is better than 70.0-th percentile (0.9609618782997131) across comparable trials.

[INFO 01-21 07:04:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:00] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>")

[INFO 01-21 07:05:00] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>")

[ERROR 01-21 07:05:00] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:00] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:00] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>").

[INFO 01-21 07:05:00] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:00] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>").

[INFO 01-21 07:05:00] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:00] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.9999466666666667.

[INFO 01-21 07:05:00] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:05:00] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:05:00] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:05:00] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:05:00] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:05:00] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.9999466666666667.

[INFO 01-21 07:05:00] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.959721
2    0.962203
3    0.948714
4    0.911162
5    0.927991
6    0.966897
Name: 0.9999466666666667, dtype: float64.

[INFO 01-21 07:05:00] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9668969511985779 is better than 70.0-th percentile (0.9609618782997131) across comparable trials.

[INFO 01-21 07:05:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:01] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8610>")

[INFO 01-21 07:05:01] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f85b0>")

[ERROR 01-21 07:05:02] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8610>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:02] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f85b0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:02] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f8610>").

[INFO 01-21 07:05:02] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:02] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f85b0>").

[INFO 01-21 07:05:02] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:02] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.9999466666666667.

[INFO 01-21 07:05:02] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:05:02] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:05:02] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:05:02] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:05:02] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:05:02] ax.early_stopping.strategies.base: Last progression of Trial 6 is 0.9999466666666667.

[INFO 01-21 07:05:02] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.959721
2    0.962203
3    0.948714
4    0.911162
5    0.927991
6    0.966897
Name: 0.9999466666666667, dtype: float64.

[INFO 01-21 07:05:02] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9668969511985779 is better than 70.0-th percentile (0.9609618782997131) across comparable trials.

[INFO 01-21 07:05:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:03] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>")

[INFO 01-21 07:05:03] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>")

[ERROR 01-21 07:05:03] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:03] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:03] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>").

[INFO 01-21 07:05:03] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:03] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd067a0>").

[INFO 01-21 07:05:03] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:03] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 1.0.

[INFO 01-21 07:05:03] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:05:03] ax.early_stopping.strategies.base: There is not yet any data associated with trial 11 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:05:03] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:05:03] ax.early_stopping.strategies.base: There is not yet any data associated with trial 12 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:05:03] ax.early_stopping.strategies.percentile: Considering trial 6 for early stopping.

[INFO 01-21 07:05:03] ax.early_stopping.strategies.base: Last progression of Trial 6 is 1.0.

[INFO 01-21 07:05:03] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1    0.959721
2    0.962203
3    0.948714
4    0.911162
5    0.927991
6    0.966897
Name: 1.0, dtype: float64.

[INFO 01-21 07:05:03] ax.early_stopping.strategies.percentile: Early stopping decision for 6: False. Reason: Trial objective value 0.9668969511985779 is better than 70.0-th percentile (0.9609618782997131) across comparable trials.

[INFO 01-21 07:05:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:04] Scheduler: Retrieved COMPLETED trials: [6].

[INFO 01-21 07:05:04] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05870>")

[INFO 01-21 07:05:04] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04700>")

[ERROR 01-21 07:05:04] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05870>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:04] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04700>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:04] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05870>").

[INFO 01-21 07:05:04] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:04] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04700>").

[INFO 01-21 07:05:04] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:04] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 07:05:04] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 01-21 07:05:06] Scheduler: Running trials [13]...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:08] Scheduler: Generated all trials that can be generated currently. Max parallelism currently reached.

[INFO 01-21 07:05:08] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>")

[INFO 01-21 07:05:08] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>")

[INFO 01-21 07:05:08] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>")

[ERROR 01-21 07:05:08] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:08] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:08] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 07:05:08] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>").

[INFO 01-21 07:05:08] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:08] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>").

[INFO 01-21 07:05:08] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:08] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>").

[INFO 01-21 07:05:08] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:08] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 07:05:08] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:09] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dddc58040>")

[INFO 01-21 07:05:09] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd047c0>")

[INFO 01-21 07:05:09] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dddc58040>")

[ERROR 01-21 07:05:09] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dddc58040>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:09] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd047c0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:09] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dddc58040>"). Ignoring for now -- will retry query on next call to fetch.

[WARNING 01-21 07:05:09] Scheduler: Failed to fetch val_acc for trial 11, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dddc58040>").

[INFO 01-21 07:05:09] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 11 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:09] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd047c0>").

[INFO 01-21 07:05:09] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:09] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dddc58040>").

[INFO 01-21 07:05:09] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:09] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.

[INFO 01-21 07:05:09] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:10] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd058a0>")

[INFO 01-21 07:05:10] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd06e60>")

[ERROR 01-21 07:05:10] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd058a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:10] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd06e60>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:10] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd058a0>").

[INFO 01-21 07:05:10] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:10] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd06e60>").

[INFO 01-21 07:05:10] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:10] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:10] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:11] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3460>")

[INFO 01-21 07:05:11] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0be0>")

[ERROR 01-21 07:05:11] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3460>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:11] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0be0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:11] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3460>").

[INFO 01-21 07:05:11] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:11] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0be0>").

[INFO 01-21 07:05:11] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:11] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:11] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388dbd0>")

[INFO 01-21 07:05:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0be0>")

[ERROR 01-21 07:05:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388dbd0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0be0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:12] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388dbd0>").

[INFO 01-21 07:05:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:12] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0be0>").

[INFO 01-21 07:05:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:12] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:12] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388fe50>")

[INFO 01-21 07:05:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388fe50>")

[ERROR 01-21 07:05:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388fe50>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388fe50>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:13] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388fe50>").

[INFO 01-21 07:05:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:13] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388fe50>").

[INFO 01-21 07:05:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:13] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:13] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f82e0>")

[INFO 01-21 07:05:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f82e0>")

[ERROR 01-21 07:05:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f82e0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f82e0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:14] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f82e0>").

[INFO 01-21 07:05:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:14] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38f82e0>").

[INFO 01-21 07:05:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:14] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:14] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>")

[INFO 01-21 07:05:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07340>")

[ERROR 01-21 07:05:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07340>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:15] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>").

[INFO 01-21 07:05:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:15] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07340>").

[INFO 01-21 07:05:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:15] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:15] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd064a0>")

[INFO 01-21 07:05:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd064a0>")

[ERROR 01-21 07:05:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd064a0>"). Ignoring for now -- will retry query on next call to fetch.

[ERROR 01-21 07:05:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd064a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:16] Scheduler: Failed to fetch val_acc for trial 12, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd064a0>").

[INFO 01-21 07:05:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 12 is still RUNNING continuing the experiment and retrying on next poll...

[WARNING 01-21 07:05:16] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd064a0>").

[INFO 01-21 07:05:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:16] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:16] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:17] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1240>")

[ERROR 01-21 07:05:17] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1240>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:17] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1240>").

[INFO 01-21 07:05:17] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:17] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:17] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:18] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>")

[ERROR 01-21 07:05:18] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:18] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>").

[INFO 01-21 07:05:18] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:19] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:19] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388dbd0>")

[ERROR 01-21 07:05:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388dbd0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:20] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd388dbd0>").

[INFO 01-21 07:05:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:20] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:20] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1a50>")

[ERROR 01-21 07:05:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1a50>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:21] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1a50>").

[INFO 01-21 07:05:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:21] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:21] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05f30>")

[ERROR 01-21 07:05:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05f30>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:22] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05f30>").

[INFO 01-21 07:05:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:22] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:22] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>")

[ERROR 01-21 07:05:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:23] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>").

[INFO 01-21 07:05:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:23] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:24] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3850>")

[ERROR 01-21 07:05:24] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3850>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:24] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3850>").

[INFO 01-21 07:05:24] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:24] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:24] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fb340>")

[ERROR 01-21 07:05:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fb340>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:25] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38fb340>").

[INFO 01-21 07:05:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:25] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:25] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04e20>")

[ERROR 01-21 07:05:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04e20>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:26] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04e20>").

[INFO 01-21 07:05:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:26] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:26] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07340>")

[ERROR 01-21 07:05:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07340>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:27] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd07340>").

[INFO 01-21 07:05:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:27] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:27] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0be0>")

[ERROR 01-21 07:05:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0be0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:29] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0be0>").

[INFO 01-21 07:05:29] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:29] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:29] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>")

[ERROR 01-21 07:05:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:30] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>").

[INFO 01-21 07:05:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:30] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:30] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:31] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2050>")

[ERROR 01-21 07:05:31] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2050>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:31] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2050>").

[INFO 01-21 07:05:31] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:31] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:31] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2050>")

[ERROR 01-21 07:05:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2050>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:32] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2050>").

[INFO 01-21 07:05:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:32] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:32] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2530>")

[ERROR 01-21 07:05:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2530>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:33] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2530>").

[INFO 01-21 07:05:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:33] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:33] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0b50>")

[ERROR 01-21 07:05:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0b50>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:34] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0b50>").

[INFO 01-21 07:05:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:34] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:34] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2530>")

[ERROR 01-21 07:05:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2530>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:35] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2530>").

[INFO 01-21 07:05:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:35] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:35] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c90>")

[ERROR 01-21 07:05:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c90>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:36] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c90>").

[INFO 01-21 07:05:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:36] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:36] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04e20>")

[ERROR 01-21 07:05:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04e20>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:37] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04e20>").

[INFO 01-21 07:05:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:37] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:37] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>")

[ERROR 01-21 07:05:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:38] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04df0>").

[INFO 01-21 07:05:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:39] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:39] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:40] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd064a0>")

[ERROR 01-21 07:05:40] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd064a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:40] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd064a0>").

[INFO 01-21 07:05:40] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:40] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:40] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:41] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3460>")

[ERROR 01-21 07:05:41] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3460>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:41] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3460>").

[INFO 01-21 07:05:41] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:41] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:41] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:42] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04700>")

[ERROR 01-21 07:05:42] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04700>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:42] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd04700>").

[INFO 01-21 07:05:42] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:42] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:42] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:43] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>")

[ERROR 01-21 07:05:43] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:43] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>").

[INFO 01-21 07:05:43] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:43] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.09994666666666667.

[INFO 01-21 07:05:43] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:44] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>")

[ERROR 01-21 07:05:44] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:44] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c3100>").

[INFO 01-21 07:05:44] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:44] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:44] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:45] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>")

[ERROR 01-21 07:05:45] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:45] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>").

[INFO 01-21 07:05:45] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:45] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:45] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:05:46] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c28c0>")

[ERROR 01-21 07:05:46] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c28c0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:05:46] Scheduler: Failed to fetch val_acc for trial 13, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c28c0>").

[INFO 01-21 07:05:46] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 13 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:46] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:46] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:47] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:47] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:49] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:49] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:50] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:50] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:51] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:51] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:52] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:52] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:53] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:53] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:54] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:54] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:55] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:55] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:56] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:56] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:57] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:57] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:05:59] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:05:59] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:05:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:00] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:00] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:01] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:01] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:02] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:02] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:03] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:03] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:04] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:04] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:05] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:05] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:06] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:06] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:07] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:07] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:09] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:09] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:09] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:10] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:10] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:11] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:11] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:12] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:12] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:13] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:13] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:14] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:14] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:15] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:15] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:16] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:16] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:18] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:18] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:19] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:06:19] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:20] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:20] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:21] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:21] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:22] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:22] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:23] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:24] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:24] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:25] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:25] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:26] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:26] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:28] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:28] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:29] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:29] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:30] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:30] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:31] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:31] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:32] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:32] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:33] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:33] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:34] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:34] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:35] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:35] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:36] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:36] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:38] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:38] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:39] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:39] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:40] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:40] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:40] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:41] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:41] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:42] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:42] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:43] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:43] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:44] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:44] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:45] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:45] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:46] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:46] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:48] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:48] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:49] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:49] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:50] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:50] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:50] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:51] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:51] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:52] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:52] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:53] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:53] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:54] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:54] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:55] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:06:55] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:06:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:57] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:06:57] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:06:57] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:06:57] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:06:57] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9538589119911194) across comparable trials.

[INFO 01-21 07:06:57] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:06:57] ax.early_stopping.strategies.base: Last progression of Trial 12 is 0.29994666666666664.

[INFO 01-21 07:06:57] ax.early_stopping.strategies.base: Trial 12's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:06:57] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:06:57] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.19994666666666666.

[INFO 01-21 07:06:57] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:06:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:58] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:06:58] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:06:58] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:06:58] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:06:58] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9538589119911194) across comparable trials.

[INFO 01-21 07:06:58] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:06:58] ax.early_stopping.strategies.base: Last progression of Trial 12 is 0.29994666666666664.

[INFO 01-21 07:06:58] ax.early_stopping.strategies.base: Trial 12's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:06:58] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:06:58] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:06:58] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:06:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:06:59] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:06:59] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:06:59] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:06:59] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:06:59] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9538589119911194) across comparable trials.

[INFO 01-21 07:06:59] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:06:59] ax.early_stopping.strategies.base: Last progression of Trial 12 is 0.29994666666666664.

[INFO 01-21 07:06:59] ax.early_stopping.strategies.base: Trial 12's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:06:59] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:06:59] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:06:59] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:06:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:00] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:00] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:00] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:00] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:00] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9538589119911194) across comparable trials.

[INFO 01-21 07:07:00] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:07:00] ax.early_stopping.strategies.base: Last progression of Trial 12 is 0.29994666666666664.

[INFO 01-21 07:07:00] ax.early_stopping.strategies.base: Trial 12's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:00] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:00] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:00] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:00] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:01] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:01] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:01] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:01] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:01] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9538589119911194) across comparable trials.

[INFO 01-21 07:07:01] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:07:01] ax.early_stopping.strategies.base: Last progression of Trial 12 is 0.29994666666666664.

[INFO 01-21 07:07:01] ax.early_stopping.strategies.base: Trial 12's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:01] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:01] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:01] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:02] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:02] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:02] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:02] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:02] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9538589119911194) across comparable trials.

[INFO 01-21 07:07:02] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:07:02] ax.early_stopping.strategies.base: Last progression of Trial 12 is 0.29994666666666664.

[INFO 01-21 07:07:02] ax.early_stopping.strategies.base: Trial 12's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:02] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:02] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:02] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:04] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:04] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:04] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:04] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:04] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:04] ax.early_stopping.strategies.percentile: Considering trial 12 for early stopping.

[INFO 01-21 07:07:04] ax.early_stopping.strategies.base: Last progression of Trial 12 is 0.3999466666666667.

[INFO 01-21 07:07:04] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:04] ax.early_stopping.strategies.percentile: Early stopping decision for 12: True. Reason: Trial objective value 0.9450400471687317 is worse than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:04] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:04] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:04] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

[INFO 01-21 07:07:07] Scheduler: Running trials [14]...

[INFO 01-21 07:07:08] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1e10>")

[ERROR 01-21 07:07:08] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1e10>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:08] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1e10>").

[INFO 01-21 07:07:08] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:08] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:08] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:08] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:08] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:08] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:08] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:08] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:08] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:08] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:08] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:09] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c90>")

[ERROR 01-21 07:07:09] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c90>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:09] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c90>").

[INFO 01-21 07:07:09] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:09] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:09] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:09] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:10] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:10] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:10] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:10] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:10] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:10] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:10] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:11] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c30>")

[ERROR 01-21 07:07:11] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c30>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:11] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c30>").

[INFO 01-21 07:07:11] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:11] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:11] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:11] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:11] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:11] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:11] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:11] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:11] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:11] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:11] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:12] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3794ac0>")

[ERROR 01-21 07:07:12] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3794ac0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:12] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3794ac0>").

[INFO 01-21 07:07:12] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:12] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:12] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:12] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:12] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:12] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:12] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:12] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:12] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:12] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:12] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:13] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1300>")

[ERROR 01-21 07:07:13] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1300>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:13] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1300>").

[INFO 01-21 07:07:13] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:13] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:13] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:13] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:13] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:13] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:13] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:13] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:13] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:13] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:13] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:14] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c14b0>")

[ERROR 01-21 07:07:14] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c14b0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:14] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c14b0>").

[INFO 01-21 07:07:14] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:14] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:14] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:14] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:14] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:14] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:14] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:14] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:14] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:14] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:14] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:15] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd058a0>")

[ERROR 01-21 07:07:15] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd058a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:15] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd058a0>").

[INFO 01-21 07:07:15] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:15] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:15] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:15] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:15] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:15] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:15] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:15] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:15] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:15] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:15] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:15] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:16] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0b50>")

[ERROR 01-21 07:07:16] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0b50>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:16] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c0b50>").

[INFO 01-21 07:07:16] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:16] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:16] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:16] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:16] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:16] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:16] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:16] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:16] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:16] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:16] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:18] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1e10>")

[ERROR 01-21 07:07:18] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1e10>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:18] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1e10>").

[INFO 01-21 07:07:18] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:18] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:18] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:18] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:18] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:18] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:18] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:18] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:18] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:18] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:18] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:19] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c30>")

[ERROR 01-21 07:07:19] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c30>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:19] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c30>").

[INFO 01-21 07:07:19] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:19] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:19] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:19] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:19] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:19] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:19] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:19] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:19] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:19] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:19] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:20] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1300>")

[ERROR 01-21 07:07:20] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1300>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:20] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1300>").

[INFO 01-21 07:07:20] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:20] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:20] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:20] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:20] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:20] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:20] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:20] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:20] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:20] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:20] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:21] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1240>")

[ERROR 01-21 07:07:21] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1240>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:21] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1240>").

[INFO 01-21 07:07:21] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:21] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:21] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:21] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:21] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:21] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:21] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:21] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:21] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:21] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:21] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:22] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c19c0>")

[ERROR 01-21 07:07:22] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c19c0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:22] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c19c0>").

[INFO 01-21 07:07:22] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:22] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:22] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:22] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:22] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:22] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:22] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:22] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:22] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:22] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:22] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:23] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c30>")

[ERROR 01-21 07:07:23] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c30>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:23] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1c30>").

[INFO 01-21 07:07:23] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:23] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:23] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:23] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:23] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:23] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:23] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:23] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:23] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:24] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:25] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1180>")

[ERROR 01-21 07:07:25] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1180>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:25] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1180>").

[INFO 01-21 07:07:25] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:25] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:25] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:25] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:25] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:25] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:25] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:25] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:25] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:25] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:25] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:26] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05f30>")

[ERROR 01-21 07:07:26] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05f30>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:26] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05f30>").

[INFO 01-21 07:07:26] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:26] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:26] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:26] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:26] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:26] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:26] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:26] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:26] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:26] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:26] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:27] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>")

[ERROR 01-21 07:07:27] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:27] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd057e0>").

[INFO 01-21 07:07:27] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:27] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:27] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:27] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.3999466666666667.

[INFO 01-21 07:07:27] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:27] ax.early_stopping.strategies.percentile: Early stopping decision for 11: False. Reason: Trial objective value 0.9538589119911194 is better than 70.0-th percentile (0.9536113798618316) across comparable trials.

[INFO 01-21 07:07:27] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:27] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:27] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:27] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:27] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:27] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 3).

[INFO 01-21 07:07:28] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1300>")

[ERROR 01-21 07:07:28] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1300>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:28] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1300>").

[INFO 01-21 07:07:28] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:28] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:07:28] ax.early_stopping.strategies.percentile: Considering trial 11 for early stopping.

[INFO 01-21 07:07:28] ax.early_stopping.strategies.base: Last progression of Trial 11 is 0.49994666666666665.

[INFO 01-21 07:07:28] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:07:28] ax.early_stopping.strategies.percentile: Early stopping decision for 11: True. Reason: Trial objective value 0.9570269584655762 is worse than 70.0-th percentile (0.9588446378707886) across comparable trials.

[INFO 01-21 07:07:28] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:28] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.29994666666666664.

[INFO 01-21 07:07:28] ax.early_stopping.strategies.base: Trial 13's most recent progression (0.29994666666666664) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:28] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:28] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:29] Scheduler: Done submitting trials, waiting for remaining 2 running trials...

[INFO 01-21 07:07:29] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3795ae0>")

[ERROR 01-21 07:07:29] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3795ae0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:29] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd3795ae0>").

[INFO 01-21 07:07:29] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:29] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:07:29] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:07:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

[INFO 01-21 07:07:30] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>")

[ERROR 01-21 07:07:30] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:30] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>").

[INFO 01-21 07:07:30] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:31] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:07:31] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:07:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

[INFO 01-21 07:07:32] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>")

[ERROR 01-21 07:07:32] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:32] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c2f20>").

[INFO 01-21 07:07:32] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:32] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:32] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:32] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:32] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:32] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:32] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:32] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

[INFO 01-21 07:07:33] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1720>")

[ERROR 01-21 07:07:33] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1720>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:33] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1720>").

[INFO 01-21 07:07:33] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:33] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:33] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:33] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:33] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:33] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:33] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:33] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

[INFO 01-21 07:07:34] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c14b0>")

[ERROR 01-21 07:07:34] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c14b0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:34] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c14b0>").

[INFO 01-21 07:07:34] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:34] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:34] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:34] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:34] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:34] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:34] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:34] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

[INFO 01-21 07:07:35] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c19c0>")

[ERROR 01-21 07:07:35] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c19c0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:35] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c19c0>").

[INFO 01-21 07:07:35] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:35] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:35] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:35] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:35] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:35] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:35] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:35] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

[INFO 01-21 07:07:36] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>")

[ERROR 01-21 07:07:36] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:36] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c07f0>").

[INFO 01-21 07:07:36] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:36] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:36] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:36] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:36] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:36] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:36] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:36] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

[INFO 01-21 07:07:37] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1e10>")

[ERROR 01-21 07:07:37] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1e10>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:37] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2dd38c1e10>").

[INFO 01-21 07:07:37] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:37] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:37] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:37] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:37] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:37] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:37] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:37] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:37] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

[INFO 01-21 07:07:38] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05e10>")

[ERROR 01-21 07:07:38] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05e10>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:38] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd05e10>").

[INFO 01-21 07:07:38] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:38] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:38] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:38] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:38] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:38] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:38] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:38] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:38] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

[INFO 01-21 07:07:39] ax.core.metric: MetricFetchE INFO: Initialized MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd058a0>")

[ERROR 01-21 07:07:39] ax.core.experiment: Discovered Metric fetching Err while attaching data MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd058a0>"). Ignoring for now -- will retry query on next call to fetch.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[WARNING 01-21 07:07:39] Scheduler: Failed to fetch val_acc for trial 14, found MetricFetchE(message="No 'scalar' data found for trial in multiplexer mul=<tensorboard.backend.event_processing.plugin_event_multiplexer.EventMultiplexer object at 0x7f2ddbd058a0>").

[INFO 01-21 07:07:39] Scheduler: MetricFetchE INFO: Because val_acc is available_while_running and trial 14 is still RUNNING continuing the experiment and retrying on next poll...

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:39] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:39] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:39] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:39] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:39] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:39] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:39] ax.early_stopping.strategies.base: There is not yet any data associated with trial 14 and metric val_acc. Not early stopping this trial.

[INFO 01-21 07:07:39] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:40] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:41] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:41] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:41] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:41] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:41] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:41] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:41] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:41] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:41] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:42] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:42] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:42] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:42] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:42] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:42] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:42] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:42] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:42] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:42] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:43] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:43] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:43] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:43] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:43] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:43] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:43] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:43] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:43] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:43] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:44] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:44] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:44] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:44] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:44] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:44] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:44] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:44] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:44] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:44] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:45] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:45] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:45] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:45] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:45] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:45] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:45] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:45] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:45] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:45] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:46] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:46] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:46] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:46] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:46] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:46] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:46] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:46] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:46] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:46] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:47] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:47] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:47] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:47] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:47] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:47] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:47] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:47] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:47] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:47] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:48] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:48] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:48] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:48] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:48] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:48] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:48] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:48] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:48] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:48] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:49] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:49] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:49] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:49] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:49] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:49] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:49] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:49] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:49] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:49] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:51] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:51] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:51] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:51] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:51] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:51] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:51] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:51] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:51] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:51] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:52] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:52] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:52] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:52] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:52] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:52] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:52] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:52] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:52] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:52] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:53] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:53] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:53] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:53] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:53] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:53] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:53] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:53] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:53] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:53] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:54] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:07:54] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:54] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:54] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.3999466666666667.

[INFO 01-21 07:07:54] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:07:54] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.959662914276123 is better than 70.0-th percentile (0.9560381293296814) across comparable trials.

[INFO 01-21 07:07:54] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:54] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:54] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:54] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:55] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:07:55] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:55] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:55] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:07:55] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:07:55] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:07:55] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:55] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:55] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:55] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:56] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:07:56] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:56] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:56] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:07:56] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:07:56] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:07:56] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:56] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:56] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:56] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:57] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:07:57] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:57] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:57] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:07:57] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:07:57] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:07:57] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:57] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:57] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:57] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:58] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:07:58] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:58] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:58] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:07:58] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:07:58] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:07:58] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:58] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:58] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:58] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:07:59] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:07:59] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:07:59] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:07:59] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:07:59] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:07:59] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:07:59] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:07:59] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:07:59] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:07:59] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:01] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:01] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:08:01] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:01] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:01] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:01] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:01] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:01] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:08:01] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:01] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:02] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:02] ax.early_stopping.utils: Got exception `x and y arrays must have at least 2 entries` during interpolation. Using uninterpolated values instead.

[INFO 01-21 07:08:02] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:02] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:02] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:02] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:02] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:02] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.09994666666666667.

[INFO 01-21 07:08:02] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.09994666666666667) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:02] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:03] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:03] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:03] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:03] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:03] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:03] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:03] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 01-21 07:08:03] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:03] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:04] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:04] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:04] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:04] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:04] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:04] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:04] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 01-21 07:08:04] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:04] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:05] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:05] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:05] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:05] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:05] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:05] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:05] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 01-21 07:08:05] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:05] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:06] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:06] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:06] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:06] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:06] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:06] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:06] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 01-21 07:08:06] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:06] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:07] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:07] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:07] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:07] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:07] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:07] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:07] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 01-21 07:08:07] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:07] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:08] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:08] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:08] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:08] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:08] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:08] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:08] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 01-21 07:08:08] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:08] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:10] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:10] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:10] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:10] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:10] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:10] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:10] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 01-21 07:08:10] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:10] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:11] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:11] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:11] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:11] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:11] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:11] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:11] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 01-21 07:08:11] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:11] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:12] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:12] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:12] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:12] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:12] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:12] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:12] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 01-21 07:08:12] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:12] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:13] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:13] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:13] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:13] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:13] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:13] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:13] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 01-21 07:08:13] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:13] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:14] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.49994666666666665.

[INFO 01-21 07:08:14] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:14] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.49994666666666665.

[INFO 01-21 07:08:14] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.950077
2     0.960604
3     0.939967
4     0.904845
5     0.934662
6     0.967661
7     0.959047
11    0.957027
13    0.961630
Name: 0.49994666666666665, dtype: float64.

[INFO 01-21 07:08:14] ax.early_stopping.strategies.percentile: Early stopping decision for 13: False. Reason: Trial objective value 0.9616298675537109 is better than 70.0-th percentile (0.9599807620048523) across comparable trials.

[INFO 01-21 07:08:14] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:14] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 01-21 07:08:14] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

[INFO 01-21 07:08:14] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 2).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:15] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.5999466666666666.

[INFO 01-21 07:08:15] ax.early_stopping.strategies.percentile: Considering trial 13 for early stopping.

[INFO 01-21 07:08:15] ax.early_stopping.strategies.base: Last progression of Trial 13 is 0.5999466666666666.

[INFO 01-21 07:08:15] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.953664
2     0.962683
3     0.941989
4     0.905204
5     0.941007
6     0.966297
13    0.961808
Name: 0.5999466666666666, dtype: float64.

[INFO 01-21 07:08:15] ax.early_stopping.strategies.percentile: Early stopping decision for 13: True. Reason: Trial objective value 0.9618080258369446 is worse than 70.0-th percentile (0.961983036994934) across comparable trials.

[INFO 01-21 07:08:15] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:15] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.19994666666666666.

[INFO 01-21 07:08:15] ax.early_stopping.strategies.base: Trial 14's most recent progression (0.19994666666666666) that is available for metric val_acc falls out of the min/max_progression range (0.3, None). Not early stopping this trial.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:16] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:08:16] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:16] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:17] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:08:17] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:17] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:18] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:08:18] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:18] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:19] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:08:19] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:20] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.19994666666666666.

[INFO 01-21 07:08:20] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:20] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:21] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:21] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:21] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:22] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:22] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:22] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:23] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:23] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:23] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:24] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:24] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:24] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:25] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:25] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:25] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:26] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:26] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:26] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:28] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:28] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:28] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:29] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:29] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:29] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:30] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:30] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:30] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:31] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:31] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:31] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:32] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:32] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:32] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:33] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:33] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:33] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:34] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:34] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:34] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:35] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:35] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:35] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:36] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.29994666666666664.

[INFO 01-21 07:08:36] ax.early_stopping.strategies.base: No trials have reached 0.3. Not stopping any trials.

[INFO 01-21 07:08:36] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 1).

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
[INFO 01-21 07:08:37] ax.early_stopping.strategies.base: Last progression of any candidate for trial stopping is 0.3999466666666667.

[INFO 01-21 07:08:37] ax.early_stopping.strategies.percentile: Considering trial 14 for early stopping.

[INFO 01-21 07:08:37] ax.early_stopping.strategies.base: Last progression of Trial 14 is 0.3999466666666667.

[INFO 01-21 07:08:37] ax.early_stopping.strategies.percentile: Early stopping objective at last progression is:
1     0.943242
2     0.959307
3     0.935194
4     0.898628
5     0.932184
6     0.964392
7     0.960921
8     0.932884
9     0.953034
10    0.952429
11    0.953859
12    0.945040
13    0.959663
14    0.952687
Name: 0.3999466666666667, dtype: float64.

[INFO 01-21 07:08:37] ax.early_stopping.strategies.percentile: Early stopping decision for 14: True. Reason: Trial objective value 0.9526873230934143 is worse than 70.0-th percentile (0.9544037163257599) across comparable trials.

CPU times: user 2min 4s, sys: 2.65 s, total: 2min 7s
Wall time: 23min 31s

OptimizationResult()

## Results

First, we examine the data stored on the experiment. This shows that each trial is associated with an entire learning curve, represented by the column "steps".

In [15]:
experiment.lookup_data().map_df.head(n=10)

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

  arm_name metric_name      mean  sem  trial_index     step
0      1_0     val_acc  0.905008  NaN            1   1874.0
1      1_0     val_acc  0.923650  NaN            1   3749.0
2      1_0     val_acc  0.938412  NaN            1   5624.0
3      1_0     val_acc  0.943242  NaN            1   7499.0
4      1_0     val_acc  0.950077  NaN            1   9374.0
5      1_0     val_acc  0.953664  NaN            1  11249.0
6      1_0     val_acc  0.956219  NaN            1  13124.0
7      1_0     val_acc  0.955744  NaN            1  14999.0
8      1_0     val_acc  0.960212  NaN            1  16874.0
9      1_0     val_acc  0.959721  NaN            1  18749.0

Below is a summary of the experiment, showing that a portion of trials have been early stopped.

In [16]:
exp_to_df(experiment)

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

,trial_index,arm_name,trial_status,generation_method,val_acc,hidden_size_1,hidden_size_2,learning_rate,dropout
0,0,0_0,FAILED,Sobol,NaN,28,23,0.006756,0.072450
1,1,1_0,COMPLETED,Sobol,0.959721,105,54,0.000213,0.482881
2,2,2_0,COMPLETED,Sobol,0.962203,51,28,0.001132,0.157062
3,3,3_0,COMPLETED,Sobol,0.948714,26,113,0.000358,0.254505
4,4,4_0,COMPLETED,Sobol,0.911162,16,36,0.000159,0.320062
5,5,5_0,COMPLETED,Sobol,0.927991,64,96,0.005031,0.222620
6,6,6_0,COMPLETED,BoTorch,0.966897,63,17,0.001455,0.046219
7,7,7_0,EARLY_STOPPED,BoTorch,0.959047,50,49,0.000467,0.062047
8,8,8_0,EARLY_STOPPED,BoTorch,0.932884,51,24,0.002555,0.327380
9,9,9_0,EARLY_STOPPED,BoTorch,0.953034,75,33,0.000617,0.340276
10,10,10_0,EARLY_STOPPED,BoTorch,0.952429,40,35,0.001449,0.010330
11,11,11_0,EARLY_STOPPED,BoTorch,0.957027,73,35,0.000551,0.304886
12,12,12_0,EARLY_STOPPED,BoTorch,0.945040,36,31,0.002512,0.087335
13,13,13_0,EARLY_STOPPED,BoTorch,0.961808,87,20,0.000581,0.000000
14,14,14_0,EARLY_STOPPED,BoTorch,0.952687,36,16,0.002077,0.000000

We can give a very rough estimate of the amount of computational savings due to early stopping, by looking at the total number of steps used when early stopping is used versus the number of steps used if we ran all trials to completion. Note to do a true comparison, one should run full HPO loops with and without early stopping (as early stopping will influence the model and future points selected by the generation strategy).

In [17]:
map_df = experiment.lookup_data().map_df
trial_to_max_steps = map_df.groupby("trial_index")["step"].max()
completed_trial_steps = trial_to_max_steps.iloc[0]
savings = 1.0 - trial_to_max_steps.sum() / (
    completed_trial_steps * len(trial_to_max_steps)
)
# TODO format nicer
print(f"A rough estimate of the computational savings is {100 * savings}%.")

A rough estimate of the computational savings is 31.43161904761905%.

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(

## Visualizations

Finally, we show a visualization of learning curves versus actual elapsed wall time. This helps to illustrate that stopped trials make room for additional trials to be run.

In [18]:
# helper function for getting trial start times
def time_started(row):
    trial_index = row["trial_index"]
    return experiment.trials[trial_index].time_run_started


# helper function for getting trial completion times
def time_completed(row):
    trial_index = row["trial_index"]
    return experiment.trials[trial_index].time_completed


# helper function for getting relevant data from experiment
# with early stopping into useful dfs
def early_stopping_exp_to_df(experiment):
    trials_df = exp_to_df(experiment)
    curve_df = experiment.lookup_data().map_df
    training_row_df = (
        curve_df.groupby("trial_index").max().reset_index()[["trial_index", "steps"]]
    )
    trials_df = trials_df.merge(training_row_df, on="trial_index")
    trials_df["time_started"] = trials_df.apply(func=time_started, axis=1)
    trials_df["time_completed"] = trials_df.apply(func=time_completed, axis=1)
    start_time = trials_df["time_started"].min()
    trials_df["time_started_rel"] = (
        trials_df["time_started"] - start_time
    ).dt.total_seconds()
    trials_df["time_completed_rel"] = (
        trials_df["time_completed"] - start_time
    ).dt.total_seconds()
    return trials_df, curve_df


def plot_curves_by_wall_time(trials_df, curve_df):
    trials = set(curve_df["trial_index"])
    fig, ax = plt.subplots(1, 1, figsize=(10, 6))
    ax.set(xlabel="seconds since start", ylabel="validation accuracy")
    for trial_index in trials:
        this_trial_df = curve_df[curve_df["trial_index"] == trial_index]
        start_time_rel = trials_df["time_started_rel"].iloc[trial_index]
        completed_time_rel = trials_df["time_completed_rel"].iloc[trial_index]
        total_steps = trials_df.loc[trial_index, "steps"]
        smoothed_curve = this_trial_df["mean"].rolling(window=3).mean()
        x = (
            start_time_rel
            + (completed_time_rel - start_time_rel)
            / total_steps
            * this_trial_df["steps"]
        )
        ax.plot(
            x,
            smoothed_curve,
            label=f"trial #{trial_index}" if trial_index % 2 == 1 else None,
        )
    ax.legend()

In [19]:
# wrap in try/except in case of flaky I/O issues
try:
    trials_df, curve_df = early_stopping_exp_to_df(experiment)
    plot_curves_by_wall_time(trials_df, curve_df)
except Exception as e:
    print(f"Encountered exception while plotting results: {e}")

Encountered exception while plotting results: "['steps'] not in index"

/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(
/tmp/tmp.qaLmkqmL9U/Ax-main/ax/core/map_data.py:216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(